### ISSUE TITLE
[BUG]: AssertionError when running the benchmark

### ISSUE THREAD

**Issue by Ethan707** [hpcaitech/ColossalAI#1006]
### 🐛 Describe the bug

When I tried to run the benchmark on single GPU (3080Ti)
```
colossalai benchmark --gpus 1
```

It gave me this error:
```
=== Benchmarking Parameters ===
gpus: 1
batch_size: 8
seq_len: 512
dimension: 1024
warmup_steps: 10
profile_steps: 50
layers: 2
model: mlp

=== size: 1, mode: None ===
Average forward time: 0.0008550882339477539
Average backward time: 0.001253962516784668
Max allocated GPU memory: 0.26564550399780273
Max cached GPU memory: 0.287109375

=== size: 1, mode: 1d ===
Average forward time: 0.0009281635284423828
Average backward time: 0.0013220453262329103
Max allocated GPU memory: 0.26564550399780273
Max cached GPU memory: 0.287109375

Traceback (most recent call last):
  File "/home/ethan/anaconda3/bin/colossalai", line 8, in <module>
    sys.exit(cli())
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/cli/benchmark/__init__.py", line 28, in benchmark
    run_benchmark(args)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/cli/benchmark/benchmark.py", line 40, in run_benchmark
    mp.spawn(run_func, nprocs=args.gpus)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 240, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/cli/benchmark/benchmark.py", line 79, in run_dist_profiling
    fwd_time, bwd_time, max_allocated, max_cached = profile_model(model=model,
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/cli/benchmark/utils.py", line 118, in profile_model
    _run_step(data)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/cli/benchmark/utils.py", line 110, in _run_step
    out = model(data)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/cli/benchmark/models.py", line 16, in forward
    x = layer(x)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/nn/layer/colossalai_layer/_utils.py", line 38, in forward
    return self._forward_func(*args)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/nn/layer/parallel_2d/layers.py", line 187, in forward
    output = Matmul_AB_2D.apply(x, self.weight, self.summa_dim, out_shape, self.row_rank, self.col_rank,
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/torch/cuda/amp/autocast_mode.py", line 118, in decorate_fwd
    return fwd(*args, **kwargs)
  File "/home/ethan/anaconda3/lib/python3.9/site-packages/colossalai/nn/layer/parallel_2d/_operation.py", line 207, in forward
    assert A.shape[-1] == B.shape[-2], \
AssertionError: Invalid shapes: A=torch.Size([4, 512, 512]), B=torch.Size([1024, 1024]) for AB.
```

### Environment

I installed colossalai from official releases
```
pip install colossalai==0.1.5+torch1.11cu11.3 -f https://release.colossalai.org
```
And it also pass the check
```
$ colossalai check -i
CUDA Version: 11.3
PyTorch Version: 1.11.0
CUDA Version in PyTorch Build: 11.3
PyTorch CUDA Version Match: ✓
CUDA Extension: ✓
```

`nvidia-smi`:
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.73.05    Driver Version: 510.73.05    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   59C    P3    81W / 350W |    923MiB / 12288MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
```

`nvcc -V`:
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Sun_Mar_21_19:15:46_PDT_2021
Cuda compilation tools, release 11.3, V11.3.58
Build cuda_11.3.r11.3/compiler.29745058_0
```

**Comment by FrankLeeeee** [comment]
Hi @Ethan707 , tensor parallelism is not enabled when running with 1 GPU. You can try with 4 or 8 GPUs instead.
