### ISSUE TITLE
[BUG]: KeyError: KeyError'SLURM_PROCID'

### ISSUE THREAD

**Issue by elricwan** [hpcaitech/ColossalAI#1023]
### 🐛 Describe the bug

I am trying to run the gpt2 example with gpt2_1d configuration. I follow the instruction and run the command:

export DATA=dataset/train_data.json

colossalai run --nproc_per_node=2 train_gpt.py --config=gpt2_configs/gpt2_1d.py

The running log is:

Colossalai should be built with cuda extension to use the FP16 optimizer
If you want to activate cuda mode for MoE, please install with cuda_ext!
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Colossalai should be built with cuda extension to use the FP16 optimizer
If you want to activate cuda mode for MoE, please install with cuda_ext!
Colossalai should be built with cuda extension to use the FP16 optimizer
If you want to activate cuda mode for MoE, please install with cuda_ext!
Traceback (most recent call last):
  File "/home/protago/miniconda3/envs/coloai/lib/python3.8/site-packages/colossalai/initialize.py", line 142, in launch_from_slurm
    rank = int(os.environ['SLURM_PROCID'])
  File "/home/protago/miniconda3/envs/coloai/lib/python3.8/os.py", line 673, in __getitem__
Traceback (most recent call last):
  File "/home/protago/miniconda3/envs/coloai/lib/python3.8/site-packages/colossalai/initialize.py", line 142, in launch_from_slurm
    rank = int(os.environ['SLURM_PROCID'])
  File "/home/protago/miniconda3/envs/coloai/lib/python3.8/os.py", line 673, in __getitem__
        raise KeyError(key) from None
raise KeyError(key) from None
KeyError: KeyError'SLURM_PROCID'
: 
During handling of the above exception, another exception occurred:

'SLURM_PROCID'

### Environment

CUDA: 11.1
pytorch: 1.11.0
python: 3.8

**Comment by YuliangLiu0306** [comment]
You can add --from_torch argument if you do not launch your program from slurm. Try 'colossalai run --nproc_per_node=2 train_gpt.py --config=gpt2_configs/gpt2_1d.py --from_torch' in your terminal, it should work as expected.  Sorry about this, I will add some notes about this in readme.

**Comment by elricwan** [comment]
Thanks for the quick reply, it works now. However, it stuck during build dataloader:
```
 INFO     colossalai - colossalai - INFO: /home/protago/minic
                             onda3/envs/coloai/lib/python3.8/site-packages/colos
                             salai/initialize.py:117 launch
                    INFO     colossalai - colossalai - INFO: Distributed
                             environment is initialized, data parallel size: 1,
                             pipeline parallel size: 1, tensor parallel size: 2
                    INFO     colossalai - colossalai - INFO: train_gpt.py:47
                             main
                    INFO     colossalai - colossalai - INFO: Build data loader
```
How long would it take to build data loader for Webtext Dataset?

**Comment by YuliangLiu0306** [comment]
It takes sevaral minutes to build dataloader. If the process takes long than that, you should check whether your dataset is built correctly.
