### ISSUE TITLE
[FEATURE]:  Instantiate a pre-trained model with ZeroInitContext

### ISSUE THREAD

**Issue by Alexzhuan** [hpcaitech/ColossalAI#1038]
### Describe the feature

It seems not to support instantiating a pre-trained model from a checkpoint with ZeroInitContext.

For example, when instantiating a `bert-base` using HuggingFace API with ZeroInitContext:
```python
with ZeroInitContext(target_device=torch.cuda.current_device(), 
                                    shard_strategy=shard_strategy,
                                    shard_param=True):
    model = BertModel.from_pretrained("bert-base-uncased")
```

I understand that when using `.from_pretrained()`, it will first instantiate a model, and then load the `state_dict` from a pre-trained checkpoint. However, in the `ZeroInitContext`, when instantiating a model, it then shards the parameters, which will cause the failure of directly loading a pre-trained checkpoint.

Is it possible to instantiate a pre-trained model with ZeroInitContext? 

Thanks!

**Comment by ver217** [comment]
Hi, I impletemented this feature in https://github.com/hpcaitech/ColossalAI/pull/894.
You can install the latest colossalai and try!

**Comment by Alexzhuan** [comment]
Thanks for your reply!

However, when I try to re-install colossalai by the latest repository, it will raise some errors. The part of error information is as follows:

```shell
ninja: build stopped: subcommand failed.
      Traceback (most recent call last):
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1740, in _run_ninja_build
          subprocess.run(
        File "/data/anaconda3/envs/bert/lib/python3.8/subprocess.py", line 516, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/data/project/ColossalAI/setup.py", line 194, in <module>
          setup(
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
          return run_commands(dist)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
          dist.run_commands()
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
          self.run_command(cmd)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/command/build.py", line 136, in run
          self.run_command(cmd_name)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
          super().run_command(command)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
          cmd_obj.run()
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 339, in run
          self.build_extensions()
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 741, in build_extensions
          build_ext.build_extensions(self)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 448, in build_extensions
          self._build_extensions_serial()
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 473, in _build_extensions_serial
          self.build_extension(ext)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 202, in build_extension
          _build_ext.build_extension(self, ext)
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 528, in build_extension
          objects = self.compiler.compile(sources,
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 562, in unix_wrap_ninja_compile
          _write_ninja_file_and_compile_objects(
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1419, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/data/anaconda3/envs/bert/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for colossalai
  Running setup.py clean for colossalai
Failed to build colossalai
Installing collected packages: colossalai
  Running setup.py install for colossalai ... error          
  error: subprocess-exited-with-error
  
  × Running setup.py install for colossalai did not run successfully.
  │ exit code: 1
  ╰─> [641 lines of output]
``` 

My environments are as follows:
CUDA version: 11.3, 
Python version: 3.8, 
Pytorch version: 1.11.0+cu113.

Thanks!

**Comment by ver217** [comment]
Hi, could you tell me your OS? We only tested colossalai on Linux x86_64, and we are afraid that MacOS and Windows are not supported.

**Comment by ver217** [comment]
You can also try to install the preview version: https://colossalai.org/download
It contains this feature.

**Comment by Alexzhuan** [comment]
Hi, 
I have installed the preview version successfully, and now could load the pre-trained checkpoint!
Thank you!

**Comment by created-Bi** [comment]
hello, I encountered a "Import 'colossalai.zero.init_ctx' could not be resolved" problem. Could it caused by the low version of colossalai?

python == 3.9.16
colossalai == 0.2.8
