### ISSUE TITLE
[BUG] please update pypi version

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#104]
**Describe the bug**
I use the colossal installed from pypi, it failed to run a resnet example!
```
python -m torch.distributed.launch --nproc_per_node 1 run_resnet_cifar10_with_engine.py

Colossalai should be built with cuda extension to use the FP16 optimizer
Colossalai should be built with cuda extension to use the FP16 optimizer
DeepSpeed is required if you want to use ZeRO.
DeepSpeed is required if you want to use ZeRO.
Traceback (most recent call last):
  File "run_resnet_cifar10_with_engine.py", line 7, in <module>
    from colossalai.utils import get_dataloader
ImportError: cannot import name 'get_dataloader' from 'colossalai.utils' (/home/jiaruifang/anaconda3/envs/deepalpha/lib/python3.7/site-packages/colossalai/utils/__init__.py)
Killing subprocess 1397423
Traceback (most recent call last):
  File "/home/jiaruifang/anaconda3/envs/deepalpha/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jiaruifang/anaconda3/envs/deepalpha/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/jiaruifang/anaconda3/envs/deepalpha/lib/python3.7/site-packages/torch/distributed/launch.py", line 340, in <module>
    main()
  File "/home/jiaruifang/anaconda3/envs/deepalpha/lib/python3.7/site-packages/torch/distributed/launch.py", line 326, in main
    sigkill_handler(signal.SIGTERM, None)  # not coming back
  File "/home/jiaruifang/anaconda3/envs/deepalpha/lib/python3.7/site-packages/torch/distributed/launch.py", line 301, in sigkill_handler
    raise subprocess.CalledProcessError(returncode=last_return_code, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/jiaruifang/anaconda3/envs/deepalpha/bin/python', '-u', 'run_resnet_cifar10_with_engine.py', '--local_rank=0']' returned non-zero exit status 1.
```

**To Reproduce**
```
pip install colossalai
cd examples/resnet_cifar10_data_parallel
python -m torch.distributed.launch --nproc_per_node 1 run_resnet_cifar10_with_engine.py
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - CUDA version:
 - cuDNN version:
 - NCCL version:
 - Python version:
 - PyTorch version: 

**Additional context**

**Comment by binmakeswell** [comment]
Hi, feifeibear,

Thank you for your comments.
Sorry for the inconvenience and confusion. Since we are still in the intensive update stage, in order to avoid version confusion, we plan to update pypi uniformly after the code is stable. We also stated in the description in project README and document, which recommends installing from source rather than through pypi.

Sincerely,
Bin
