### ISSUE TITLE
[BUG]: colossalai check failed in NGC pytorch 21.07

### ISSUE THREAD

**Issue by LSC527** [hpcaitech/ColossalAI#1043]
### 🐛 Describe the bug

I built the docker images sucessfully following the [instructions](https://github.com/hpcaitech/ColossalAI#use-docker). And then I run `colossalai check -i` and check failed with the following trace:
```
Traceback (most recent call last):
  File "/opt/conda/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/opt/conda/lib/python3.8/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (initialize, launch, launch_from_openmpi,
  File "/opt/conda/lib/python3.8/site-packages/colossalai/initialize.py", line 23, in <module>
    from colossalai.engine.schedule import NonPipelineSchedule, PipelineSchedule, InterleavedPipelineSchedule, get_tensor_shape
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/__init__.py", line 1, in <module>
    from ._base_engine import Engine
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 11, in <module>
    from colossalai.engine.schedule import BaseSchedule, NonPipelineSchedule, PipelineSchedule, InterleavedPipelineSchedule
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/schedule/__init__.py", line 1, in <module>
    from ._base_schedule import BaseSchedule
  File "/opt/conda/lib/python3.8/site-packages/colossalai/engine/schedule/_base_schedule.py", line 10, in <module>
    from colossalai.utils import get_current_device
  File "/opt/conda/lib/python3.8/site-packages/colossalai/utils/__init__.py", line 15, in <module>
    from .model.colo_init_context import ColoInitContext
  File "/opt/conda/lib/python3.8/site-packages/colossalai/utils/model/colo_init_context.py", line 3, in <module>
    from colossalai.tensor import ColoTensor, ColoParameter, register_colo_module, init_colo_module, \
  File "/opt/conda/lib/python3.8/site-packages/colossalai/tensor/__init__.py", line 4, in <module>
    from .colo_tensor import ColoTensor
  File "/opt/conda/lib/python3.8/site-packages/colossalai/tensor/colo_tensor.py", line 7, in <module>
    from colossalai.tensor.dist_spec_mgr import DistSpecManager
  File "/opt/conda/lib/python3.8/site-packages/colossalai/tensor/dist_spec_mgr.py", line 2, in <module>
    from colossalai.nn.layer.utils import divide
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/__init__.py", line 1, in <module>
    from .layer import *
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/layer/__init__.py", line 7, in <module>
    from .moe import *
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/layer/moe/__init__.py", line 1, in <module>
    from .experts import Experts, FFNExperts, TPExperts
  File "/opt/conda/lib/python3.8/site-packages/colossalai/nn/layer/moe/experts.py", line 8, in <module>
    from colossalai.zero.init_ctx import no_shard_zero_decrator
  File "/opt/conda/lib/python3.8/site-packages/colossalai/zero/__init__.py", line 6, in <module>
    from colossalai.zero.sharded_model.sharded_model_v2 import ShardedModelV2
  File "/opt/conda/lib/python3.8/site-packages/colossalai/zero/sharded_model/__init__.py", line 1, in <module>
    from .sharded_model_v2 import ShardedModelV2
  File "/opt/conda/lib/python3.8/site-packages/colossalai/zero/sharded_model/sharded_model_v2.py", line 5, in <module>
    from torch.nn.modules.module import _EXTRA_STATE_KEY_SUFFIX
ImportError: cannot import name '_EXTRA_STATE_KEY_SUFFIX' from 'torch.nn.modules.module' (/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py)

```

### Environment

NGC pytorch 21.07

**Comment by LSC527** [comment]
I tried Dockerfile in the latest branch and colossalai check sucessed.

**Comment by LSC527** [comment]
However, the same error occured when building colossalai from source in a conda env with colossalai-0.1.5+torch1.8cu11.6

**Comment by FrankLeeeee** [comment]
> However, the same error occured when building colossalai from source in a conda env with colossalai-0.1.5+torch1.8cu11.6

This occurs perhaps because of API incompatibility of PyTorch, you can try a higher version PyTorch like 1.10 and 1.11.
