### ISSUE TITLE
[BUG] initialize context failed using pytorch 1.10

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#105]
**Describe the bug**
```
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
warning: variables which starts with __, is a module or class declaration are omitted
Traceback (most recent call last):
  File "run_resnet_cifar10_with_trainer.py", line 118, in <module>
    main()
  File "run_resnet_cifar10_with_trainer.py", line 19, in main
    colossalai.launch_from_torch(config='./config.py')
  File "/opt/conda/lib/python3.8/site-packages/colossalai/initialize.py", line 209, in launch_from_torch
    launch(config=config,
  File "/opt/conda/lib/python3.8/site-packages/colossalai/initialize.py", line 101, in launch
    gpc.init_global_dist(rank, world_size, backend, host, port)
  File "/opt/conda/lib/python3.8/site-packages/colossalai/context/parallel_context.py", line 322, in init_global_dist
    dist.init_process_group(rank=rank,
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 559, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/rendezvous.py", line 141, in _tcp_rendezvous_handler
    store = TCPStore(  # type: ignore[call-arg]
RuntimeError: Address already in use

```

**To Reproduce**
```
cd examples/resnet_cifar10_data_parallel
examples/resnet_cifar10_data_parallel
env DATA="./cifar10_data" python -m torch.distributed.launch --nproc_per_node=1 run_resnet_cifar10_with_engine.py
```

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - CUDA version:  cuda_11.4.r11.4/compiler.30188945_0
 - cuDNN version:
 - NCCL version:
 - Python version: 3.8.10
 - PyTorch version: 1.10.0a0+3fd9dcf

**Additional context**
I believe the bug come from the L321 of colossalai/context/parallel_context.py.

**Comment by kurisusnowdeng** [comment]
Hi. This is because someone else is using the same port on the same server. Please try another port by adding the option `--master_port=ANY_OTHER_PORT` after `python -m torch.distributed.launch` and `run_resnet_cifar10_with_engine.py`

**Comment by feifeibear** [comment]
It dose not work
