### ISSUE TITLE
[BUG] RuntimeError: Address already in use

### ISSUE THREAD

**Issue by Arsmart123** [hpcaitech/ColossalAI#110]
**Describe the bug**
Traceback (most recent call last):
  File "train.py", line 132, in <module>
    train_cifar()
  File "train.py", line 73, in train_cifar
    colossalai.launch_from_torch(config=args.config)
  File "/home/svu/e0787810/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/colossalai/initialize.py", line 217, in launch_from_torch
    verbose=verbose)
  File "/home/svu/e078XXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/colossalai/initialize.py", line 101, in launch
    gpc.init_global_dist(rank, world_size, backend, host, port)
  File "/home/svu/e078XXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/colossalai/context/parallel_context.py", line 325, in init_global_dist
    init_method=init_method)
  File "/home/svu/e078XXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py", line 576, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "/home/svu/e078XXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 183, in _tcp_rendezvous_handler
    store = _create_c10d_store(result.hostname, result.port, rank, world_size, timeout)
  File "/home/svu/e078XXXX/.conda/miniconda/envs/huang_test/lib/python3.6/site-packages/torch/distributed/rendezvous.py", line 158, in _create_c10d_store
    hostname, port, world_size, start_daemon, timeout, multi_tenant=True
RuntimeError: Address already in use

I am running this on NUS HPC, and for hostname, I use 'hostname -l' instrucution to get four IPs, I tried one of them, for port, I randomly choose a number. Not sure how to find an acceptable address.

**Comment by kurisusnowdeng** [comment]
Hi. Could you first try `netstat -tunlp | grep PORT` to check whether `PORT` is available?

**Comment by Arsmart123** [comment]
I think I solve this problem now...The thing is when I first run it, it will be blocked because incorrect arg settings, and then I disrupt it and rerun it again, but the port used by last turn still exists and will block this new run! Generally, the port is not the key point here..Thank you!!
