### ISSUE TITLE
[BUG] failed to run a gpt2_xl test case

### ISSUE THREAD

**Issue by feifeibear** [hpcaitech/ColossalAI#116]
I wrote a GPT2 test case and tried gpt_small and gpt_large. they are fine. However, it failed on gpt2_xl.
For more details see my MR #115 .
BTW: What is the unit of throughput? Can you provide a Tflops metrics? It is a task-irrelevant indicator that reflects the utilization of hardware computing power.
Tflops = (model_numel * batch_size * sequence_length * 2 * 4) / elapse per iter

On a 8 GPU node.
```
cd examples/gpt
bash run.sh
```

```
Traceback (most recent call last):
  File "run_gpt2_with_engine.py", line 110, in <module>
Traceback (most recent call last):
  File "run_gpt2_with_engine.py", line 110, in <module>
    train_gpt()
  File "run_gpt2_with_engine.py", line 106, in train_gpt
    trainer.fit(train_dataloader=train_dataloader, epochs=gpc.config.NUM_EPOCHS, hooks=hook_list, display_progress=True)
  File "/workspace/ColossalAI/colossalai/trainer/_trainer.py", line 312, in fit
    train_gpt()
  File "run_gpt2_with_engine.py", line 106, in train_gpt
    self._train_epoch(
  File "/workspace/ColossalAI/colossalai/trainer/_trainer.py", line 178, in _train_epoch
    trainer.fit(train_dataloader=train_dataloader, epochs=gpc.config.NUM_EPOCHS, hooks=hook_list, display_progress=True)
  File "/workspace/ColossalAI/colossalai/trainer/_trainer.py", line 312, in fit
    logits, label, loss = self.schedule.forward_backward_step(
  File "/workspace/ColossalAI/colossalai/engine/schedule/_non_pipeline_schedule.py", line 52, in forward_backward_step
    output = self._call_engine(engine, data)
  File "/workspace/ColossalAI/colossalai/engine/schedule/_base_schedule.py", line 98, in _call_engine
    self._train_epoch(
  File "/workspace/ColossalAI/colossalai/trainer/_trainer.py", line 178, in _train_epoch
    return engine(inputs)
  File "/workspace/ColossalAI/colossalai/engine/_base_engine.py", line 112, in __call__
    logits, label, loss = self.schedule.forward_backward_step(
      File "/workspace/ColossalAI/colossalai/engine/schedule/_non_pipeline_schedule.py", line 52, in forward_backward_step
return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    output = self._call_engine(engine, data)
  File "/workspace/ColossalAI/colossalai/engine/schedule/_base_schedule.py", line 98, in _call_engine
    return engine(inputs)
  File "/workspace/ColossalAI/colossalai/engine/_base_engine.py", line 112, in __call__
    return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 871, in forward
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 871, in forward
    output = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    output = self.module(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 18, in decorate_autocast
    return func(*args, **kwargs)
  File "/workspace/ColossalAI/colossalai/amp/torch_amp/torch_amp.py", line 63, in forward
    return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/cuda/amp/autocast_mode.py", line 18, in decorate_autocast
    return func(*args, **kwargs)
  File "/workspace/ColossalAI/colossalai/amp/torch_amp/torch_amp.py", line 63, in forward
    return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ColossalAI/model_zoo/gpt/gpt.py", line 245, in forward
    x, attention_mask = block(x, attention_mask)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ColossalAI/model_zoo/gpt/gpt.py", line 245, in forward
    x, attention_mask = block(x, attention_mask)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ColossalAI/colossalai/nn/layer/utils/common.py", line 26, in forward
    return checkpoint(self._forward, *args, **kwargs)
  File "/workspace/ColossalAI/colossalai/utils/activation_checkpoint.py", line 117, in checkpoint
    return CheckpointFunction.apply(function, *args)
  File "/workspace/ColossalAI/colossalai/utils/activation_checkpoint.py", line 44, in forward
    outputs = run_function(*args)
  File "/workspace/ColossalAI/model_zoo/gpt/gpt.py", line 148, in _forward
    return forward_call(*input, **kwargs)
  File "/workspace/ColossalAI/colossalai/nn/layer/utils/common.py", line 26, in forward
    return checkpoint(self._forward, *args, **kwargs)
x = x + self.attn(self.norm1(x), attention_mask)  File "/workspace/ColossalAI/colossalai/utils/activation_checkpoint.py", line 117, in checkpoint

  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return CheckpointFunction.apply(function, *args)
  File "/workspace/ColossalAI/colossalai/utils/activation_checkpoint.py", line 44, in forward
    outputs = run_function(*args)
  File "/workspace/ColossalAI/model_zoo/gpt/gpt.py", line 148, in _forward
    x = x + self.attn(self.norm1(x), attention_mask)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1056, in _call_impl
    return forward_call(*input, **kwargs)
  File "/workspace/ColossalAI/model_zoo/gpt/gpt.py", line 72, in forward
    qkv = qkv.view(new_qkv_shape)
RuntimeError: shape '[8, 1024, 6, 192]' is invalid for input of size 9830400
    return forward_call(*input, **kwargs)
  File "/workspace/ColossalAI/model_zoo/gpt/gpt.py", line 72, in forward
    qkv = qkv.view(new_qkv_shape)
RuntimeError: shape '[8, 1024, 6, 192]' is invalid for input of size 9830400
```

**Comment by kurisusnowdeng** [comment]
Hi. The problem is supposed to be that the number of attention heads of GPT-XL is 25, which cannot be divided by the tensor parallel size 4. We will improve the related error messages very soon.
