### ISSUE TITLE
[BUG]: Colossalai doesn't support (mini)conda python?

### ISSUE THREAD

**Issue by fuhengwu2021** [hpcaitech/ColossalAI#1668]
### 🐛 Describe the bug

I am using miniconda python, but colossalai always uses the python in `/usr/bin/python3`

I observed this when reporting https://github.com/hpcaitech/ColossalAI-Examples/issues/176 .

The python interpreter I am using is:

```
$which python
/home/wfh/miniconda3/envs/colossai-py3.8/bin/python
```
But ColossalAI seems using a different python interpreter: `/usr/bin/python3`

Relevant error logs are below:

(Please be noted with this line `ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 868127) of binary: /usr/bin/python3`)

```
...
RuntimeError: CUDA out of memory. Tried to allocate 148.00 MiB (GPU 5; 15.78 GiB total capacity; 9.65 GiB already allocated; 63.19 MiB free; 9.79 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 868127) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/wfh/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/wfh/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/wfh/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/home/wfh/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/home/wfh/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/wfh/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_with_cifar10.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2022-09-28_16:45:26
  host      : tesla-shared
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 868128)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2022-09-28_16:45:26
  host      : tesla-shared
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 868129)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2022-09-28_16:45:26
  host      : tesla-shared
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 868130)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2022-09-28_16:45:26
  host      : tesla-shared
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 868131)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2022-09-28_16:45:26
  host      : tesla-shared
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 868132)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2022-09-28_16:45:26
  host      : tesla-shared
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 868133)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2022-09-28_16:45:26
  host      : tesla-shared
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 868127)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Error: failed to run torchrun --nproc_per_node=7 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=127.0.0.1:29500 --rdzv_id=colossalai-default-job train_with_cifar10.py --config config.py on 127.0.0.1
```

### Environment

```
>>> import colossalai
>>> colossalai.__version__
'0.1.9'
>>> import torch
>>> torch.__version__
'1.12.1+cu113'
```

**Comment by Cypher30** [comment]
The issue has been solved by @Fazziekey

**Comment by Fazziekey** [comment]
use the python 3.9
