### ISSUE TITLE
torchrun command not found error when launching on multi-nodes

### ISSUE THREAD

**Issue by frankxyy** [hpcaitech/ColossalAI#1779]
![image](https://user-images.githubusercontent.com/6971044/199020846-b1af70e3-0030-4254-973a-de2f668bdf85.png)

The error is as above. However，if i personnally ssh the worker node and run torchrun, this command exists. I have added conda activate into the .bashrc file.

![image](https://user-images.githubusercontent.com/6971044/199021257-f2bd55cf-6a8c-416a-bd88-360ee5b19b3c.png)

**Comment by Cypher30** [comment]
Could you please test if you have already installed `torchrun` on host 172.27.231.79?

**Comment by frankxyy** [comment]
@Cypher30 hi, I have installed torchrun, as you can see from the second picture. The problem occurs maybe of the reason that the .bashrc and .bash_profile is not executed on host 172.27.231.79. Maybe it is the issue of fabric library?

**Comment by FrankLeeeee** [comment]
The fabric library should have propagated the `$PATH` variable to another machine.

**Comment by frankxyy** [comment]
@FrankLeeeee @Cypher30 I fixed this error by set publickey for 172.27.231.79 to visit itself.

Now another error occured:

```
(colossalai) [root@m5-autorl-test01 demo]# cuda_visible_devices=2,4 colossalai run --nproc_per_node 2 --host 172.27.231.79,172.26.1.24 --master_addr 172.27.231.79 run_resnet_cifar10_with_engine.py
_meta_registrations seems to be incompatible with PyTorch 1.11.0+cu113.
[11/01/22 17:46:50] INFO     colossalai - paramiko.transport - INFO: Connected (version 2.0, client OpenSSH_7.4)
                    INFO     colossalai - paramiko.transport - INFO: Authentication (publickey) successful!
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "IndexError: list index out of range",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py\", line 345, in wrapper\n    return f(*args, **kwargs)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/run.py\", line 719, in main\n    run(args)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/run.py\", line 713, in run\n    )(*cmd_args)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/launcher/api.py\", line 131, in __call__\n    return launch_agent(self._config, self._entrypoint, list(args))\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/launcher/api.py\", line 252, in launch_agent\n    result = agent.run()\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 709, in run\n    result = self._invoke_run(role)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 837, in _invoke_run\n    self._initialize_workers(self._worker_group)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 678, in _initialize_workers\n    self._rendezvous(worker_group)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 541, in _rendezvous\n    workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py\", line 125, in wrapper\n    result = f(*args, **kwargs)\n  File \"/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py\", line 611, in _assign_worker_ranks\n    my_role_info = role_infos[group_rank]\nIndexError: list index out of range\n",
      "timestamp": "1667296264"
    }
  }
}
Traceback (most recent call last):
  File "/usr/local/bin/torchrun", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/run.py", line 713, in run
    )(*cmd_args)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/launcher/api.py", line 252, in launch_agent
    result = agent.run()
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 837, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 541, in _rendezvous
    workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/distributed/elastic/agent/server/api.py", line 611, in _assign_worker_ranks
    my_role_info = role_infos[group_rank]
IndexError: list index out of range
Error: failed to run torchrun --nproc_per_node=2 --nnodes=2 --node_rank=1 --rdzv_backend=c10d --rdzv_endpoint=172.27.231.79:29500 --rdzv_id=colossalai-default-job run_resnet_cifar10_with_engine.py on 172.26.1.24
```

**Comment by frankxyy** [comment]
From the log, why torchrun command is executed on node 172.26.1.24 with  --rdzv_endpoint=172.27.231.79:29500 argument which is not consistent with the ip of the node？

**Comment by frankxyy** [comment]
This error is solved as I change one of the machine. However, root cuase is unknown.

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
