### ISSUE TITLE
[BUG]: ZeRO mode  AssertionError: PRE FWD param.data must be on CUDA

### ISSUE THREAD

**Issue by marsggbo** [hpcaitech/ColossalAI#1892]
### 🐛 Describe the bug

ZeRO doesn’t support models with a dynamic forward 

I modified this [example](https://github.com/hpcaitech/ColossalAI-Examples/blob/main/features/zero/train.py) by using the following model, which has a dynamic forward function:

```python
class NASModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = torch.nn.Conv2d(3, 512, kernel_size=3, stride=1, padding=1, bias=False)
        self.conv2 = torch.nn.Conv2d(512, 1024, kernel_size=3, stride=1, padding=1, bias=False)
        self.conv3 = torch.nn.Conv2d(512, 1024, kernel_size=5, stride=1, padding=2, bias=False)
        self.gavg = torch.nn.AdaptiveAvgPool2d((1, 1))
        self.fc = torch.nn.Linear(1024, 1000, bias=False)
        self.count = 0

    def forward(self, x):
        out = self.conv1(x)
        if self.count % 2 == 0:
            out = self.conv2(out)
        else:
            out = self.conv3(out)
        self.count += 1
        out = self.gavg(out).view(out.size(0), -1)
        out = self.fc(out)
        return out
``` 
You can reproduce the results via the source code:
https://github.com/marsggbo/ColossalNAS/blob/main/zero/dynamicZero.py

Run
torchrum --nproc_per_node=1 dynamicZero.py
The error information is as below

```bash
Traceback (most recent call last):
  File "/home/xihe/xinhe/ColossalNAS/zero/dynamicZero.py", line 120, in <module>
    main()
  File "/home/xihe/xinhe/ColossalNAS/zero/dynamicZero.py", line 98, in main
    outputs = model(x)
  File "/datasets/xihe/miniconda3/envs/colossal/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/datasets/xihe/miniconda3/envs/colossal/lib/python3.9/site-packages/colossalai/zero/sharded_model/sharded_model_v2.py", line 228, in forward
    outputs = self.module(*args, **kwargs)
  File "/datasets/xihe/miniconda3/envs/colossal/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xihe/xinhe/ColossalNAS/zero/dynamicZero.py", line 50, in forward
    out = self.conv2(out)
  File "/datasets/xihe/miniconda3/envs/colossal/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1137, in _call_impl
    result = hook(self, input)
  File "/datasets/xihe/miniconda3/envs/colossal/lib/python3.9/site-packages/colossalai/gemini/ophooks/utils.py", line 113, in _pre_forward_module_hook
    hook.pre_fwd_exec(submodule, *args)
  File "/datasets/xihe/miniconda3/envs/colossal/lib/python3.9/site-packages/colossalai/zero/utils/zero_hook.py", line 78, in pre_fwd_exec
    assert param.data.device.type == 'cuda', f"PRE FWD param.data must be on CUDA"
AssertionError: PRE FWD param.data must be on CUDA
```

**Comment by feifeibear** [comment]
@marsggbo Thanks for your feedback. 
Can you use the GeminiDDP instead of `ShardedModelV2 ` in your code. See the lastest ZeRO implementation as follows.
https://github.com/hpcaitech/ColossalAI/blob/main/examples/language/gpt/train_gpt_demo.py#L161

**Comment by 1SAA** [comment]
Hi @marsggbo,

thanks for your issue. I believe it is a bug about unused parameters. ColossalAI assumes all parameters recieve gradients in the backward pass. we may fix this bug later.

**Comment by marsggbo** [comment]
> 

Hi @1SAA , any update on this bug?

**Comment by binmakeswell** [comment]
We have updated a lot. This issue was closed due to inactivity. Thanks.
