### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by yrz7991** [hpcaitech/ColossalAI#2024]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "scripts/txt2img.py", line 344, in <module>
    main()
  File "scripts/txt2img.py", line 240, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 54, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/home/zrytest/stable-diffusion-main/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/home/zrytest/stable-diffusion-main/ldm/models/diffusion/ddpm.py", line 448, in __init__
    super().__init__(conditioning_key=conditioning_key, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_fp16'

**Comment by Fazziekey** [comment]
Thanks for your issue,I will check this problem
