### ISSUE TITLE
Duplicated 'mkdir' with MPI backend

### ISSUE THREAD

**Issue by ExtremeViscent** [hpcaitech/ColossalAI#211]
### 🐛 Describe the bug

The save checkpoint hook does not check local rank while calling `_ensure_directory_exists(checkpoint_path)`, causing multiple processes attempt to create directory and crash. Log attached.

```
Traceback (most recent call last):
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/experiment.py", line 312, in run_commandline
Traceback (most recent call last):
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/experiment.py", line 312, in run_commandline
    return self.run(
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/experiment.py", line 276, in run
    return self.run(
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/run.py", line 238, in __call__
    run()
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/workspace/ColossalAI-Examples/image/vilt/run.py", line 137, in main
    self.result = self.main_function(*args)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/workspace/ColossalAI-Examples/image/vilt/run.py", line 137, in main
    trainer.fit(
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/_trainer.py", line 312, in fit
    trainer.fit(
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/_trainer.py", line 312, in fit
    self._train_epoch(
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/_trainer.py", line 195, in _train_epoch
    self._train_epoch(
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/_trainer.py", line 195, in _train_epoch
    self._call_hooks('after_train_epoch')
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/_trainer.py", line 145, in _call_hooks
    self._call_hooks('after_train_epoch')
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/_trainer.py", line 145, in _call_hooks
    getattr(hook, func)(self)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/hooks/_checkpoint_hook.py", line 61, in after_train_epoch
    getattr(hook, func)(self)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/trainer/hooks/_checkpoint_hook.py", line 61, in after_train_epoch
    save_checkpoint(save_path,
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/utils/checkpointing.py", line 163, in save_checkpoint
    save_checkpoint(save_path,
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/utils/checkpointing.py", line 163, in save_checkpoint
    _ensure_directory_exists(checkpoint_path)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/utils/checkpointing.py", line 76, in _ensure_directory_exists
    _ensure_directory_exists(checkpoint_path)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/site-packages/colossalai/utils/checkpointing.py", line 76, in _ensure_directory_exists
    os.makedirs(dir)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/os.py", line 225, in makedirs
    os.makedirs(dir)
  File "/workspace/intel/oneapi/intelpython/latest/envs/autoaug/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: './ckpt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/workspace/ColossalAI-Examples/image/vilt/run.py", line 40, in <module>
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: './ckpt'
```

**Comment by FrankLeeeee** [comment]
Hi, let me fix this :)

**Comment by FrankLeeeee** [comment]
Hi， this issue is fiexed in #217
