### ISSUE TITLE
gpt+zero3测试报错：RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Tron1994** [hpcaitech/ColossalAI#2421]
config：https://github.com/hpcaitech/ColossalAI-Examples/blob/main/language/gpt/gpt2_configs/gpt2_zero3.py

报错：
Traceback (most recent call last):
  File "train_gpt.py", line 149, in <module>
    main()
  File "train_gpt.py", line 140, in main
    trainer.fit(train_dataloader=train_dataloader,
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/trainer/_trainer.py", line 321, in fit
    self._train_epoch(
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/trainer/_trainer.py", line 181, in _train_epoch
    logits, label, loss = self.engine.execute_schedule(
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 201, in execute_schedule
    output, label, loss = self._schedule.forward_backward_step(self, data_iter, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/schedule/_non_pipeline_schedule.py", line 78, in forward_backward_step
    output = self._call_engine(engine, data)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/schedule/_base_schedule.py", line 113, in _call_engine
    return engine(**inputs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 186, in __call__
    return self.model(*args, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/sharded_model/sharded_model_v2.py", line 235, in forward
    outputs = self.module(*args, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/titans/model/gpt/gpt.py", line 105, in forward
    x = self.embed(input_ids)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/titans/layer/embedding/gpt_embedding.py", line 39, in forward
    x = self.word_embeddings(input_ids) + self.position_embeddings(position_ids)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1109, in _call_impl
    result = hook(self, input)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/ophooks/utils.py", line 113, in _pre_forward_module_hook
    hook.pre_fwd_exec(submodule, *args)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/utils/zero_hook.py", line 73, in pre_fwd_exec
    self.adjust_module_data(module)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/utils/zero_hook.py", line 66, in adjust_module_data
    self._stateful_tensor_mgr.adjust_layout()
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/stateful_tensor_mgr.py", line 61, in adjust_layout
    vol, evict_time = self._tensor_placement_policy.evict_tensors(hold_cuda_tensor_list,
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/tensor_placement_policy.py", line 34, in evict_tensors
    colo_model_data_tensor_move_inline(t, self.device)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/tensor_utils.py", line 86, in colo_model_data_tensor_move_inline
    t.move_to(target_device)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/stateful_tensor.py", line 94, in move_to
    self.payload.data = self.payload.data.to(to_device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Traceback (most recent call last):
  File "train_gpt.py", line 149, in <module>
    main()
  File "train_gpt.py", line 140, in main
    trainer.fit(train_dataloader=train_dataloader,
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/trainer/_trainer.py", line 321, in fit
    self._train_epoch(
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/trainer/_trainer.py", line 181, in _train_epoch
    logits, label, loss = self.engine.execute_schedule(
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 201, in execute_schedule
    output, label, loss = self._schedule.forward_backward_step(self, data_iter, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/schedule/_non_pipeline_schedule.py", line 78, in forward_backward_step
    output = self._call_engine(engine, data)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/schedule/_base_schedule.py", line 113, in _call_engine
    return engine(**inputs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 186, in __call__
    return self.model(*args, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/sharded_model/sharded_model_v2.py", line 235, in forward
Traceback (most recent call last):
  File "train_gpt.py", line 149, in <module>
    outputs = self.module(*args, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/titans/model/gpt/gpt.py", line 105, in forward
    main()
  File "train_gpt.py", line 140, in main
    x = self.embed(input_ids)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    trainer.fit(train_dataloader=train_dataloader,
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/trainer/_trainer.py", line 321, in fit
    self._train_epoch(
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/trainer/_trainer.py", line 181, in _train_epoch
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/titans/layer/embedding/gpt_embedding.py", line 39, in forward
        logits, label, loss = self.engine.execute_schedule(x = self.word_embeddings(input_ids) + self.position_embeddings(position_ids)

  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1109, in _call_impl
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 201, in execute_schedule
    output, label, loss = self._schedule.forward_backward_step(self, data_iter, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/schedule/_non_pipeline_schedule.py", line 78, in forward_backward_step
    output = self._call_engine(engine, data)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/schedule/_base_schedule.py", line 113, in _call_engine
    result = hook(self, input)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/ophooks/utils.py", line 113, in _pre_forward_module_hook
    return engine(**inputs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/engine/_base_engine.py", line 186, in __call__
    hook.pre_fwd_exec(submodule, *args)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/utils/zero_hook.py", line 73, in pre_fwd_exec
    return self.model(*args, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    self.adjust_module_data(module)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/utils/zero_hook.py", line 66, in adjust_module_data
    self._stateful_tensor_mgr.adjust_layout()
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/stateful_tensor_mgr.py", line 61, in adjust_layout
    vol, evict_time = self._tensor_placement_policy.evict_tensors(hold_cuda_tensor_list,
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/tensor_placement_policy.py", line 34, in evict_tensors
    colo_model_data_tensor_move_inline(t, self.device)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/tensor_utils.py", line 86, in colo_model_data_tensor_move_inline
    t.move_to(target_device)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/stateful_tensor.py", line 94, in move_to
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/sharded_model/sharded_model_v2.py", line 235, in forward
    self.payload.data = self.payload.data.to(to_device)
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
    outputs = self.module(*args, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/titans/model/gpt/gpt.py", line 105, in forward
    x = self.embed(input_ids)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/titans/layer/embedding/gpt_embedding.py", line 39, in forward
    x = self.word_embeddings(input_ids) + self.position_embeddings(position_ids)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1109, in _call_impl
    result = hook(self, input)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/ophooks/utils.py", line 113, in _pre_forward_module_hook
    hook.pre_fwd_exec(submodule, *args)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/utils/zero_hook.py", line 73, in pre_fwd_exec
    self.adjust_module_data(module)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/zero/utils/zero_hook.py", line 66, in adjust_module_data
    self._stateful_tensor_mgr.adjust_layout()
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/stateful_tensor_mgr.py", line 61, in adjust_layout
    vol, evict_time = self._tensor_placement_policy.evict_tensors(hold_cuda_tensor_list,
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/tensor_placement_policy.py", line 34, in evict_tensors
    colo_model_data_tensor_move_inline(t, self.device)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/tensor_utils.py", line 86, in colo_model_data_tensor_move_inline
    t.move_to(target_device)
  File "/home/jovyan/miniconda3/envs/colossalai-test/lib/python3.8/site-packages/colossalai/gemini/stateful_tensor.py", line 94, in move_to
    self.payload.data = self.payload.data.to(to_device)
RuntimeError: CUDA error: device-side assert triggered

提供的demo中zero3有具体说明解释吗，zero2\zero1的使用配置有参考脚本吗

**Comment by Tron1994** [comment]
问题定位：Assertion ‘srcIndex ＜ srcSelectDimSize‘ failed
原因：采用了yuan语料vocab.txt，和gpt默认vocab_size有出入，需要手动修改，可在配置gpt_zero3.py中修改：
model = dict(
    type=gpt2_small,
    vocab_size=53227,
    checkpoint=True,
)


希望修复

**Comment by binmakeswell** [comment]
We have updated a lot. Please use try the new example 
https://github.com/hpcaitech/ColossalAI/tree/main/examples/language
https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat
This issue was closed due to inactivity. Thanks.
