### ISSUE TITLE
[BUG]: Dreambooth startup fails with "CUDA error: invalid device ordinal"

### ISSUE THREAD

**Issue by brucethemoose** [hpcaitech/ColossalAI#2439]
### 🐛 Describe the bug

As the title says, the dreambooth script fails to start with the following error: 

```❯ ./colossalai.sh
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/alpha/tempclone/ColossalAI/examples/images/dreambooth/train_dreambooth_colossalai.py", line 677, in <module>
    main(args)
  File "/home/alpha/tempclone/ColossalAI/examples/images/dreambooth/train_dreambooth_colossalai.py", line 358, in main
    colossalai.launch_from_torch(config={})
  File "/home/alpha/.local/lib/python3.10/site-packages/colossalai-0.2.0-py3.10.egg/colossalai/initialize.py", line 220, in launch_from_torch
    launch(config=config,
  File "/home/alpha/.local/lib/python3.10/site-packages/colossalai-0.2.0-py3.10.egg/colossalai/initialize.py", line 108, in launch
    gpc.set_device(local_rank)
  File "/home/alpha/.local/lib/python3.10/site-packages/colossalai-0.2.0-py3.10.egg/colossalai/context/parallel_context.py", line 519, in set_device
    torch.cuda.set_device(device_ordinal)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/cuda/__init__.py", line 335, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

[01/10/23 23:48:51] INFO     colossalai - colossalai - INFO:
                             /home/alpha/.local/lib/python3.10/site-packages/colossalai-0.2.0-py3.10.egg/
                             colossalai/context/parallel_context.py:521 set_device
                    INFO     colossalai - colossalai - INFO: process rank 0 is bound to device 0
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1626 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 1 (pid: 1627) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/home/alpha/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 779, in main
    run(args)
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 770, in run
    elastic_launch(
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/alpha/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_dreambooth_colossalai.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-01-10_23:48:52
  host      : Asus-GA401IV
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1627)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

My sh file, changing parameters doesn't seem to make a difference:
```
export MODEL_NAME="/home/alpha/Storage/AIModels/diffusers/pmerge/" 
export INSTANCE_DIR="/home/alpha/Storage/TrainingData/test/cropped/"
export CLASS_DIR="path-to-class-images"
export OUTPUT_DIR="/home/alpha/Storage/TrainingOutput/test/"

HF_DATASETS_OFFLINE=1 
TRANSFORMERS_OFFLINE=1 
DIFFUSERS_OFFLINE=1

torchrun --nproc_per_node 2 --master_port=25641 train_dreambooth_colossalai.py \
  --pretrained_model_name_or_path=$MODEL_NAME  \
  --instance_data_dir=$INSTANCE_DIR \
  --output_dir=$OUTPUT_DIR \
  --instance_prompt="lotest" \
  --resolution=512 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=1 \
  --learning_rate=3e-6 \
  --lr_scheduler="constant" \
  --lr_warmup_steps=0 \
  --max_train_steps=400 \
  --placement="auto" \
  --mixed_precision="fp16"
```

I don't really understand whats going wrong here, as I am on a laptop with a single RTX 2060? And identifying it with colossalai seems to work fine:

```
❯ python
Python 3.10.9 (main, Dec 24 2022, 22:19:02) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from colossalai.utils import get_current_device
>>> print(get_current_device())
cuda:0
```

Let me know if there are any other functions I can use to debug this. 

### Environment

CUDA 11.8,
torch==2.0.0.dev20230109+cu118
Python 3.10.9
Other SD inference scripts seem to work fine.

Laptop I am testing this on: 
```
           .-------------------------:                    alpha@Asus-GA401IV
          .+=========================.                    ------------------
         :++===++==================-       :++-           OS: CachyOS Linux x86_64
        :*++====+++++=============-        .==:           Host: ROG Zephyrus G14 GA401IV_GA401IV (1.0)
       -*+++=====+***++==========:                        Kernel: 6.1.4-1-cachyos-lto
      =*++++========------------:                         Uptime: 5 mins
     =*+++++=====-                     ...                Packages: 1195 (pacman)
   .+*+++++=-===:                    .=+++=:              Shell: fish 3.5.1
  :++++=====-==:                     -*****+              Resolution: 3840x2160 @ 60Hz
 :++========-=.                      .=+**+.              DE: KDE Plasma 5.26.5
.+==========-.                          .                 WM: KWin (Wayland)
 :+++++++====-                                .--==-.     WM Theme: Breeze
  :++==========.                             :+++++++:    Theme: Lightly (CachyOSNord) [QT], cachyos-nor]
   .-===========.                            =*****+*+    Icons: breeze-dark [QT], breeze-dark [GTK2/3/4]
    .-===========:                           .+*****+:    Font: Noto Sans (10pt) [QT], Noto Sans (10pt) ]
      -=======++++:::::::::::::::::::::::::-:  .---:      Cursor: capitaine (24px)
       :======++++====+++******************=.             Terminal: alacritty
        :=====+++==========++++++++++++++*-               Terminal Font: monospace (12pt)
         .====++==============++++++++++*-                CPU: AMD Ryzen 9 4900HS (16) @ 3 GHz
          .===+==================+++++++:                 GPU: AMD Renoir
           .-=======================+++:                  GPU: NVIDIA GeForce RTX 2060 Max-Q
             ..........................                   Memory: 3.04 GiB / 15.05 GiB (20%)
                                                          Disk (/): 114 GiB / 139 GiB (82%)
                                                          Disk (/home/alpha/Storage): 279 GiB / 344 GiB )
                                                          Disk (/run/media/alpha/External): 140 GiB / 93]
                                                          Disk (/windows): 296 GiB / 434 GiB (68%) [Remo]
                                                          Battery: 100% [Not charging]
                                                          Locale: en_US.UTF-8
```

**Comment by haofanwang** [comment]
This is because you only have one GPU, try set `nproc_per_node = 1`

**Comment by brucethemoose** [comment]
Thanks. I swear thats one of the first things I tried, but apparently not.

I have some other config errors to work through later, will probably post another issue when I get stuck.
