### ISSUE TITLE
[BUG]: AssertionError: please init model in the ColoInitContext

### ISSUE THREAD

**Issue by tungdq212** [hpcaitech/ColossalAI#2501]
### 🐛 Describe the bug

When running with ColossalAIStrategy, this error occur:
`AssertionError: please init model in the ColoInitContext`

My config:
```
trainer:
    benchmark: True
    accelerator: 'gpu'
    devices: 1
    log_gpu_memory: all
    auto_select_gpus: False
    precision: 16
    num_sanity_val_steps: 0

    strategy:
      target: strategies.ColossalAIStrategy
      params:
        use_chunk: True
        enable_distributed_storage: True
        placement_policy: cuda
        force_outputs_fp32: true
```
Full error:
```
Traceback (most recent call last):
  File "/home/tungduongquang/workspace/image-generation/main.py", line 809, in <module>
    trainer.fit(model, data)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1084, in _run
    self.strategy.setup(self)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/strategies/colossalai.py", line 367, in setup
    self.setup_precision_plugin()
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/strategies/colossalai.py", line 306, in setup_precision_plugin
    self.model = GeminiDDP(
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/colossalai/nn/parallel/gemini_parallel.py", line 51, in __init__
    chunk_manager = init_chunk_manager(model=module,
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/colossalai/gemini/chunk/utils.py", line 48, in init_chunk_manager
    config_dict, wasted_size = search_chunk_configuration(model, **kwargs_dict)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/colossalai/gemini/chunk/search_utils.py", line 99, in search_chunk_configuration
    params_dict = classify_params_by_dp_degree(param_order)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/colossalai/gemini/chunk/search_utils.py", line 55, in classify_params_by_dp_degree
    assert isinstance(param, ColoParameter), "please init model in the ColoInitContext"
AssertionError: please init model in the ColoInitContext

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tungduongquang/workspace/image-generation/main.py", line 811, in <module>
    melk()
  File "/home/tungduongquang/workspace/image-generation/main.py", line 794, in melk
    trainer.save_checkpoint(ckpt_path)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1930, in save_checkpoint
    self._checkpoint_connector.save_checkpoint(filepath, weights_only=weights_only, storage_options=storage_options)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 510, in save_checkpoint
    _checkpoint = self.dump_checkpoint(weights_only)
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 442, in dump_checkpoint
    "state_dict": self._get_lightning_module_state_dict(),
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/connectors/checkpoint_connector.py", line 524, in _get_lightning_module_state_dict
    state_dict = self.trainer.strategy.lightning_module_state_dict()
  File "/home/tungduongquang/miniconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/strategies/colossalai.py", line 426, in lightning_module_state_dict
    assert isinstance(self.model, ZeroDDP)
AssertionError
```

### Environment

```
torch                     1.12.1
lightning                 1.9.0rc0
colossalai                0.2.0+torch1.12cu11.7
```

**Comment by feifeibear** [comment]
Did you use your own code? As the error indicates you should build your model under the context of ColoInitContext.

https://colossalai.org/docs/features/zero_with_chunk#usage

**Comment by tungdq212** [comment]
@feifeibear  I clone the repo and install with `CUDA_EXT=1 pip install `, I dont think I change code. So how to fix that?
