### ISSUE TITLE
[BUG]: I can not install colossalAI

### ISSUE THREAD

**Issue by shendl1978** [hpcaitech/ColossalAI#2811]
### 🐛 Describe the bug

I build colossalAI from source code, but can not install it correctly.

Then I use 
pip install colossalai
     to install.  but I still install it uncorrectly.

 colossalai check -i
Traceback (most recent call last):
  File "/usr/local/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/usr/local/lib/python3.10/dist-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (
  File "/usr/local/lib/python3.10/dist-packages/colossalai/initialize.py", line 18, in <module>
    from colossalai.amp import AMP_TYPE, convert_to_amp
  File "/usr/local/lib/python3.10/dist-packages/colossalai/amp/__init__.py", line 9, in <module>
    from .torch_amp import convert_to_torch_amp
  File "/usr/local/lib/python3.10/dist-packages/colossalai/amp/torch_amp/__init__.py", line 9, in <module>
    from .torch_amp import TorchAMPLoss, TorchAMPModel, TorchAMPOptimizer
  File "/usr/local/lib/python3.10/dist-packages/colossalai/amp/torch_amp/torch_amp.py", line 10, in <module>
    from colossalai.nn.optimizer import ColossalaiOptimizer
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/__init__.py", line 1, in <module>
    from ._ops import *
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/_ops/__init__.py", line 1, in <module>
    from .addmm import colo_addmm
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/_ops/addmm.py", line 5, in <module>
    from ._utils import GeneralTensor, Number, convert_to_colo_tensor
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/_ops/_utils.py", line 8, in <module>
    from colossalai.nn.layer.utils import divide
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/layer/__init__.py", line 1, in <module>
    from .colossalai_layer import *
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/layer/colossalai_layer/__init__.py", line 2, in <module>
    from .dropout import Dropout
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/layer/colossalai_layer/dropout.py", line 4, in <module>
    from ..parallel_1d import *
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/layer/parallel_1d/__init__.py", line 1, in <module>
    from .layers import (Classifier1D, Dropout1D, Embedding1D, LayerNorm1D, Linear1D, Linear1D_Col, Linear1D_Row,
  File "/usr/local/lib/python3.10/dist-packages/colossalai/nn/layer/parallel_1d/layers.py", line 17, in <module>
    from colossalai.kernel import LayerNorm
  File "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/__init__.py", line 1, in <module>
    from .cuda_native import FusedScaleMaskSoftmax, LayerNorm, MultiHeadAttention
  File "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/cuda_native/__init__.py", line 1, in <module>
    from .layer_norm import MixedFusedLayerNorm as LayerNorm
  File "/usr/local/lib/python3.10/dist-packages/colossalai/kernel/cuda_native/layer_norm.py", line 12, in <module>
    from colossalai.kernel.op_builder.layernorm import LayerNormBuilder
ModuleNotFoundError: No module named 'colossalai.kernel.op_builder'

### Environment

Ubuntu22.04

**Comment by Gy-Lu** [comment]
Seems this issue https://github.com/hpcaitech/ColossalAI/issues/2771 would help you.

**Comment by NKcqx** [comment]
Same in Windows 11.
I built from source code and I've followed #2771 to not execute from root directory.

**Comment by FrankLeeeee** [comment]
> 

@NKcqx did you use WSL on windows?

**Comment by FrankLeeeee** [comment]
@shendl1978 is it possible to reproduce in docker?

**Comment by FrankLeeeee** [comment]
Several users met the same problem, but it works fine on all of our machines. If this can be reproduced in Docker, we can directly build the same environment and try to look for the bug. That would significantly speed up the process. @shendl1978 @NKcqx

**Comment by binmakeswell** [comment]
Hi @NKcqx @shendl1978 We have updated a lot. 
Please check the latest instructions
https://github.com/hpcaitech/ColossalAI#Installation
This issue was closed due to inactivity. Thanks.
