### ISSUE TITLE
[DOC]: There are a problem when I use multi-node

### ISSUE THREAD

**Issue by zte-tcb** [hpcaitech/ColossalAI#2833]
### 📚 The doc issue

used example : image/resnet/train.py in ColossalAI-Examples
when I do this on echo my two node is ok.
colossalai run --nproc_per_node 2 train.py

but when I used two node together, used command:
colossalai run --host shgpu1,shgpu2 --master_addr shgpu1 --nproc_per_node 2 train.py

raise exception as this :
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/root/.conda/envs/py39/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.1', 'console_scripts', 'torchrun')())
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 236, in launch_agent
    result = agent.run()
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 844, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 541, in _rendezvous
    workers = self._assign_worker_ranks(store, group_rank, group_world_size, spec)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/metrics/api.py", line 125, in wrapper
    result = f(*args, **kwargs)
  File "/root/.conda/envs/py39/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 611, in _assign_worker_ranks
    my_role_info = role_infos[group_rank]
IndexError: list index out of range
Error: failed to run torchrun --nproc_per_node=2 --nnodes=2 --node_rank=1 --rdzv_backend=c10d --rdzv_endpoint=shgpu1:29500 --rdzv_id=colossalai-default-job train.py on shgpu2, is localhost: False, exception: Encountered a bad command exit code!

Are there any errors when I use multiple nodes？

**Comment by FrankLeeeee** [comment]
Hi, I have never encountered this issue. `colossalai run` is a wrapper for `torchrun` such that we can launch multi-node training with on one node. You can try to see if `torchrun` works on your machine. If using `torchrun`, you need to excute the `torchrun` command on both your of nodes.

**Comment by zte-tcb** [comment]
> Hi, I have never encountered this issue. `colossalai run` is a wrapper for `torchrun` such that we can launch multi-node training with on one node. You can try to see if `torchrun` works on your machine. If using `torchrun`, you need to excute the `torchrun` command on both your of nodes.

Is there any example for run on multiple nodes used colossalai run ?

**Comment by zte-tcb** [comment]
> Hi, I have never encountered this issue. `colossalai run` is a wrapper for `torchrun` such that we can launch multi-node training with on one node. You can try to see if `torchrun` works on your machine. If using `torchrun`, you need to excute the `torchrun` command on both your of nodes.

And what's your torch version?  i'm py39 and torch==1.12.1

**Comment by binmakeswell** [comment]
Hi @zte-tcb you can check the detailed requirements.
https://github.com/hpcaitech/ColossalAI#Installation
For multiple nodes used colossalai run, maybe you can refer to #2768 
This issue was closed due to inactivity. Thanks.
