### ISSUE TITLE
[BUG]: Error during training a reward model with lora_rank=16

### ISSUE THREAD

**Issue by haozhestat** [hpcaitech/ColossalAI#2834]
### 🐛 Describe the bug

I run into a runtime error when running `train_rm.sh` under `applications/ChatGPT`. The model is downloaded from Huggingface `bigscience/bloom-560m`. lora_rank is `16`. Is there any hints on this?

The command is 
```
torchrun --standalone --nproc_per_node=2 examples/train_reward_model.py --pretrain 'models/bloom-560m' --strategy colossalai_zero2  --lora_rank 16
```
The main error message is 
```
Traceback (most recent call last):
  File "examples/train_reward_model.py", line 78, in <module>
    train(args)
  File "examples/train_reward_model.py", line 58, in train
    trainer.fit(use_lora=args.lora_rank)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/rm.py", line 70, in fit
    self.strategy.optimizer_step(self.optimizer)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/strategies/colossalai.py", line 134, in optimizer_step
    optimizer.step()
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/zero/sharded_optim/low_level_optim.py", line 466, in step
    assert param_shape == flat_fp32_avg_grads.shape, \
AssertionError: fp32 param and grad have different shape torch.Size([279245825]) vs torch.Size([1025])
Traceback (most recent call last):
  File "examples/train_reward_model.py", line 78, in <module>
    train(args)
  File "examples/train_reward_model.py", line 58, in train
    trainer.fit(use_lora=args.lora_rank)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/rm.py", line 70, in fit
    self.strategy.optimizer_step(self.optimizer)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/strategies/colossalai.py", line 134, in optimizer_step
    optimizer.step()
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/zero/sharded_optim/low_level_optim.py", line 460, in step
    flat_fp16_avg_grads = flatten(fp16_avg_grads)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/zero/sharded_optim/_utils.py", line 14, in flatten
    return _flatten_dense_tensors(input_)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/_utils.py", line 265, in _flatten_dense_tensors
    return torch._C._nn.flatten_dense_tensors(tensors)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].
```

The full log is  
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
  warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
  warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
[02/20/23 17:00:18] INFO     colossalai - colossalai - INFO: /home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/context/parallel_context.py:521 set_device         
                    INFO     colossalai - colossalai - INFO: process rank 1 is bound to device 1                                                                                                 
[02/20/23 17:00:18] INFO     colossalai - colossalai - INFO: /home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/context/parallel_context.py:521 set_device         
                    INFO     colossalai - colossalai - INFO: process rank 0 is bound to device 0                                                                                                 
[02/20/23 17:00:22] INFO     colossalai - colossalai - INFO: /home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/context/parallel_context.py:557 set_seed           
                    INFO     colossalai - colossalai - INFO: initialized seed on rank 0, numpy: 42, python random: 42, ParallelMode.DATA: 42, ParallelMode.TENSOR: 42,the default parallel seed  
                             is ParallelMode.DATA.                                                                                                                                               
                    INFO     colossalai - colossalai - INFO: /home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/initialize.py:116 launch                           
[02/20/23 17:00:22] INFO     colossalai - colossalai - INFO: /home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/context/parallel_context.py:557 set_seed           
                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized, data parallel size: 2, pipeline parallel size: 1, tensor parallel size: 1                   
                    INFO     colossalai - colossalai - INFO: initialized seed on rank 1, numpy: 42, python random: 42, ParallelMode.DATA: 42, ParallelMode.TENSOR: 42,the default parallel seed  
                             is ParallelMode.DATA.                                                                                                                                               
=========================================================================================
No pre-built kernel is found, build and load the cpu_adam kernel during runtime now
=========================================================================================
/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/utils/cpp_extension.py:295: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Emitting ninja build file /home/zxx/.cache/colossalai/torch_extensions/torch1.10_cu11.1/build.ninja...
Building extension module cpu_adam...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module cpu_adam...
/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/utils/cpp_extension.py:295: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Detected CUDA files, patching ldflags
Emitting ninja build file /home/zxx/.cache/colossalai/torch_extensions/torch1.10_cu11.1/build.ninja...
Building extension module fused_optim...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_optim...
Loading extension module cpu_adam...
Time to load cpu_adam op: 1.2210237979888916 seconds
=========================================================================================
No pre-built kernel is found, build and load the fused_optim kernel during runtime now
=========================================================================================
Using custom data configuration Dahoas--rm-static-4d703c93423b052a
Found cached dataset parquet (/home/zxx/.cache/huggingface/datasets/parquet/Dahoas--rm-static-4d703c93423b052a/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 359.27it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 508.09it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 375.87it/s]
/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/utils/cpp_extension.py:295: UserWarning: 

                               !! WARNING !!

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Your compiler (c++) is not compatible with the compiler Pytorch was
built with for this platform, which is g++ on linux. Please
use g++ to to compile your extension. Alternatively, you may
compile PyTorch from source using c++, and then you can also use
c++ to compile your extension.

See https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md for help
with compiling PyTorch from source.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

                              !! WARNING !!

  warnings.warn(WRONG_COMPILER_WARNING.format(
Detected CUDA files, patching ldflags
Emitting ninja build file /home/zxx/.cache/colossalai/torch_extensions/torch1.10_cu11.1/build.ninja...
Building extension module fused_optim...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module fused_optim...
Time to load fused_optim op: 0.5216825008392334 seconds
Using custom data configuration Dahoas--rm-static-4d703c93423b052a
Found cached dataset parquet (/home/zxx/.cache/huggingface/datasets/parquet/Dahoas--rm-static-4d703c93423b052a/0.0.0/2a3b91fbd88a2c90d1dbbb32b460cf621d31bd5b05b934492fdef7d8d6f236ec)
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 240.42it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 414.97it/s]
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 363.56it/s]
Using Lora
Train epoch:   0%|                                                                                                                                                         | 0/2 [00:00<?, ?it/sUsing Lorap of epoch 0:   0%|                                                                                                                                             | 0/100 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "examples/train_reward_model.py", line 78, in <module>
    train(args)
  File "examples/train_reward_model.py", line 58, in train
    trainer.fit(use_lora=args.lora_rank)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/rm.py", line 70, in fit
    self.strategy.optimizer_step(self.optimizer)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/strategies/colossalai.py", line 134, in optimizer_step
    optimizer.step()
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/zero/sharded_optim/low_level_optim.py", line 466, in step
    assert param_shape == flat_fp32_avg_grads.shape, \
AssertionError: fp32 param and grad have different shape torch.Size([279245825]) vs torch.Size([1025])
Traceback (most recent call last):
  File "examples/train_reward_model.py", line 78, in <module>
    train(args)
  File "examples/train_reward_model.py", line 58, in train
    trainer.fit(use_lora=args.lora_rank)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/rm.py", line 70, in fit
    self.strategy.optimizer_step(self.optimizer)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/chatgpt/trainer/strategies/colossalai.py", line 134, in optimizer_step
    optimizer.step()
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/zero/sharded_optim/low_level_optim.py", line 460, in step
    flat_fp16_avg_grads = flatten(fp16_avg_grads)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/colossalai/zero/sharded_optim/_utils.py", line 14, in flatten
    return _flatten_dense_tensors(input_)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/_utils.py", line 265, in _flatten_dense_tensors
    return torch._C._nn.flatten_dense_tensors(tensors)
NotImplementedError: There were no tensor arguments to this function (e.g., you passed an empty list of Tensors), but no fallback function is registered for schema aten::_cat.  This usually means that this function requires a non-empty list of Tensors, or that you (the operator writer) forgot to register a fallback function.  Available functions are [CPU, CUDA, QuantizedCPU, BackendSelect, Python, Named, Conjugate, Negative, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradXLA, AutogradLazy, AutogradXPU, AutogradMLC, AutogradHPU, AutogradNestedTensor, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, Tracer, UNKNOWN_TENSOR_TYPE_ID, Autocast, Batched, VmapMode].

CPU: registered at aten/src/ATen/RegisterCPU.cpp:18433 [kernel]
CUDA: registered at aten/src/ATen/RegisterCUDA.cpp:26496 [kernel]
QuantizedCPU: registered at aten/src/ATen/RegisterQuantizedCPU.cpp:1068 [kernel]
BackendSelect: fallthrough registered at ../aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
Python: registered at ../aten/src/ATen/core/PythonFallbackKernel.cpp:47 [backend fallback]
Named: registered at ../aten/src/ATen/core/NamedRegistrations.cpp:7 [backend fallback]
Conjugate: registered at ../aten/src/ATen/ConjugateFallback.cpp:18 [backend fallback]
Negative: registered at ../aten/src/ATen/native/NegateFallback.cpp:18 [backend fallback]
ADInplaceOrView: fallthrough registered at ../aten/src/ATen/core/VariableFallbackKernel.cpp:64 [backend fallback]
AutogradOther: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradCPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradCUDA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradXLA: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradLazy: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradXPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradMLC: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradHPU: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradNestedTensor: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradPrivateUse1: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradPrivateUse2: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
AutogradPrivateUse3: registered at ../torch/csrc/autograd/generated/VariableType_3.cpp:10141 [autograd kernel]
Tracer: registered at ../torch/csrc/autograd/generated/TraceType_3.cpp:11560 [kernel]
UNKNOWN_TENSOR_TYPE_ID: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:466 [backend fallback]
Autocast: fallthrough registered at ../aten/src/ATen/autocast_mode.cpp:305 [backend fallback]
Batched: registered at ../aten/src/ATen/BatchingRegistrations.cpp:1016 [backend fallback]
VmapMode: fallthrough registered at ../aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]

Train epoch:   0%|                                                                                                                                                         | 0/2 [00:00<?, ?it/s]
Train step of epoch 0:   0%|                                                                                                                                             | 0/100 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 53732) of binary: /home/zxx/.conda/envs/colossal-ai/bin/python
Traceback (most recent call last):
  File "/home/zxx/.conda/envs/colossal-ai/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/distributed/run.py", line 710, in run
    elastic_launch(
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/zxx/.conda/envs/colossal-ai/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/train_reward_model.py FAILED
------------------------------------------------------------
```

### Environment

CUDA Version: 11.1
transformers Version: 4.26.1
torch Version: 1.10.1+cu111
loralib Version: 0.1.1
colossalai Version: 0.2.5

**Comment by ht-zhou** [comment]
Thanks for your feedback, it's actually a bug here.
And we'll fix it soon.

**Comment by Taurids** [comment]
How long did this take to load
"======================================================
No pre-built kernel is found, build and load the cpu_adam kernel during runtime now
======================================================="

**Comment by ht-zhou** [comment]
Thanks for your feedback and this bug has been fixed.
Feel free to reopen the issue if having any problems.
