### ISSUE TITLE
[BUG]: colossalai check -i error

### ISSUE THREAD

**Issue by Alternate-D** [hpcaitech/ColossalAI#2845]
### 🐛 Describe the bug

I installed colossalai0.2.5 successfully(from source not pypi), but the following problem occurred when I executed command "colossalai check -i", please help me.
(Colossal-AI) ln01@ln01-System-Product-Name:/media/ln01/2t/usr/wy$ colossalai check -i
Traceback (most recent call last):
  File "/home/ln01/anaconda3/envs/Colossal-AI/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/initialize.py", line 18, in <module>
    from colossalai.amp import AMP_TYPE, convert_to_amp
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/amp/__init__.py", line 9, in <module>
    from .torch_amp import convert_to_torch_amp
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/amp/torch_amp/__init__.py", line 9, in <module>
    from .torch_amp import TorchAMPLoss, TorchAMPModel, TorchAMPOptimizer
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/amp/torch_amp/torch_amp.py", line 10, in <module>
    from colossalai.nn.optimizer import ColossalaiOptimizer
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/__init__.py", line 1, in <module>
    from ._ops import *
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/_ops/__init__.py", line 1, in <module>
    from .addmm import colo_addmm
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/_ops/addmm.py", line 5, in <module>
    from ._utils import GeneralTensor, Number, convert_to_colo_tensor
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/_ops/_utils.py", line 8, in <module>
    from colossalai.nn.layer.utils import divide
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/layer/__init__.py", line 1, in <module>
    from .colossalai_layer import *
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/layer/colossalai_layer/__init__.py", line 2, in <module>
    from .dropout import Dropout
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/layer/colossalai_layer/dropout.py", line 4, in <module>
    from ..parallel_1d import *
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/layer/parallel_1d/__init__.py", line 1, in <module>
    from .layers import (Classifier1D, Dropout1D, Embedding1D, LayerNorm1D, Linear1D, Linear1D_Col, Linear1D_Row,
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/nn/layer/parallel_1d/layers.py", line 17, in <module>
    from colossalai.kernel import LayerNorm
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/kernel/__init__.py", line 1, in <module>
    from .cuda_native import FusedScaleMaskSoftmax, LayerNorm, MultiHeadAttention
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/kernel/cuda_native/__init__.py", line 1, in <module>
    from .layer_norm import MixedFusedLayerNorm as LayerNorm
  File "/home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/kernel/cuda_native/layer_norm.py", line 12, in <module>
    from colossalai.kernel.op_builder.layernorm import LayerNormBuilder
ModuleNotFoundError: No module named 'colossalai.kernel.op_builder'

### Environment

Python3.7+CUDA11.7+torch1.13.1

**Comment by FrankLeeeee** [comment]
Hi, we have encountered several user feedback on this, one related issue is #2811

**Comment by Wangyu926498** [comment]
> I am looking into this issue, however, I cannot reproduce this bug on my machine. Is it possible for you to provide a dockerfile script to reproduce this in Docker? I would be more than happy to help if needed.

Sorry, I'm not familiar with the usage of Docker.

**Comment by FrankLeeeee** [comment]
That's absolutely alright. If you could provide the output of the following bash commands, perhaps it can help me better locate the bug.

```bash
ls /home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/kernel
ls /home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/
```

**Comment by Wangyu926498** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Frank ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hpcaitech/ColossalAI] [BUG]: colossalai check -i error (Issue #2845)





 
That's absolutely alright. If you could provide the output of the following bash commands, perhaps it can help me better locate the bug.
 ls /home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/kernel ls /home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/

**Comment by FrankLeeeee** [comment]
@Alternate-D can I know whether you are running on windows?

**Comment by Alternate-D** [comment]
> @Alternate-D can I know whether you are running on windows?

Linux, Ubuntu22.04

**Comment by bingo00** [comment]
> That's absolutely alright. If you could provide the output of the following bash commands, perhaps it can help me better locate the bug.
> 
> ```shell
> ls /home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/colossalai/kernel
> ls /home/ln01/anaconda3/envs/Colossal-AI/lib/python3.7/site-packages/
> ```

I have solve this promblem by adding a link
```
site-packages/colossalai/kernel$ ln -s ../../op_builder op_builder
```
then the check command works
```
$ colossalai check -i
#### Installation Report ####

------------ Environment ------------
Colossal-AI version: 0.2.5
PyTorch version: 1.12.0
System CUDA version: 10.2
CUDA version required by PyTorch: 10.2
```
seems like the reason for this error, but the origin reason is in the installing process.
My env is 
```
$ conda --version
conda 4.9.2
$ python -V
Python 3.9.12
```
project version is
```
$ git log
commit cd2b0eaa8dd4a7d8a67ce91b93459e07418bd741 (origin/main, origin/HEAD)
Author: YuliangLiu0306 <72588413+YuliangLiu0306@users.noreply.github.com>
Date:   Tue Mar 7 11:08:11 2023 +0800

    [DTensor] refactor sharding spec (#2987)
    
    * [autoparallel] refactor sharding spec
    
    * rename function name
```

**Comment by binmakeswell** [comment]
Glad to hear it was resolved. Thanks.
