### ISSUE TITLE
[BUG]: When using `diffusers` modules, encounters `RuntimeError: Input type (float) and bias type (c10::Half) should be the same`

### ISSUE THREAD

**Issue by hpretila** [hpcaitech/ColossalAI#2909]
### 🐛 Describe the bug

Hi, I'm currently working on integrating Diffusers modules into one of my projects. It seems that I encounter the `RuntimeError: Input type (float) and bias type (c10::Half) should be the same` when I attempt to invoke a `Unet2DConditionModel`. Potentially related to #1976. Found in #2857.

```py
import pytorch_lightning as pl
from diffusers import UNet2DConditionModel

class LLMDiffusion(pl.LightningModule):
    def __init__(self, unet_config):
        self.unet_config = unet_config

    def configure_sharded_model(self) -> None:
        # Configure the module
        self.unet = UNet2DConditionModel(**self.unet_config)

    def forward(self, ins, t, q):
        return self.unet(ins, t, encoder_hidden_states=q).sample
```

The trace is as following.

<details>
    <summary>Logs</summary>

```py
Traceback (most recent call last):
  File "/mnt/e/Source/language-diff/train.py", line 81, in <module>
    train_denoiser()
  File "/mnt/e/Source/language-diff/train.py", line 76, in train_denoiser
    denoiser_trainer.fit(diffusion_model, train_loader, val_loader)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1214, in _run_train
    self.fit_loop.run()
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 249, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 370, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1356, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/core/module.py", line 1742, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/strategies/colossalai.py", line 383, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/plugins/precision/colossalai.py", line 73, in optimizer_step
    closure_result = closure()
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 149, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 135, in closure
    step_output = self._step_fn()
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/loops/optimization/optimizer_loop.py", line 419, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/strategies/ddp.py", line 351, in training_step
    return self.model(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/colossalai/nn/parallel/data_parallel.py", line 282, in forward
    outputs = self.module(*args, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/pytorch_lightning/overrides/base.py", line 98, in forward
    output = self._forward_module.training_step(*inputs, **kwargs)
  File "/mnt/e/Source/language-diff/model/diffusion.py", line 223, in training_step
    img_hat = self.forward_with_text_q(q)
  File "/mnt/e/Source/language-diff/model/diffusion.py", line 210, in forward_with_text_q
    noise_pred = self.unet(latent_ins, t, encoder_hidden_states=prompt_embeds).sample
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/diffusers/models/unet_2d_condition.py", line 574, in forward
    sample = self.conv_in(sample)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 463, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/colossalai/tensor/colo_parameter.py", line 87, in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.10/site-packages/colossalai/tensor/colo_tensor.py", line 184, in __torch_function__
    ret = func(*args, **kwargs)
RuntimeError: Input type (float) and bias type (c10::Half) should be the same
```

</details>

### Environment

<details>
  <summary>Current environment</summary>

```
* CUDA:
        - GPU:
                - NVIDIA GeForce RTX 3090
        - available:         True
        - version:           11.7
* Lightning:
        - lightning-utilities: 0.6.0.post0
        - open-clip-torch:   2.14.0
        - pytorch-lightning: 1.9.2
        - torch:             1.13.1
        - torchaudio:        0.13.1
        - torchmetrics:      0.11.1
        - torchvision:       0.14.1
* Packages:
        - absl-py:           1.4.0
        - aiohttp:           3.8.4
        - aiosignal:         1.3.1
        - async-timeout:     4.0.2
        - attrs:             22.2.0
        - bcrypt:            4.0.1
        - cachetools:        5.3.0
        - certifi:           2022.12.7
        - cffi:              1.15.1
        - cfgv:              3.3.1
        - charset-normalizer: 3.0.1
        - click:             8.1.3
        - cmake:             3.25.2
        - colossalai:        0.2.5
        - contexttimer:      0.3.3
        - contourpy:         1.0.7
        - cryptography:      39.0.1
        - cycler:            0.11.0
        - diffusers:         0.13.1
        - distlib:           0.3.6
        - fabric:            3.0.0
        - filelock:          3.9.0
        - fonttools:         4.38.0
        - frozenlist:        1.3.3
        - fsspec:            2023.1.0
        - ftfy:              6.1.1
        - huggingface-hub:   0.12.1
        - identify:          2.5.18
        - idna:              3.4
        - importlib-metadata: 6.0.0
        - invoke:            2.0.0
        - kiwisolver:        1.4.4
        - lightning-utilities: 0.6.0.post0
        - lit:               15.0.7
        - markdown:          3.4.1
        - markdown-it-py:    2.1.0
        - markupsafe:        2.1.2
        - matplotlib:        3.7.0
        - mdurl:             0.1.2
        - multidict:         6.0.4
        - mypy-extensions:   1.0.0
        - ninja:             1.11.1
        - nodeenv:           1.7.0
        - numpy:             1.24.2
        - nvidia-cublas-cu11: 11.10.3.66
        - nvidia-cuda-nvrtc-cu11: 11.7.99
        - nvidia-cuda-runtime-cu11: 11.7.99
        - nvidia-cudnn-cu11: 8.5.0.96
        - oauthlib:          3.2.2
        - open-clip-torch:   2.14.0
        - packaging:         23.0
        - paramiko:          3.0.0
        - pillow:            9.4.0
        - pip:               22.3.1
        - platformdirs:      3.0.0
        - pre-commit:        3.0.4
        - protobuf:          3.20.3
        - psutil:            5.9.4
        - pyasn1:            0.4.8
        - pyasn1-modules:    0.2.8
        - pycparser:         2.21
        - pygments:          2.14.0
        - pynacl:            1.5.0
        - pyparsing:         3.0.9
        - pyre-extensions:   0.0.23
        - python-dateutil:   2.8.2
        - pytorch-lightning: 1.9.2
        - pyyaml:            6.0
        - regex:             2022.10.31
        - requests:          2.28.2
        - requests-oauthlib: 1.3.1
        - rich:              13.3.1
        - rsa:               4.9
        - sentencepiece:     0.1.97
        - setuptools:        65.6.3
        - six:               1.16.0
        - tensorboard:       2.12.0
        - tensorboard-data-server: 0.7.0
        - tensorboard-plugin-wit: 1.8.1
        - timm:              0.6.12
        - tokenizers:        0.13.2
        - torch:             1.13.1
        - torchaudio:        0.13.1
        - torchmetrics:      0.11.1
        - torchvision:       0.14.1
        - tqdm:              4.64.1
        - transformers:      4.26.1
        - triton:            2.0.0a2
        - typing-extensions: 4.5.0
        - typing-inspect:    0.8.0
        - urllib3:           1.26.14
        - virtualenv:        20.19.0
        - wcwidth:           0.2.6
        - werkzeug:          2.2.3
        - wheel:             0.38.4
        - xformers:          0.0.16
        - yarl:              1.8.2
        - zipp:              3.14.0
* System:
        - OS:                Linux
        - architecture:
                - 64bit
                - ELF
        - processor:         x86_64
        - python:            3.10.9
```

</details>

**Comment by Fazziekey** [comment]
you should make your input tensor to half, because the colossal genimi launch with half precise, like
```
input = input.half()
```

**Comment by Fazziekey** [comment]
like 
![image](https://user-images.githubusercontent.com/55798671/221805544-9679e7ea-2490-411e-93d2-82cdca2cf2d4.png)

**Comment by Fazziekey** [comment]
https://github.com/hpcaitech/ColossalAI/blob/dca98937f834f5af2730f481bf6f5e5eee844742/examples/images/diffusion/ldm/models/diffusion/ddpm.py#L448

**Comment by hpretila** [comment]
Thank you, @Fazziekey! Got further with my model as a result :D
