### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by Kingzsf** [hpcaitech/ColossalAI#3000]
### 🐛 Describe the bug

[zhousf@fedora ~]$ colossalai check -i
Traceback (most recent call last):
  File "/home/zhousf/.local/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/initialize.py", line 18, in <module>
    from colossalai.amp import AMP_TYPE, convert_to_amp
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/amp/__init__.py", line 5, in <module>
    from colossalai.context import Config
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/context/__init__.py", line 4, in <module>
    from .moe_context import MOE_CONTEXT
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/context/moe_context.py", line 8, in <module>
    from colossalai.tensor import ProcessGroup
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/tensor/__init__.py", line 2, in <module>
    from .colo_parameter import ColoParameter
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/tensor/colo_parameter.py", line 5, in <module>
    from colossalai.tensor.colo_tensor import ColoTensor
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/tensor/colo_tensor.py", line 11, in <module>
    from colossalai.tensor.tensor_spec import ColoTensorSpec
  File "/home/zhousf/.local/lib/python3.11/site-packages/colossalai/tensor/tensor_spec.py", line 10, in <module>
    @dataclass
     ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1220, in dataclass
    return wrap(cls)
           ^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 1210, in wrap
    return _process_class(cls, init, repr, eq, order, unsafe_hash,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 958, in _process_class
    cls_fields.append(_get_field(cls, name, type, kw_only))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/dataclasses.py", line 815, in _get_field
    raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'colossalai.tensor.distspec._DistSpec'> for field dist_attr is not allowed: use default_factory

### Environment

Python 3.11.2 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] on linux
System:
  Kernel: 6.1.14-200.fc37.x86_64 arch: x86_64 bits: 64 compiler: gcc
    v: 2.38-25.fc37 Console: pty pts/0 Distro: Fedora release 37 (Thirty Seven)
CPU:
  Info: 2x 4-core model: Intel Core i7-10700K bits: 64 type: MCP SMP
    arch: Comet Lake rev: 5 cache: L1: 2x 256 KiB (512 KiB)
    L2: 2x 1024 KiB (2 MiB) L3: 2x 16 MiB (32 MiB)
  Speed (MHz): avg: 3792 min/max: N/A cores: 1: 3792 2: 3792 3: 3792 4: 3792
    5: 3792 6: 3792 7: 3792 8: 3792 bogomips: 60672
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3
Graphics:
  Device-1: VMware SVGA II Adapter driver: vmwgfx v: 2.20.0.0 bus-ID: 00:0f.0
  Display: server: X.Org v: 22.1.8 with: Xwayland v: 22.1.8 driver:
    dri: vmwgfx gpu: vmwgfx note: X driver n/a resolution: 2560x1440~60Hz
  API: OpenGL v: 4.3 Mesa 22.3.6 renderer: SVGA3D; build: RELEASE; LLVM;
    direct-render: Yes

**Comment by MountainGG** [comment]
Any solutions？

**Comment by MountainGG** [comment]
Any solution？
