### ISSUE TITLE
[BUG]:pip install colossalai报错，代码如下

### ISSUE THREAD

**Issue by lee-tai** [hpcaitech/ColossalAI#3110]
### 🐛 Describe the bug

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting colossalai
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/25/7c/99446b8f26ba3a8706553868aa230dd9e9e153f024961967c6d916ddc943/colossalai-0.2.7.tar.gz (686 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [7 lines of output]
      No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\33465\AppData\Local\Temp\pip-install-2jzqc5_e\colossalai_f1433698a88d46a3abc96ade6259cb7d\setup.py", line 37, in <module>
          raise RuntimeError("Windows is not supported yet. Please try again within the Windows Subsystem for Linux (WSL).")
      RuntimeError: Windows is not supported yet. Please try again within the Windows Subsystem for Linux (WSL).
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by leo9960** [comment]
还不支持Windows，要用Linux或者WSL2

**Comment by binmakeswell** [comment]
Hi @lee-tai Please check [Requirements](https://github.com/hpcaitech/ColossalAI#Installation) This issue was closed due to inactivity. Thanks.
