### ISSUE TITLE
[BUG]: gpt2 pipline error

### ISSUE THREAD

**Issue by Xu-Kai** [hpcaitech/ColossalAI#3164]
### 🐛 Describe the bug

I use examples to run gpt2 with pipeline mode.
The command is in examples/language/gpt/experiments/pipeline_parallel/run.sh.
The error is 
Traceback (most recent call last):
  File "/home/guest_01/ColossalAI/colossalai/fx/tracer/tracer.py", line 295, in _meta_data_computing
    attr_itr = getattr(attr_itr, atom)
  File "/home/guest_01/anaconda3/envs/bloom/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 705, in module_getattr_wrapper
    return self.getattr(attr, attr_val, parameter_proxy_cache)
  File "/home/guest_01/anaconda3/envs/bloom/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 484, in getattr
    maybe_parameter_proxy = maybe_get_proxy_for_attr(
  File "/home/guest_01/anaconda3/envs/bloom/lib/python3.9/site-packages/torch/fx/_symbolic_trace.py", line 478, in maybe_get_proxy_for_attr
    val_proxy = self.create_proxy("get_attr", n, (), {}, **kwargs)  # type: ignore[arg-type]
  File "/home/guest_01/ColossalAI/colossalai/fx/tracer/tracer.py", line 142, in create_proxy
    meta_out = self._meta_data_computing(
  File "/home/guest_01/ColossalAI/colossalai/fx/tracer/tracer.py", line 308, in _meta_data_computing
    raise RuntimeError(f"Could not compute metadata for {kind} target {target}: {e}")

### Environment

CUDA 11.6 + Pytorch 1.13 + colossalai 0.2.7

**Comment by Wesley-Jzy** [comment]
May you tell me the version of transformers?
