### ISSUE TITLE
[BUG]This happened after I ran Colossal after building the environment according to the instructions

### ISSUE THREAD

**Issue by dong49** [hpcaitech/ColossalAI#3175]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "/root/anaconda3/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/initialize.py", line 18, in <module>
    from colossalai.amp import AMP_TYPE, convert_to_amp
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/amp/__init__.py", line 9, in <module>
    from .torch_amp import convert_to_torch_amp
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/amp/torch_amp/__init__.py", line 9, in <module>
    from .torch_amp import TorchAMPLoss, TorchAMPModel, TorchAMPOptimizer
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/amp/torch_amp/torch_amp.py", line 10, in <module>
    from colossalai.nn.optimizer import ColossalaiOptimizer
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/nn/__init__.py", line 1, in <module>
    from ._ops import *
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/nn/_ops/__init__.py", line 1, in <module>
    from .addmm import colo_addmm
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/nn/_ops/addmm.py", line 5, in <module>
    from ._utils import GeneralTensor, Number, convert_to_colo_tensor
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/nn/_ops/_utils.py", line 8, in <module>
    from colossalai.nn.layer.utils import divide
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/nn/layer/__init__.py", line 7, in <module>
    from .moe import *
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/nn/layer/moe/__init__.py", line 1, in <module>
    from .experts import Experts, FFNExperts, TPExperts
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/nn/layer/moe/experts.py", line 8, in <module>
    from colossalai.zero.init_ctx import no_shard_zero_decrator
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/zero/__init__.py", line 7, in <module>
    from colossalai.zero.sharded_model.sharded_model_v2 import ShardedModelV2
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/zero/sharded_model/__init__.py", line 1, in <module>
    from .sharded_model_v2 import ShardedModelV2
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/zero/sharded_model/sharded_model_v2.py", line 16, in <module>
    from colossalai.gemini.memory_tracer import MemStatsCollector, StaticMemStatsCollector
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/gemini/__init__.py", line 1, in <module>
    from .chunk import ChunkManager, TensorInfo, TensorState, search_chunk_configuration
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/gemini/chunk/__init__.py", line 3, in <module>
    from .search_utils import classify_params_by_dp_degree, search_chunk_configuration
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/gemini/chunk/search_utils.py", line 8, in <module>
    from colossalai.gemini.memory_tracer import MemStats, OrderedParamGenerator
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/gemini/memory_tracer/__init__.py", line 6, in <module>
    from .static_memstats_collector import StaticMemStatsCollector    # isort:skip
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/gemini/memory_tracer/static_memstats_collector.py", line 7, in <module>
    from colossalai.fx.passes.meta_info_prop import MetaInfoProp
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/fx/__init__.py", line 3, in <module>
    from .passes import MetaInfoProp, metainfo_trace
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/fx/passes/__init__.py", line 2, in <module>
    from .concrete_info_prop import ConcreteInfoProp
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/fx/passes/concrete_info_prop.py", line 10, in <module>
    from colossalai.fx.profiler import GraphInfo, profile_function, profile_method, profile_module
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/fx/profiler/__init__.py", line 4, in <module>
    from .opcount import flop_mapping
  File "/root/anaconda3/lib/python3.9/site-packages/colossalai/fx/profiler/opcount.py", line 273, in <module>
    aten.upsample_nearest2d_backward.vec: elementwise_flop_counter(0, 1),
  File "/root/anaconda3/lib/python3.9/site-packages/torch/_ops.py", line 488, in __getattr__
    raise AttributeError(
AttributeError: The underlying op of 'aten.upsample_nearest2d_backward' has no overload name 'vec'

### Environment

cuda kit ：12.1 cuda ：11.7  cudnn：cudnn-local-repo-ubuntu2004-8.8.0.121_1.0-1_amd64 Python 3.9 pytorch：pytorch.org/whl/cu117

**Comment by binmakeswell** [comment]
Hi @dong49 Which step did you execute according to the instructions from where? Could you please provide detailed reproduction steps? Thanks.

**Comment by Shikamaru5** [comment]
I'm also seeing this issue, I've got the latest version of PyTorch and Cuda, and Cudnn, and all ChatGPT could tell me was it was likely one of those but when testing they do seem to be working. Going through those scripts, I mean it does seem correct that I can't find a method for the vec overload but I'm not sure why? For me at least it pops up when I start trying to train. literally I type python3 train.py and that is what shows up, except the only difference for me is that it starts at import colossalai. I've also tried uninstalling and reinstalling colossalai, and doing it from the github source, including grabbing the requirements. I've tried uninstalling and reinstalling different versions of PyTorch, but that hasn't changed the issue.

**Comment by super-dainiu** [comment]
I think something happens here.

https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/gemini/memory_tracer/static_memstats_collector.py

What is the usage of MetaInfoProp in this file? Can remove that if the problem cannot be solved. 

cc @YuliangLiu0306 @DAC-HAO

**Comment by super-dainiu** [comment]
Also the flop count should be in a import-friendly way..

**Comment by Shikamaru5** [comment]
After doing some major digging into it, I determined the issue is that PyTorch had a script in torch called aten which is no longer there, so I've sent an issue to the PyTorch GitHub page asking where it is, and what I should do about it, but I may have to download the version that isn't found on the get started on the PyTorch site.
