### ISSUE TITLE
[BUG]: bug in Stable-Diffusion, RuntimeError: expected scalar type Half but found Float

### ISSUE THREAD

**Issue by yuanluw** [hpcaitech/ColossalAI#3248]
### 🐛 Describe the bug

你好，我在尝试对stable diffusion模型进行微调，所以使用了https://github.com/hpcaitech/ColossalAI/tree/main/examples/images/diffusion 的代码。并且基本上按照readme文件的步骤走了下来。
1. conda env create -f environment.yaml
2. 没有使用镜像
3. 使用了sdv1.5的模型
4. 我在训练中使用了https://github.com/hpcaitech/ColossalAI/blob/main/examples/images/diffusion/configs/Teyvat/train_colossalai_teyvat.yaml 这个例子，但是直接使用会出现加载sdv1.5的模型出错的问题，所以我修改了yaml文件中unet_config的配置，其他内容都一致

```
unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 2
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: True
        legacy: False
```

修改后可以正常运行，然后就出现了expected scalar type Half but found Float这个错误，整个错误日志如下：
```
sorBoard: The `model.example_input_array` attribute is not set or `input_array` was not given.
  rank_zero_warn(
Epoch 0:   0%|                                                                                                                             | 0/8 [00:00<?, ?it/s]/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/strategies/ddp.py:437: UserWarning: Error handling mechanism for deadlock detection is uninitialized. Skipping check.
  rank_zero_warn("Error handling mechanism for deadlock detection is uninitialized. Skipping check.")
Traceback (most recent call last):
  File "/home/data/diffusion/code/ColossalAI/examples/images/diffusion/main.py", line 892, in <module>
Summoning checkpoint.
    trainer.fit(model, data)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/epoch/training_epoch_loop.py", line 213, in advance
    batch_output = self.batch_loop.run(kwargs)
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/batch/training_batch_loop.py", line 88, in advance
    outputs = self.optimizer_loop.run(optimizers, kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/optimizer_loop.py", line 202, in advance
    result = self._run_optimization(kwargs, self._optimizers[self.optim_progress.optimizer_position])
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/optimizer_loop.py", line 249, in _run_optimization
    self._optimizer_step(optimizer, opt_idx, kwargs.get("batch_idx", 0), closure)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/optimizer_loop.py", line 370, in _optimizer_step
    self.trainer._call_lightning_module_hook(
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1347, in _call_lightning_module_hook
    output = fn(*args, **kwargs)
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/core/module.py", line 1744, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/core/optimizer.py", line 169, in step
    step_output = self._strategy.optimizer_step(self._optimizer, self._optimizer_idx, closure, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/strategies/colossalai.py", line 411, in optimizer_step
    return self.precision_plugin.optimizer_step(
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/plugins/precision/colossalai.py", line 73, in optimizer_step
    closure_result = closure()
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/optimizer_loop.py", line 149, in __call__
    self._result = self.closure(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/optimizer_loop.py", line 135, in closure
    step_output = self._step_fn()
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/loops/optimization/optimizer_loop.py", line 419, in _training_step
    training_step_output = self.trainer._call_strategy_hook("training_step", *kwargs.values())
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1485, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/wuyuanlu/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/strategies/ddp.py", line 351, in training_step
    return self.model(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/colossalai/nn/parallel/data_parallel.py", line 282, in forward
    outputs = self.module(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/lightning/pytorch/overrides/base.py", line 98, in forward
    output = self._forward_module.training_step(*inputs, **kwargs)
  File "/home/data/diffusion/code/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 474, in training_step
    loss, loss_dict = self.shared_step(batch)
  File "/home/data/diffusion/code/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 925, in shared_step
    loss = self(x, c)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data/wuyuanlu/diffusion/code/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 937, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/home/data/diffusion/code/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 977, in p_losses
    model_output = self.apply_model(x_noisy, t, cond)
  File "/home/data/wuyuanlu/diffusion/code/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 949, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data/diffusion/code/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 1520, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/data/diffusion/code/ColossalAI/examples/images/diffusion/ldm/modules/diffusionmodules/openaimodel.py", line 769, in forward
    emb = self.time_embed(t_emb)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/colossalai/tensor/colo_parameter.py", line 87, in __torch_function__
    ret = super().__torch_function__(func, types, args, kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/colossalai/tensor/colo_tensor.py", line 184, in __torch_function__
    ret = func(*args, **kwargs)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/colossalai/nn/_ops/linear.py", line 171, in colo_linear
    return colo_linear_imp(input, weight, bias)
  File "/home/anaconda3/envs/ldm/lib/python3.9/site-packages/colossalai/nn/_ops/linear.py", line 78, in colo_linear_imp
    ret_tensor = ColoTensor.from_torch_tensor(F.linear(input_tensor, weight, bias), spec=ColoTensorSpec(pg))
```
不知道能否帮我看看，感谢！

### Environment

我的运行环境是在两张3090Ti上，CUDA version 为11.7
安装的库版本完全跟environment.yaml一致，只有xformer因为安装失败我没有安装

**Comment by yuanluw** [comment]
使用了镜像运行后，还是遇到了同样的问题

**Comment by JThh** [comment]
There were a few past unsolved issues (#1984, #2450) about this. Can you try setting this [line](https://github.com/hpcaitech/ColossalAI/blob/280fcdc4856e061688e3aba49c3b53427967fd7b/examples/images/diffusion/configs/Teyvat/train_colossalai_teyvat.yaml#L113) to false?

**Comment by yuanluw** [comment]
更新下，我重新测试后，发现使用stable-diffusion-v2-base的ckpt是可以正常运行，不会遇到这个错误。但是使用sdv1.5的ckpt还是有

**Comment by NatalieC323** [comment]
Thanks for your trials and updates! As for the configuration file, we have updated the structure by removing the "params" and "target" keys. Please note that you need to modify the information before you start training (For instance, the data path should be changed at least). And for the checkpoint problem, the stable diffusion v2 is recommended and performs more robustly (denoted in README).

**Comment by Youngon** [comment]
> Thanks for your trials and updates! As for the configuration file, we have updated the structure by removing the "params" and "target" keys. Please note that you need to modify the information before you start training (For instance, the data path should be changed at least). And for the checkpoint problem, the stable diffusion v2 is recommended and performs more robustly (denoted in README).

I have met the error when using stable diffusion scripts/txt2img.py ,  "KeyError: 'Expected key `target` to instantiate.", could you give me some help.
