### ISSUE TITLE
[BUG]: [chatgpt] llama model code not fit with other LMs and colossalai strategies save model bugs

### ISSUE THREAD

**Issue by pgzhang** [hpcaitech/ColossalAI#3267]
### Bug1:
llama model dataset and training code not fit with other LMs
```
Traceback (most recent call last):
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 142, in <module>
    train(args)
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 99, in train
    train_sampler = DistributedSampler(train_dataset, shuffle=True, seed=42, drop_last=True)
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/distributed.py", line 83, in __init__
    if self.drop_last and len(self.dataset) % self.num_replicas != 0:  # type: ignore[arg-type]
  File "/ColossalAI/applications/ChatGPT/chatgpt/dataset/sft_dataset.py", line 73, in __len__
    length = len(self.prompts)
AttributeError: 'SFTDataset' object has no attribute 'prompts'
```
```
Traceback (most recent call last):
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 142, in <module>
    train(args)
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 106, in train
    train_dataloader = DataLoader(train_dataset, shuffle=(train_sampler is None), sampler=train_sampler, batch_size=args.batch_size, collate_fn=data_collator)
UnboundLocalError: local variable 'data_collator' referenced before assignment
```
```
Traceback (most recent call last):
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 143, in <module>
    train(args)
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 121, in train
    trainer.fit(logger=logger, use_lora=args.lora_rank, log_interval=args.log_interval)
  File "/ColossalAI/applications/ChatGPT/chatgpt/trainer/sft.py", line 63, in fit
    for batch_id, batch in enumerate(self.train_dataloader):
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 681, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 721, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/ColossalAI/applications/ChatGPT/chatgpt/dataset/sft_dataset.py", line 78, in __getitem__
    return dict(input_ids=self.input_ids[i], labels=self.labels[i])
NameError: name 'i' is not defined
```

### Bug2:
colossalai strategies save model code bug
```
Traceback (most recent call last):
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 143, in <module>
    train(args)
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 124, in train
    strategy.save_model(model, 'sft_checkpoint.pt', only_rank0=True)
  File "/ColossalAI/applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py", line 176, in save_model
    train(args)
  File "/ColossalAI/applications/ChatGPT/examples/train_sft.py", line 124, in train
        strategy.save_model(model, 'sft_checkpoint.pt', only_rank0=True)if not isinstance(self.model, PreTrainedModel):

  File "/ColossalAI/applications/ChatGPT/chatgpt/trainer/strategies/colossalai.py", line 176, in save_model
AttributeError: 'ColossalAIStrategy' object has no attribute 'model'
    if not isinstance(self.model, PreTrainedModel):
AttributeError: 'ColossalAIStrategy' object has no attribute 'model'
```

### Environment

Python == 3.9
Pytorch == 1.12.0

**Comment by JThh** [comment]
Thanks for pointing out the bugs. As we are in rapid development of recent models, backward compatibility is often not perfectly catered. We will get to this soon!
