### ISSUE TITLE
[BUG]: CUDA out of memory when running the \applications\Chat\example\train_sft.sh

### ISSUE THREAD

**Issue by ls361664056** [hpcaitech/ColossalAI#3361]
### 🐛 Describe the bug

my GPU config is 3090*10, report the memory issue when training llama 7b.
Here is the train_sft.sh I modified:
torchrun --standalone --nproc_per_node=4 train_sft.py \
    --pretrain "./LLaMa/llama-7b-hf" \
    --model 'llama' \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path  "./Coati/coati-7b" \
    --dataset "./data/InstructionWild/data/instinwild_ch.json" \
    --batch_size 1 \
    --accimulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 256 \
    --max_epochs 1 \

Here is my error info:
steps:   0%|                                                                                                               | 0/8 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/GPT_test/ColossalAI/applications/Chat/examples/train_sft.py", line 184, in <module>
    train(args)
  File "/mnt/GPT_test/ColossalAI/applications/Chat/examples/train_sft.py", line 155, in train
    trainer.fit(logger=logger, log_interval=args.log_interval)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/coati/trainer/sft.py", line 94, in fit
    outputs = self.model(prompt_ids, attention_mask=p_mask, labels=labels)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/coati/models/llama/llama_lm.py", line 40, in forward
    return self.model(input_ids, attention_mask=attention_mask, labels=labels, **kwargs)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 772, in forward
    outputs = self.model(
  File "/home/xin.ye/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 621, in forward
    layer_outputs = decoder_layer(
  File "/home/xin.ye/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 316, in forward
    hidden_states, self_attn_weights, present_key_value = self.self_attn(
  File "/home/xin.ye/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/transformers/models/llama/modeling_llama.py", line 253, in forward
    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query_states.dtype)
  File "/home/xin.ye/.local/lib/python3.10/site-packages/torch/nn/functional.py", line 1843, in softmax
    ret = input.softmax(dim, dtype=dtype)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 24.00 MiB (GPU 0; 23.70 GiB total capacity; 20.29 GiB already allocated; 9.56 MiB free; 20.49 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

torch1.13_cu11.7

**Comment by FrankLeeeee** [comment]
You can find some replies in #3331 .

**Comment by binmakeswell** [comment]
Hi @ls361664056 We have update and anwsered in #3331 . Thanks.
