### ISSUE TITLE
[BUG]: Can not train boom-7b due to “int too big to convert” on V100(32GB)

### ISSUE THREAD

**Issue by x22x22** [hpcaitech/ColossalAI#3364]
### 🐛 Describe the bug

train_sft.sh file content:
```bash
torchrun --standalone --nproc_per_node=1 train_sft.py \
    --pretrain "/root/autodl-tmp/conda/colossal-chat/bloom-7b1/" \
    --model 'bloom' \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path  /root/autodl-tmp/ai/colossal-ai-chat/colossal-chat-bloom-7b \
    --dataset /root/autodl-tmp/ai/colossal-ai-chat/dataset/instinwild_full.json \
    --batch_size 1 \
    --accimulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \
```
run `./train_sft.sh`, The error information is as follows:

```bash
OP colossalai._C.fused_optim already exists, skip building.
Time to load fused_optim op: 4.0531158447265625e-05 seconds
[03/31/23 11:21:01] INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:124 __init__
                    INFO     colossalai - colossalai - INFO: Loading data...
[03/31/23 11:21:02] INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:126 __init__
                    INFO     colossalai - colossalai - INFO: Loaded 103695 examples.
                    INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:129 __init__
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 512 examples.
                    INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:132 __init__
                    INFO     colossalai - colossalai - INFO: Formatting inputs...
                    INFO     colossalai - colossalai - INFO: /root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:140 __init__
                    INFO     colossalai - colossalai - INFO: Tokenizing inputs... This may take some time...
Traceback (most recent call last):
  File "train_sft.py", line 184, in <module>
    train(args)
  File "train_sft.py", line 106, in train
    train_dataset = SupervisedDataset(tokenizer=tokenizer,
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 141, in __init__
    data_dict = preprocess(sources, targets, tokenizer)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 111, in preprocess
    examples_tokenized, sources_tokenized = [_tokenize_fn(strings, tokenizer) for strings in (examples, sources)]
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 111, in <listcomp>
    examples_tokenized, sources_tokenized = [_tokenize_fn(strings, tokenizer) for strings in (examples, sources)]
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 83, in _tokenize_fn
    tokenized_list = [
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/coati/dataset/sft_dataset.py", line 84, in <listcomp>
    tokenizer(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2531, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2637, in _call_one
    return self.encode_plus(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2710, in encode_plus
    return self._encode_plus(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/models/bloom/tokenization_bloom_fast.py", line 158, in _encode_plus
    return super()._encode_plus(*args, **kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 500, in _encode_plus
    batched_output = self._batch_encode_plus(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/models/bloom/tokenization_bloom_fast.py", line 147, in _batch_encode_plus
    return super()._batch_encode_plus(*args, **kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 420, in _batch_encode_plus
    self.set_truncation_and_padding(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/transformers/tokenization_utils_fast.py", line 375, in set_truncation_and_padding
    self._tokenizer.enable_truncation(**target)
OverflowError: int too big to convert
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 12067) of binary: /root/autodl-tmp/conda/colossal-chat/bin/python
Traceback (most recent call last):
  File "/root/autodl-tmp/conda/colossal-chat/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/autodl-tmp/conda/colossal-chat/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-31_11:21:07
  host      : autodl-container-fbdc119552-21eb2858
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 12067)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
```

### Environment

torch==1.12.1+cu113
torchvision==0.13.1+cu113
torchaudio==0.12.1
Python==3.8.16
os=Ubuntu 20.04.4 LTS

**Comment by cauyxy** [comment]
@x22x22  #3368 You can modify based on this pull request to get it running first.
