### ISSUE TITLE
[BUG]: train_sft.py: ValueError: Couldn't instantiate the backend tokenizer

### ISSUE THREAD

**Issue by jimmy-walker** [hpcaitech/ColossalAI#3381]
### 🐛 Describe the bug

When I run the commad below:
```
CUDA_VISIBLE_DEVICES=0
colossalai run --nproc_per_node=1 train_sft.py \
    --pretrain "/mywork/bloom-7b1/" \
    --model "bloom" \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path  "/mywork/Coati-7B/" \
    --dataset /mywork/colossalaidata/instinwild_ch.json \
    --batch_size 1 \
    --accimulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \ 
```

It will output the error:
```
[03/31/23 14:17:43] INFO     colossalai - colossalai - INFO:
                             /opt/conda/lib/python3.9/site-packages/colossalai/c
                             ontext/parallel_context.py:521 set_device
                    INFO     colossalai - colossalai - INFO: process rank 0 is
                             bound to device 0
[03/31/23 14:17:47] INFO     colossalai - colossalai - INFO:
                             /opt/conda/lib/python3.9/site-packages/colossalai/c
                             ontext/parallel_context.py:557 set_seed
                    INFO     colossalai - colossalai - INFO: initialized seed on
                             rank 0, numpy: 42, python random: 42,
                             ParallelMode.DATA: 42, ParallelMode.TENSOR: 42,the
                             default parallel seed is ParallelMode.DATA.
                    INFO     colossalai - colossalai - INFO:
                             /opt/conda/lib/python3.9/site-packages/colossalai/i
                             nitialize.py:116 launch
                    INFO     colossalai - colossalai - INFO: Distributed
                             environment is initialized, data parallel size: 1,
                             pipeline parallel size: 1, tensor parallel size: 1
Loading checkpoint shards: 100%|██████████| 2/2 [00:54<00:00, 27.19s/it]
Traceback (most recent call last):
  File "/workspace/ColossalAI/applications/Chat/train_sft.py", line 188, in <module>
    train(args)
  File "/workspace/ColossalAI/applications/Chat/train_sft.py", line 62, in train
    tokenizer = BloomTokenizerFast.from_pretrained(args.pretrain, use_fast=False)
  File "/opt/conda/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9.egg/transformers/tokenization_utils_base.py", line 1811, in from_pretrained
    return cls._from_pretrained(
  File "/opt/conda/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9.egg/transformers/tokenization_utils_base.py", line 1965, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9.egg/transformers/models/bloom/tokenization_bloom_fast.py", line 121, in __init__
    super().__init__(
  File "/opt/conda/lib/python3.9/site-packages/transformers-4.28.0.dev0-py3.9.egg/transformers/tokenization_utils_fast.py", line 120, in __init__
    raise ValueError(
ValueError: Couldn't instantiate the backend tokenizer from one of:
(1) a `tokenizers` library serialization file,
(2) a slow tokenizer instance to convert or
(3) an equivalent slow tokenizer class to instantiate and convert.
You need to have sentencepiece installed to convert a slow tokenizer to a fast one.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 371) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-31_14:20:57
  host      : e225ce22d1c0
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 371)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Error: failed to run torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=127.0.0.1:29500 --rdzv_id=colossalai-default-job train_sft.py --pretrain /mywork/bloom-7b1/ --model bloom --strategy colossalai_zero2 --log_interval 10 --save_path /mywork/Coati-7B/ --dataset /mywork/colossalaidata/instinwild_ch.json --batch_size 1 --accimulation_steps 8 --lr 2e-5 --max_datasets_size 512 --max_epochs 1   on 127.0.0.1, is localhost: True, exception: Encountered a bad command exit code!

Command: 'cd /workspace/ColossalAI/applications/Chat && export NV_LIBCUBLAS_VERSION="11.5.1.109-1" NVIDIA_VISIBLE_DEVICES="0" NV_NVML_DEV_VERSION="11.3.58-1" NV_CUDNN_PACKAGE_NAME="libcudnn8" NV_LIBNCCL_DEV_PACKAGE="libnccl-dev=2.9.9-1+cuda11.3" NV_LIBNCCL_DEV_PACKAGE_VERSION="2.9.9-1" HOSTNAME="e225ce22d1c0" NVIDIA_REQUIRE_CUDA="cuda>=11.3 brand=tesla,driver>=418,driver<419 driver>=450" NV_LIBCUBLAS_DEV_PACKAGE="libcublas-dev-11-3=11.5.1.109-1" NV_NVTX_VERSION="11.3.109-1" NV_CUDA_CUDART_DEV_VERSION="11.3.109-1" NV_LIBCUSPARSE_VERSION="11.6.0.109-1" NV_LIBNPP_VERSION="11.3.3.95-1" NCCL_VERSION="2.9.9-1" PWD="/workspace/ColossalAI/applications/Chat" NV_CUDNN_PACKAGE="libcudnn8=8.2.0.53-1+cuda11.3" NVIDIA_DRIVER_CAPABILITIES="compute,utility" NV_NVPROF_DEV_PACKAGE="cuda-nvprof-11-3=11.3.111-1" NV_LIBNPP_PACKAGE="libnpp-11-3=11.3.3.95-1" NV_LIBNCCL_DEV_PACKAGE_NAME="libnccl-dev" NV_LIBCUBLAS_DEV_VERSION="11.5.1.109-1" NV_LIBCUBLAS_DEV_PACKAGE_NAME="libcublas-dev-11-3" NV_CUDA_CUDART_VERSION="11.3.109-1" HOME="/root" LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:" CUDA_VERSION="11.3.1" NV_LIBCUBLAS_PACKAGE="libcublas-11-3=11.5.1.109-1" NV_LIBNPP_DEV_PACKAGE="libnpp-dev-11-3=11.3.3.95-1" NV_LIBCUBLAS_PACKAGE_NAME="libcublas-11-3" NV_LIBNPP_DEV_VERSION="11.3.3.95-1" LESSCLOSE="/usr/bin/lesspipe %s %s" TERM="xterm" NV_LIBCUSPARSE_DEV_VERSION="11.6.0.109-1" LESSOPEN="| /usr/bin/lesspipe %s" LIBRARY_PATH="/usr/local/cuda/lib64/stubs"NV_CUDNN_VERSION="8.2.0.53" SHLVL="1" NV_CUDA_LIB_VERSION="11.3.1-1" NVARCH="x86_64" NV_CUDNN_PACKAGE_DEV="libcudnn8-dev=8.2.0.53-1+cuda11.3" NV_CUDA_COMPAT_PACKAGE="cuda-compat-11-3" NV_LIBNCCL_PACKAGE="libnccl2=2.9.9-1+cuda11.3" LD_LIBRARY_PATH="/root/.tensornvme/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64" NV_NVPROF_VERSION="11.3.111-1" CUDA_HOME="/usr/local/cuda" PATH="/opt/conda/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" NV_LIBNCCL_PACKAGE_NAME="libnccl2" NV_LIBNCCL_PACKAGE_VERSION="2.9.9-1" OLDPWD="/workspace/ColossalAI/applications" _="/opt/conda/bin/colossalai" LC_CTYPE="C.UTF-8" && torchrun --nproc_per_node=1 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=127.0.0.1:29500 --rdzv_id=colossalai-default-job train_sft.py --pretrain /mywork/bloom-7b1/ --model bloom --strategy colossalai_zero2 --log_interval 10 --save_path /mywork/Coati-7B/ --dataset /mywork/colossalaidata/instinwild_ch.json --batch_size 1 --accimulation_steps 8 --lr 2e-5 --max_datasets_size 512 --max_epochs 1  '

Exit code: 1

Stdout: already printed

Stderr: already printed



====== Training on All Nodes =====
127.0.0.1: failure

====== Stopping All Nodes =====
127.0.0.1: finish
```

I've found seveal methods to overcome it. But it still be here.
Please help me. Thanks!

### Environment
cuda                    11.3
colossalai             0.2.7
datasets               2.10.1
sentencepiece      0.1.97
torch                  1.12.1
torchaudio             0.12.1
torchvision            0.13.1
transformers           4.28.0.dev0

**Comment by 4IK1d** [comment]
Have you tried this "You need to have sentencepiece installed to convert a slow tokenizer to a fast one."?

**Comment by ifromeast** [comment]
```
from transformers import LlamaTokenizer
elif args.model == 'llama':
  tokenizer = LlamaTokenizer.from_pretrained(
      args.pretrain,
      # padding_side="right",
      # use_fast=False,
  )
```

**Comment by jimmy-walker** [comment]
> Have you tried this "You need to have sentencepiece installed to convert a slow tokenizer to a fast one."?

Yes, Just like what I copied, I have already installed sentencepiece (0.1.97).

But it still could not work.

**Comment by jimmy-walker** [comment]
> ```
> from transformers import LlamaTokenizer
> elif args.model == 'llama':
>   tokenizer = LlamaTokenizer.from_pretrained(
>       args.pretrain,
>       # padding_side="right",
>       # use_fast=False,
>   )
> ```

I have tried with `use_fast=False` or `use_fast=True`. Both doesn't work...

**Comment by chengeharrison** [comment]
> > ```
> > from transformers import LlamaTokenizer
> > elif args.model == 'llama':
> >   tokenizer = LlamaTokenizer.from_pretrained(
> >       args.pretrain,
> >       # padding_side="right",
> >       # use_fast=False,
> >   )
> > ```
> 
> I have tried with `use_fast=False` or `use_fast=True`. Both doesn't work...

Hi, it seems that in the bug description you are using bloom model, but here you are configuring llama model.
