### ISSUE TITLE
[BUG]: LlamaRM model has no attribute 'resize_token_embeddings'

### ISSUE THREAD

**Issue by lierik** [hpcaitech/ColossalAI#3389]
### 🐛 Describe the bug

LlamaRM is not a huggingface transformer module but LoraModule, while llamaRM.model is a huggingface transformer model. So LlamaRm has no function "resize_token_embeddings" but LlamaRM.model has. When using Llama to train RM model, it will raise the error: AttributeError: 'LlamaRM' object has no attribute 'resize_token_embeddings'

line 68 in coati/utils/tokenizer_utils.py

**Comment by bingjie3216** [comment]
Met the same issue:

        smart_tokenizer_and_embedding_resize(smart_tokenizer_and_embedding_resize(

  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/x-gpu1/code/Users/jbing/code/ColossalAI/applications/Chat/coati/utils/tokenizer_utils.py", line 68, in smart_tokenizer_and_embedding_resize
  File "/mnt/batch/tasks/shared/LS_root/mounts/clusters/x-gpu1/code/Users/jbing/code/ColossalAI/applications/Chat/coati/utils/tokenizer_utils.py", line 68, in smart_tokenizer_and_embedding_resize
        model.resize_token_embeddings(len(tokenizer))model.resize_token_embeddings(len(tokenizer))

  File "/anaconda/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
  File "/anaconda/envs/coati/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'LlamaRM' object has no attribute 'resize_token_embeddings'AttributeError: 'LlamaRM' object has no attribute 'resize_token_embeddings

**Comment by HaixHan** [comment]
Meet the same issue:
AttributeError: 'LlamaRM' object has no attribute 'resize_token_embeddings'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 526441 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 526440) of binary: /data/anaconda3/bin/python
Traceback (most recent call last):
  File "/data/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/anaconda3/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/data/anaconda3/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/data/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/anaconda3/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by StarsTesla** [comment]
I met this error too, but if you are training the stage 2, you should modified the pretrain to Coati7B(you trained in stage 1) instead of LLaMA7B that provided by huggingface.

**Comment by HaixHan** [comment]
> I met this error too, but if you are training the stage 2, you should modified the pretrain to Coati7B(you trained in stage 1) instead of LLaMA7B that provided by huggingface.

Thank you very much for the reminder！

**Comment by samulew** [comment]
met the some problem , and i add the code at  line 72  of train_reward_model.py , imitating train_sft.py :

tokenizer = LlamaTokenizer.from_pretrained(args.pretrain)
tokenizer.eos_token = '<\s>'
tokenizer.pad_token = tokenizer.eos_token

**Comment by honglvagan** [comment]
me too,i met the same problem

Traceback (most recent call last):
  File "server.py", line 923, in <module>
    add_lora_to_model([shared.args.lora])
  File "/home/ubuntu/Desktop/bookDesk202303061/text-generation-webui/modules/LoRA.py", line 40, in add_lora_to_model
    shared.model.resize_token_embeddings(len(shared.tokenizer))
AttributeError: 'LlamaCppModel' object has no attribute 'resize_token_embeddings'

what should i do to fix it?
