### ISSUE TITLE
[BUG]: META_COMPATIBILITY is not defined

### ISSUE THREAD

**Issue by mcc311** [hpcaitech/ColossalAI#3435]
### 🐛 Describe the bug

Hi Dears:
I found out that if I use torch==1.14, it'll turn out some error during import:
```
mcc311nycu@ioa7mzctr1680319977435-xg5sj:~/examples_new$ ./train_rm.sh
Traceback (most recent call last):  File "train_reward_model.py", line 6, in <module>
    from coati.dataset import HhRlhfDataset, RmStaticDataset
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/coati/dataset/__init__.py", line 1, in <module>
    from .prompt_dataset import PromptDataset
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/coati/dataset/prompt_dataset.py", line 12, in <module>
    from colossalai.logging import get_dist_logger
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/initialize.py", line 18, in <module>
    from colossalai.amp import AMP_TYPE, convert_to_amp  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/amp/__init__.py", line 11, in <module>    from .apex_amp import convert_to_apex_amp
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/amp/apex_amp/__init__.py", line 4, in <module>    from .apex_amp import ApexAMPOptimizer
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/amp/apex_amp/apex_amp.py", line 13, in <module>
    from colossalai.nn.optimizer import ColossalaiOptimizer
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/__init__.py", line 1, in <module>
    from ._ops import *
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/_ops/__init__.py", line 1, in <module>
    from .addmm import colo_addmm
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/_ops/addmm.py", line 6, in <module>
    from ._utils import GeneralTensor, Number, convert_to_colo_tensor, reduce_grad, reduce_input
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/_ops/_utils.py", line 7, in <module>
    from colossalai.nn.layer.utils import divide
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/layer/__init__.py", line 7, in <module>
    from .moe import *
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/layer/moe/__init__.py", line 1, in <module>
    from .checkpoint import load_moe_model, save_moe_model
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/layer/moe/checkpoint.py", line 5, in <module>
    from .experts import MoeExperts
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/nn/layer/moe/experts.py", line 12, in <module>
    from colossalai.zero.legacy.init_ctx import no_shard_zero_decrator
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/zero/__init__.py", line 1, in <module>
    from .gemini import (
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/zero/gemini/__init__.py", line 1, in <module>
    from .chunk import ChunkManager, TensorInfo, TensorState, search_chunk_configuration
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/zero/gemini/chunk/__init__.py", line 3, in <module>
    from .search_utils import classify_params_by_dp_degree, search_chunk_configuration
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/zero/gemini/chunk/search_utils.py", line 10, in <module>
    from colossalai.zero.gemini.memory_tracer import MemStats, OrderedParamGenerator
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/zero/gemini/memory_tracer/__init__.py", line 6, in <module>
    from .static_memstats_collector import StaticMemStatsCollector    # isort:skip
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/zero/gemini/memory_tracer/static_memstats_collector.py", line 7, in <module>
    from colossalai.fx.passes.meta_info_prop import MetaInfoProp
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/fx/__init__.py", line 3, in <module>
    from .passes import MetaInfoProp, metainfo_trace
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/fx/passes/__init__.py", line 2, in <module>
    from .concrete_info_prop import ConcreteInfoProp
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/fx/passes/concrete_info_prop.py", line 10, in <module>
    from colossalai.fx.profiler import GraphInfo, profile_function, profile_method, profile_module
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/fx/profiler/__init__.py", line 3, in <module>
    if is_compatible_with_meta():
  File "/home/mcc311nycu/.local/lib/python3.8/site-packages/colossalai/fx/_compatibility.py", line 54, in is_compatible_with_meta
    return META_COMPATIBILITY
NameError: name 'META_COMPATIBILITY' is not defined
```

So I went to check why, and I found that in [this file](https://github.com/hpcaitech/ColossalAI/blob/main/colossalai/fx/_compatibility.py#L13), it only support torch only 1.12, 1.13 and 2. So I think the document should be fixed. 

### Requirement
- ~torch >= 1.11~

### Environment

torch==1.14

**Comment by binmakeswell** [comment]
Hi @mcc311 how did you install torch 1.14, the latest official pytorch only has 1.13 and 2.0.
https://pytorch.org/docs/versions.html

**Comment by mcc311** [comment]
I'm currently using [NVIDIA container image for Pytorch](https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel-23-02.html ). The document said it used [Pytorch 1.14.0a0+44dac51](https://github.com/pytorch/pytorch/commit/44dac51).

**Comment by daneren** [comment]
Since torch1.14 and torch2.0 are approximately equivalent, you can add processing for torch1.14 in colossalai/fx/_compatibility.py according to the judgment logic of torch2.0.

from typing import Callable

import torch

TORCH_MAJOR = int(torch.__version__.split('.')[0])
TORCH_MINOR = int(torch.__version__.split('.')[1])

if TORCH_MAJOR == 1 and TORCH_MINOR < 12:
    META_COMPATIBILITY = False
elif TORCH_MAJOR == 1 and TORCH_MINOR == 12:
    from . import _meta_regist_12
    META_COMPATIBILITY = True
elif TORCH_MAJOR == 1 and TORCH_MINOR == 13:
    from . import _meta_regist_13
    META_COMPATIBILITY = True
elif TORCH_MAJOR == 1 and TORCH_MINOR == 14:
    from . import _meta_regist_13
    META_COMPATIBILITY = True
elif TORCH_MAJOR == 2:
    from . import _meta_regist_13
    META_COMPATIBILITY = True
    raise UserWarning("Colossalai is not tested with torch2.0 yet!!!")
