### ISSUE TITLE
[BUG]: Fail to do supervised instructs tuning becase of an 

### ISSUE THREAD

**Issue by q423462798** [hpcaitech/ColossalAI#3462]
### 🐛 Describe the bug

I try to do a supervised instructs tuning  on a llama-7B with a machine with four T4 following the example by following command:

`torchrun --standalone --nproc_per_node=4 applications/Chat/examples/train_sft.py --pretrain "/root/ColossalAI/llama/models" --model 'llama' --strategy colossalai_zero2 --log_interval 10 --save_path "/root/ColossalAI/Coati7B" --dataset "/root/ColossalAI/dataset/data_ch"  --batch_size 4     --accimulation_steps 8     --lr 2e-5     --max_datasets_size 512     --max_epochs 1`

But got a unknown exit code -7 as following log:

WARNING:torch.distributed.run:

Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.

/root/miniconda3/lib/python3.7/site-packages/torch/library.py:130: UserWarning: Overriding a previously registered kernel for the same operator and the same dispatch key

  operator: aten::index.Tensor(Tensor self, Tensor?[] indices) -> Tensor
    registered at aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: Meta
  previous kernel: registered at ../aten/src/ATen/functorch/BatchRulesScatterOps.cpp:1053
       new kernel: registered at /dev/null:219 (Triggered internally at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:150.)
  self.m.impl(name, dispatch_key, fn)

/root/miniconda3/lib/python3.7/site-packages/torch/library.py:130: UserWarning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::index.Tensor(Tensor self, Tensor?[] indices) -> Tensor
    registered at aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: Meta
  previous kernel: registered at ../aten/src/ATen/functorch/BatchRulesScatterOps.cpp:1053
       new kernel: registered at /dev/null:219 (Triggered internally at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:150.)
  self.m.impl(name, dispatch_key, fn)

/root/miniconda3/lib/python3.7/site-packages/torch/library.py:130: UserWarning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::index.Tensor(Tensor self, Tensor?[] indices) -> Tensor
    registered at aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: Meta
  previous kernel: registered at ../aten/src/ATen/functorch/BatchRulesScatterOps.cpp:1053
       new kernel: registered at /dev/null:219 (Triggered internally at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:150.)
  self.m.impl(name, dispatch_key, fn)

/root/miniconda3/lib/python3.7/site-packages/torch/library.py:130: UserWarning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::index.Tensor(Tensor self, Tensor?[] indices) -> Tensor
    registered at aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: Meta
  previous kernel: registered at ../aten/src/ATen/functorch/BatchRulesScatterOps.cpp:1053
       new kernel: registered at /dev/null:219 (Triggered internally at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:150.)
  self.m.impl(name, dispatch_key, fn)

[04/06/23 05:22:32] INFO     colossalai - colossalai - INFO: /root/miniconda3/lib/python3.7/site-packages/colossalai/context/parallel_context.py:521 set_device
                    INFO     colossalai - colossalai - INFO: process rank 3 is bound to device 3
[04/06/23 05:22:32] INFO     colossalai - colossalai - INFO: /root/miniconda3/lib/python3.7/site-packages/colossalai/context/parallel_context.py:521 set_device
                    INFO     colossalai - colossalai - INFO: process rank 1 is bound to device 1
[04/06/23 05:22:32] INFO     colossalai - colossalai - INFO: /root/miniconda3/lib/python3.7/site-packages/colossalai/context/parallel_context.py:521 set_device
                    INFO     colossalai - colossalai - INFO: process rank 2 is bound to device 2
[04/06/23 05:22:32] INFO     colossalai - colossalai - INFO: /root/miniconda3/lib/python3.7/site-packages/colossalai/context/parallel_context.py:521 set_device
                    INFO     colossalai - colossalai - INFO: process rank 0 is bound to device 0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -7) local_rank: 0 (pid: 2514) of binary: /root/miniconda3/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/run.py", line 756, in run
    )(*cmd_args)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.7/site-packages/torch/distributed/launcher/api.py", line 248, in launch_agent
    failures=result.failures,
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

====================================================
applications/Chat/examples/train_sft.py FAILED

Failures:
[1]:
  time      : 2023-04-06_05:22:37
  host      : standalone-x86-26-113.cluster.local
  rank      : 1 (local_rank: 1)
  exitcode  : -7 (pid: 2515)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2515
[2]:
  time      : 2023-04-06_05:22:37
  host      : standalone-x86-26-113.cluster.local
  rank      : 2 (local_rank: 2)
  exitcode  : -7 (pid: 2516)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2516
[3]:
  time      : 2023-04-06_05:22:37
  host      : standalone-x86-26-113.cluster.local
  rank      : 3 (local_rank: 3)
  exitcode  : -7 (pid: 2517)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2517

Root Cause (first observed failure):
[0]:
  time      : 2023-04-06_05:22:37
  host      : standalone-x86-26-113.cluster.local
  rank      : 0 (local_rank: 0)
  exitcode  : -7 (pid: 2514)
  error_file: <N/A>
  traceback : Signal 7 (SIGBUS) received by PID 2514

### Environment

cuda 11.0 on T4
python 3.7
pytorch 1.13.1+cu117

**Comment by Camille7777** [comment]
hiiii, @q423462798 have you tried to run it again (still get this error?) and check with the GPU resources availability?

**Comment by Camille7777** [comment]
Hi, got that, how about the size of your training dataset "data_ch" and try to reduce the batch size? The CPU memory usage may lead to this problem sometimes.
