### ISSUE TITLE
[BUG]: pickle_module.load has bug: _pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by Modas-Li** [hpcaitech/ColossalAI#3511]
### 🐛 Describe the bug

`Loading checkpoint shards:   0%|                                            | 0/33 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/data/anaconda3/lib/python3.7/site-packages/transformers/modeling_utils.py", line 415, in l                                oad_state_dict
    return torch.load(checkpoint_file, map_location="cpu")
  File "/data/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/data/anaconda3/lib/python3.7/site-packages/torch/serialization.py", line 1002, in _legacy_                                load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.
`

**Comment by JThh** [comment]
Hi, what was your command to run the codes, and where did you download the checkpoints?
