### ISSUE TITLE
[BUG]: AssertionError

### ISSUE THREAD

**Issue by wccccp** [hpcaitech/ColossalAI#3538]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "/home/appuser/miniconda3/envs/wcpshiyan/bin/colossalai", line 8, in <module>
    sys.exit(cli())
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/colossalai/cli/launcher/__init__.py", line 87, in run
    launch_multi_processes(args)
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/colossalai/cli/launcher/run.py", line 272, in launch_multi_processes
    cmd = get_launch_command(master_addr=args.master_addr,
  File "/home/appuser/miniconda3/envs/wcpshiyan/lib/python3.8/site-packages/colossalai/cli/launcher/run.py", line 157, in get_launch_command
    assert torch_version.major == 1
AssertionError

**Comment by ai-naymul** [comment]
The error occurs when the script checks the major version of the installed PyTorch package and finds that it is not equal to 1. This could mean that you have an incompatible version of PyTorch installed. You may want to check the version of PyTorch you have installed and ensure that it is compatible with the version required by colossalai.
Thank you :)
