### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'colossalai._analyzer'

### ISSUE THREAD

**Issue by a1xiaoyaozi** [hpcaitech/ColossalAI#3540]
### 🐛 Describe the bug

My command is as follows:
git clone https://github.com/hpcaitech/ColossalAI.git
cd ColossalAI
# install colossalai
pip install .
# install chat
cd applications/Chat
pip install .
git clone https://github.com/hpcaitech/transformers
cd transformers
pip install .
# train
torchrun --standalone --nproc_per_node=4 train_sft.py \
    --pretrain "./LLaMa-7B" \
    --model 'llama' \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path  ./Coati-7B \
    --dataset ./dataset/instinwild_en.json \
    --batch_size 4 \
    --accimulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1

# result
Traceback (most recent call last):
  File "/root/ColossalAI/applications/Chat/examples/train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/coati/dataset/__init__.py", line 1, in <module>
    from .prompt_dataset import PromptDataset
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/coati/dataset/prompt_dataset.py", line 12, in <module>
    from colossalai.logging import get_dist_logger
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/initialize.py", line 18, in <module>
    from colossalai.amp import AMP_TYPE, convert_to_amp
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/amp/__init__.py", line 11, in <module>
    from .apex_amp import convert_to_apex_amp
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/amp/apex_amp/__init__.py", line 4, in <module>
    from .apex_amp import ApexAMPOptimizer
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/amp/apex_amp/apex_amp.py", line 13, in <module>
    from colossalai.nn.optimizer import ColossalaiOptimizer
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/__init__.py", line 1, in <module>
    from ._ops import *
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/_ops/__init__.py", line 1, in <module>
    from .addmm import colo_addmm
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/_ops/addmm.py", line 6, in <module>
    from ._utils import GeneralTensor, Number, convert_to_colo_tensor, reduce_grad, reduce_input
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/_ops/_utils.py", line 7, in <module>
    from colossalai.nn.layer.utils import divide
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/layer/__init__.py", line 7, in <module>
    from .moe import *
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/layer/moe/__init__.py", line 1, in <module>
    from .checkpoint import load_moe_model, save_moe_model
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/layer/moe/checkpoint.py", line 5, in <module>
    from .experts import MoeExperts
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/nn/layer/moe/experts.py", line 12, in <module>
    from colossalai.zero.legacy.init_ctx import no_shard_zero_decrator
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/zero/__init__.py", line 1, in <module>
    from .gemini import (
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/zero/gemini/__init__.py", line 3, in <module>
    from .gemini_ddp import GeminiDDP, ZeroDDP
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/zero/gemini/gemini_ddp.py", line 17, in <module>
    from colossalai.utils.model.experimental import LazyTensor
  File "/root/miniconda3/envs/coati/lib/python3.9/site-packages/colossalai/utils/model/experimental.py", line 10, in <module>
    from colossalai._analyzer._subclasses import MetaTensor
ModuleNotFoundError: No module named 'colossalai._analyzer'

### Environment

CUDA  11.0
cuDNN 8
Python 3.9
Pytorch 1.13.1+cu117

**Comment by allaccs** [comment]
Worked yesterday for me, stopped working today.

Workaround : git checkout e6a132a449d10489e65544e77f49190e2817b587 
Use the commit from yesterday and it works, I guess an update broke the code.

**Comment by tuzeao** [comment]
Meeted the same problem too.
You need to checkout the old version which is around yesterday morning or before.

**Comment by FrankLeeeee** [comment]
Yes, the source code is not stable until an official release.

**Comment by RestartNeverLate** [comment]
我通过复制colossalai/_analyzer 到site-packages/colossalai/  解决了这个问题
cp -r _analyzer/  /path/to/site-packages/colossalai/

**Comment by FrankLeeeee** [comment]
> 

I will try to fix this bug today.

**Comment by tianbuwei** [comment]
same question

**Comment by wangxiaobo007** [comment]
same question

**Comment by jamesunnc** [comment]
Please does anyone get any specific advice on how to solve this import error?

**Comment by wangxiaobo007** [comment]
> Please does anyone get any specific advice on how to solve this import error?

> 我通过复制colossalai/_analyzer 到site-packages/colossalai/ 解决了这个问题 cp -r _analyzer/ /path/to/site-packages/colossalai/

I refer to the above solution and it can now run normally, but I always feel that this method is not very friendly

**Comment by jamesunnc** [comment]
Many thanks, it works now.

**Comment by LDH007** [comment]
> 我通过复制colossalai/_analyzer 到site-packages/colossalai/ 解决了这个问题 cp -r _analyzer/ /path/to/site-packages/colossalai/

awesome!

**Comment by catqaq** [comment]
> 

any progress?
