### ISSUE TITLE
[BUG]: setStorage out of bounds during inference

### ISSUE THREAD

**Issue by alexanderswerdlow** [hpcaitech/ColossalAI#3674]
### 🐛 Describe the bug

Running inference after training or validation for diffusion model results in a `setStorage` `out of bounds for storage of size 0` error. This happens when I uncomment the log_images in train callback, or try to similarly run inference in my own codebase using colossal.

```
Traceback (most recent call last):
  File "/repo_parent/ColossalAI/examples/images/diffusion/main.py", line 844, in <module>
    trainer.fit(model, data)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/trainer/call.py", line 36, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/strategies/launchers/subprocess_script.py", line 88, in launch
    return function(*args, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1103, in _run
    results = self._run_stage()
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1182, in _run_stage
    self._run_train()
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1205, in _run_train
    self.fit_loop.run()
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/loops/fit_loop.py", line 267, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/loops/epoch/training_epoch_loop.py", line 229, in advance
    self.trainer._call_callback_hooks("on_train_batch_end", batch_end_outputs, batch, batch_idx)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/lightning/pytorch/trainer/trainer.py", line 1385, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/main.py", line 498, in on_train_batch_end
    self.log_img(pl_module, batch, batch_idx, split="train")
  File "/repo_parent/ColossalAI/examples/images/diffusion/main.py", line 460, in log_img
    images = pl_module.log_images(batch, split=split, **self.log_images_kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 1378, in log_images
    samples, z_denoise_row = self.sample_log(cond=c,
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 1274, in sample_log
    samples, intermediates = ddim_sampler.sample(ddim_steps, batch_size, shape, cond, verbose=False, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddim.py", line 103, in sample
    samples, intermediates = self.ddim_sampling(conditioning, size,
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddim.py", line 163, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, index=index, use_original_steps=ddim_use_original_steps,
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddim.py", line 188, in p_sample_ddim
    model_output = self.model.apply_model(x, t, c)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 951, in apply_model
    x_recon = self.model(x_noisy, t, **cond)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/models/diffusion/ddpm.py", line 1521, in forward
    out = self.diffusion_model(x, t, context=cc)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/repo_parent/ColossalAI/examples/images/diffusion/ldm/modules/diffusionmodules/openaimodel.py", line 770, in forward
    emb = self.time_embed(t_emb)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/colossalai/tensor/colo_parameter.py", line 91, in __torch_function__
    return super().__torch_function__(func, types, args, kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/colossalai/tensor/colo_tensor.py", line 184, in __torch_function__
    ret = func(*args, **kwargs)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/colossalai/nn/_ops/linear.py", line 171, in colo_linear
    return colo_linear_imp(input, weight, bias)
  File "/user_home/anaconda3/envs/ldmmm/lib/python3.9/site-packages/colossalai/nn/_ops/linear.py", line 78, in colo_linear_imp
    ret_tensor = ColoTensor.from_torch_tensor(F.linear(input_tensor, weight, bias), spec=ColoTensorSpec(pg))
RuntimeError: setStorage: sizes [320, 1280], strides [1, 320], storage offset 0, and itemsize 2 requiring a storage size of 819200 are out of bounds for storage of size 0
```

### Environment

Occurs in:
torch: `1.12.1`
python: `3.9.12`
xformers: `0.0.19`
ColossalAI: `0.2.5`

As well as:
torch: `2.0.0+cu117`
python: `3.10.11`
xformers compiled locally
ColossalAI compiled locally

**Comment by iceflame89** [comment]
same problem

**Comment by bgl0703** [comment]
same problem
