### ISSUE TITLE
[BUG]: torch.distributed.elastic.multiprocessing.api:failed

### ISSUE THREAD

**Issue by youkpan** [hpcaitech/ColossalAI#3677]
### 🐛 Describe the bug
```
Error:
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1167 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1169 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 1170 closing signal SIGTERM

ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 1168) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/workspace/ColossalAI/applications/Chat/examples/train_sft.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-03_23:26:17
  host      : 1f6d79e0d3f1
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 1168)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 1168
```
cmd

torchrun --standalone --nproc_per_node=4 /workspace/ColossalAI/applications/Chat/examples/train_sft.py \
    --pretrain "" \
    --model 'llama' \
    --strategy naive \
    --log_interval 10 \
    --save_path  "/workspace/train_model" \
    --dataset "/workspace/data/en/alpaca.json" \
    --batch_size 1 \
    --accumulation_steps 8 \
    --lr 2e-4 \
    --max_datasets_size 512 \
    --max_epochs 10 \
    --lora_rank 16\
    --grad_checkpoint

### Environment

4x 4090 + 258 G RAM
same on 7x4090 ..

tried:
export OMP_NUM_THREADS=7
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6

**Comment by JThh** [comment]
Have you tested out other strategies such as ‘colossalai_gemini’?

**Comment by binmakeswell** [comment]
Hi @youkpan Could you please monitor your CPU memory usage? It looks like running out of CPU memory.
You can also refer to [How to train with limited resources](https://github.com/hpcaitech/ColossalAI/tree/main/applications/Chat#faq)
