### ISSUE TITLE
[BUG]: gloo report listen port conflict when training SD model on 12Node*8GPU

### ISSUE THREAD

**Issue by linxiaochunsd** [hpcaitech/ColossalAI#3689]
### 🐛 Describe the bug

The main.py file is copied from ColossalAI Demo, the only modification  is switching to our own dataset and dataloader. We started the training by `colossalai run --nproc_per_node 8 --host $TRAINER_IP_LIST --master_port 6001 --master_addr $MASTER_IP --extra_launch_args  "rdzv_conf read_timeout=3600"  main.py --logdir ./output/ --train --base configs/train_colossalai.yaml --ckpt 512-base-ema.ckpt`. 
It worked on 4Node*8GPU, 6Node*8GPU, but failed on 10Node*8GPU and 12Node*8GPU.

When we try to train stable diffusion model on 96 GPU(12Node*8GPU), an error(which attached below) occurred randomly on 1-3 nodes. When error occurred, we found a strange phenomenon, which may be the cause of the error: ColossalAI was listening on more than 700+ ports on every node. We believe that the error was caused by a port conflict, but the cause of the abnormal number of listening ports was not located.

```
Traceback (most recent call last):
  File "main.py", line 590, in <module>
    config="./config.py"
  File "/usr/local/lib/python3.7/dist-packages/colossalai/initialize.py", line 227, in launch_from_torch
    verbose=verbose)
  File "/usr/local/lib/python3.7/dist-packages/colossalai/initialize.py", line 102, in launch
    gpc.init_parallel_groups()
  File "/usr/local/lib/python3.7/dist-packages/colossalai/context/parallel_context.py", line 479, in init_parallel_groups
    parallel_setting = initializer.init_dist_group()
  File "/usr/local/lib/python3.7/dist-packages/colossalai/context/process_group_initializer/initializer_data.py", line 45, in init_dist_group
    group_cpu = dist.new_group(ranks, backend='gloo') if dist.get_backend() != 'gloo' else group
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 3342, in new_group
    timeout=timeout,
  File "/usr/local/lib/python3.7/dist-packages/torch/distributed/distributed_c10d.py", line 862, in _new_process_group_helper
    pg = ProcessGroupGloo(prefix_store, group_rank, group_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:185] listen: Address already in use
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26381 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26382 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26383 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26385 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26386 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26387 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 26388 closing signal SIGTERM


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   c10d::ProcessGroupGloo::ProcessGroupGloo(c10::intrusive_ptr<c10d::Store, c10::detail::intrusive_target_default_null_type<c10d::Store> > const&, int, int, c10::intrusive_ptr<c10d::ProcessGroupGloo::Options, c10::detail::intrusive_target_default_null_type<c10d::ProcessGroupGloo::Options> >)
1   gloo::rendezvous::Context::connectFullMesh(gloo::rendezvous::Store&, std::shared_ptr<gloo::transport::Device>&)
2   gloo::rendezvous::PrefixStore::wait(std::vector<std::string, std::allocator<std::string> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&)
3   c10d::PrefixStore::wait(std::vector<std::string, std::allocator<std::string> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&)
4   c10d::PrefixStore::wait(std::vector<std::string, std::allocator<std::string> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&)
5   c10d::TCPStore::wait(std::vector<std::string, std::allocator<std::string> > const&, std::chrono::duration<long, std::ratio<1l, 1000l> > const&)
6   c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1683176781 (unix time) try "date -d @1683176781" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x66bd) received by PID 26388 (TID 0x7efc208eb740) from PID 26301 ***]


``` 

We temporarily commented out `gloo` to skip this error. Hope there will be an official solution for this error. 

<img width="848" alt="ab71fb490f7cbb248a1811f123357f97" src="https://user-images.githubusercontent.com/19832205/236425173-c5e26d68-45c9-4aae-b5e1-07edf74b4848.png">

### Environment

NVIDIA-SMI 460.32.03    
Driver Version: 460.32.03    
CUDA Version: 11.2
Python 3.7.16

colossalai               0.2.8

torch                    1.13.1
torch                    1.13.1
torchaudio               0.13.1
torchmetrics             0.11.4
torchvision              0.14.1

lightning                1.9.0
lightning-cloud          0.5.34
lightning-utilities      0.8.0

nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96

**Comment by shileims** [comment]
+1
