### ISSUE TITLE
[BUG]: RLHF Training Stage1 of ColossalChat works well on a single GPU but not on two GPUs

### ISSUE THREAD

**Issue by Ozawa333** [hpcaitech/ColossalAI#3701]
### 🐛 Describe the bug

**It's program works well on following commands**

torchrun --standalone --nproc_per_node=1 train_sft.py \
    --pretrain "../checkpointhf/" \
    --model 'llama' \
    --strategy colossalai_zero2 \
    --log_interval 10 \
    --save_path  ../checkpoint/ \
    --dataset yizhongw/self_instruct \
    --batch_size 1 \
    --accumulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \
    --lora_rank 16 \
    --grad_checkpoint

**But if I change '--nproc_per_node=1' from 1 to 2**
**The programming will stay here for a long time**

[05/06/23 19:28:56] INFO     colossalai - colossalai - INFO:                                                             
                             /opt/conda/lib/python3.10/site-packages/colossalai/context/parallel_context.py:522          
                             set_device                                                                                  
                    INFO     colossalai - colossalai - INFO: process rank 0 is bound to device 0                         
[05/06/23 19:28:56] INFO     colossalai - colossalai - INFO:                                                             
                             /opt/conda/lib/python3.10/site-packages/colossalai/context/parallel_context.py:522          
                             set_device                                                                                  
                    INFO     colossalai - colossalai - INFO: process rank 1 is bound to device 1    

**and them report the error**       
              
[E ProcessGroupNCCL.cpp:821] [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808940 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:821] [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808948 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/jovyan/work/ColossalAI/applications/Chat/examples/train_sft.py", line 196, in <module>
    train(args)
  File "/home/jovyan/work/ColossalAI/applications/Chat/examples/train_sft.py", line 39, in train
    strategy = ColossalAIStrategy(stage=2, placement_policy='cuda')
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/colossalai.py", line 82, in __init__
    super().__init__(seed)
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/ddp.py", line 26, in __init__
    super().__init__()
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/base.py", line 26, in __init__
    self.setup_distributed()
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/colossalai.py", line 122, in setup_distributed
    colossalai.launch_from_torch({}, seed=self.seed)
  File "/opt/conda/lib/python3.10/site-packages/colossalai/initialize.py", line 218, in launch_from_torch
    launch(config=config,
  File "/opt/conda/lib/python3.10/site-packages/colossalai/initialize.py", line 109, in launch
    gpc.detect_num_processes_on_current_node()
  File "/opt/conda/lib/python3.10/site-packages/colossalai/context/parallel_context.py", line 92, in detect_num_processes_on_current_node
    dist.all_gather_object(hostname_list, hostname, group=self.get_group(ParallelMode.GLOBAL))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1896, in all_gather_object
    all_gather(output_tensors, input_tensor, group=group)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2277, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: NCCL communicator was aborted on rank 0.  Original reason for failure was: [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808948 milliseconds before timing out.
Traceback (most recent call last):
  File "/home/jovyan/work/ColossalAI/applications/Chat/examples/train_sft.py", line 196, in <module>
    train(args)
  File "/home/jovyan/work/ColossalAI/applications/Chat/examples/train_sft.py", line 39, in train
    strategy = ColossalAIStrategy(stage=2, placement_policy='cuda')
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/colossalai.py", line 82, in __init__
    super().__init__(seed)
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/ddp.py", line 26, in __init__
    super().__init__()
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/base.py", line 26, in __init__
    self.setup_distributed()
  File "/opt/conda/lib/python3.10/site-packages/coati/trainer/strategies/colossalai.py", line 122, in setup_distributed
    colossalai.launch_from_torch({}, seed=self.seed)
  File "/opt/conda/lib/python3.10/site-packages/colossalai/initialize.py", line 218, in launch_from_torch
    launch(config=config,
  File "/opt/conda/lib/python3.10/site-packages/colossalai/initialize.py", line 109, in launch
    gpc.detect_num_processes_on_current_node()
  File "/opt/conda/lib/python3.10/site-packages/colossalai/context/parallel_context.py", line 92, in detect_num_processes_on_current_node
    dist.all_gather_object(hostname_list, hostname, group=self.get_group(ParallelMode.GLOBAL))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1896, in all_gather_object
    all_gather(output_tensors, input_tensor, group=group)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2277, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: NCCL communicator was aborted on rank 1.  Original reason for failure was: [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808940 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808940 milliseconds before timing out.
[E ProcessGroupNCCL.cpp:456] Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
[E ProcessGroupNCCL.cpp:461] To avoid data inconsistency, we are taking the entire process down.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=1, OpType=ALLGATHER, Timeout(ms)=1800000) ran for 1808948 milliseconds before timing out.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 8371 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 1 (pid: 8372) of binary: /opt/conda/bin/python3.10
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
train_sft.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-06_19:59:08
  host      : e86b8d4b6489
  rank      : 1 (local_rank: 1)
  exitcode  : -6 (pid: 8372)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 8372
=====================================================

### Environment

GPU RTX4090*2
cudatoolkit-dev           11.7.0
colossalai                     0.2.8

**Comment by elven2016** [comment]
Out of memory too， 2*V100 32GB ，cudatoolkit-dev 11.7.0colossalai 0.2.8    stage 1 i change the strategy to  naive, it can run，and  complete less than 2 min, not ssure if it is ok
and in stage2, use ddp, gemini,zero2,ervery strategy failed oom,

**Comment by Ozawa333** [comment]
> Out of memory too， 2*V100 32GB ，cudatoolkit-dev 11.7.0colossalai 0.2.8 stage 1 i change the strategy to naive, it can run，and complete less than 2 min, not ssure if it is ok and in stage2, use ddp, gemini,zero2,ervery strategy failed oom,

thank you so much, I will try it on a stronger server

**Comment by xiaotingyun** [comment]
I also encountered this problem, do you have a solution now?

**Comment by jiejie1993** [comment]
I also encountered this problem, do you have a solution now?

**Comment by CWHer** [comment]
I am sorry I can not reproduce this issue with the latest code from `main` branch.

Please reopen this issue if the error persists.
