### ISSUE TITLE
[BUG]: Stage 3 gives RuntimeError: probability tensor contains either `inf`, `nan` or element < 0

### ISSUE THREAD

**Issue by sdvies** [hpcaitech/ColossalAI#3732]
### 🐛 Describe the bug

Hi!
After running _stage 1_ and _stage 2_ of the Chat, obtaining the corresponding models, I proceeded to run **stage 3** with the following parameters in the _train_prompts.sh_ file:

```
set_n_least_used_CUDA_VISIBLE_DEVICES() {
    local n=${1:-"9999"}
    echo "GPU Memory Usage:"
    local FIRST_N_GPU_IDS=$(nvidia-smi --query-gpu=memory.used --format=csv \
        | tail -n +2 \
        | nl -v 0 \
        | tee /dev/tty \
        | sort -g -k 2 \
        | awk '{print $1}' \
        | head -n $n)
    export CUDA_VISIBLE_DEVICES=$(echo $FIRST_N_GPU_IDS | sed 's/ /,/g')
    echo "Now CUDA_VISIBLE_DEVICES is set to:"
    echo "CUDA_VISIBLE_DEVICES=$CUDA_VISIBLE_DEVICES"
}

set_n_least_used_CUDA_VISIBLE_DEVICES 1

torchrun --standalone --nproc_per_node=1 examples/train_prompts.py \
        --prompt_dataset "examples/seed_prompts_en.jsonl" \
        --pretrain_dataset "examples/instinwild_en.json" \
        --strategy naive \
        --model 'bloom' \
        --pretrain "/workspace/ColossalAI/applications/Chat/output_model/stage_1" \
        --rm_path "output_model/stage_2/rmstatic.pt" \
        --rm_pretrain "bigscience/bloom-560m" \
        --save_path "output_model/stage_3/rf_model.pt" \
        --train_batch_size 1\ 
        --max_epochs 1\ 
     
```
So, when carrying out this third step ( _bash examples/train_rm.sh_), I get the following output:

```
GPU Memory Usage:
     0  0 MiB
Now CUDA_VISIBLE_DEVICES is set to:
CUDA_VISIBLE_DEVICES=0
/opt/conda/lib/python3.8/site-packages/torch/library.py:130: UserWarning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::eye.m_out(int n, int m, *, Tensor(a!) out) -> Tensor(a!)
    registered at aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: Meta
  previous kernel: registered at aten/src/ATen/RegisterCPU.cpp:30798
       new kernel: registered at /dev/null:219 (Triggered internally at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:150.)
  self.m.impl(name, dispatch_key, fn)
/opt/conda/lib/python3.8/site-packages/torch/library.py:130: UserWarning: Overriding a previously registered kernel for the same operator and the same dispatch key
  operator: aten::index.Tensor(Tensor self, Tensor?[] indices) -> Tensor
    registered at aten/src/ATen/RegisterSchema.cpp:6
  dispatch key: Meta
  previous kernel: registered at ../aten/src/ATen/functorch/BatchRulesScatterOps.cpp:1053
       new kernel: registered at /dev/null:219 (Triggered internally at ../aten/src/ATen/core/dispatch/OperatorEntry.cpp:150.)
  self.m.impl(name, dispatch_key, fn)
[05/11/23 08:12:12] INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/prompt_dataset.py:25 __init__                                           
                    INFO     colossalai - colossalai - INFO: Loading data...                                                                                                              
                    INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/prompt_dataset.py:27 __init__                                           
                    INFO     colossalai - colossalai - INFO: Loaded 429 examples.                                                                                                         
                    INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/prompt_dataset.py:30 __init__                                           
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 16384 examples.                                                                                          
                    INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:125 __init__                                             
                    INFO     colossalai - colossalai - INFO: Loading data...                                                                                                              
                    INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:127 __init__                                             
                    INFO     colossalai - colossalai - INFO: Loaded 52191 examples.                                                                                                       
                    INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:130 __init__                                             
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 16384 examples.                                                                                          
                    INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:133 __init__                                             
                    INFO     colossalai - colossalai - INFO: Formatting inputs...                                                                                                         
                    INFO     colossalai - colossalai - INFO: /opt/conda/lib/python3.8/site-packages/coati/dataset/sft_dataset.py:141 __init__                                             
                    INFO     colossalai - colossalai - INFO: Tokenizing inputs... This may take some time...                                                                              
Train epoch [1/5]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:34<00:00,  2.33it/s, reward=nan]
Train epoch [2/5]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:34<00:00,  2.33it/s, reward=nan]
Train epoch [3/5]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:34<00:00,  2.33it/s, reward=nan]
Train epoch [4/5]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:34<00:00,  2.33it/s, reward=nan]
Train epoch [5/5]: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 80/80 [00:34<00:00,  2.33it/s, reward=nan]
Episode [1/10]: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 10/10 [03:18<00:00, 19.89s/it]
Episode [2/10]:   0%|                                                                                                                                              | 0/10 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "examples/train_prompts.py", line 233, in <module>
    main(args)
  File "examples/train_prompts.py", line 190, in main
    trainer.fit(prompt_dataloader=prompt_dataloader,
  File "/opt/conda/lib/python3.8/site-packages/coati/trainer/base.py", line 118, in fit
    experience = self._make_experience(prompts)
  File "/opt/conda/lib/python3.8/site-packages/coati/trainer/base.py", line 62, in _make_experience
    return self.experience_maker.make_experience(inputs, **self.generate_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/coati/experience_maker/naive.py", line 19, in make_experience
    sequences, attention_mask, action_mask = self.actor.generate(input_ids,
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/coati/models/base/actor.py", line 34, in generate
    sequences = generate(self.model, input_ids, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/coati/models/generation.py", line 131, in generate
    return sample(model,
  File "/opt/conda/lib/python3.8/site-packages/coati/models/generation.py", line 68, in sample
    next_tokens = torch.multinomial(probs, num_samples=1).squeeze(1)
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2751529) of binary: /opt/conda/bin/python
Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
examples/train_prompts.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-05-11_08:15:52
  host      : a0ef77adeb08
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 2751529)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
examples/train_prompts.sh: line 32: --max_epochs: command not found

```
As you can see in the code above, I get **two** errors:

```
RuntimeError: probability tensor contains either `inf`, `nan` or element < 0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2751529) of binary: /opt/conda/bin/python
```

**How could this situation be solved, and what should I do to make the stage 3 run smoothly?**

Thank you!!

**Comment by CWHer** [comment]
This problem is hyper-parameter related and may not have some general solutions. 😢
