### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'invoke.vendor.decorator'

### ISSUE THREAD

**Issue by AndrWeisR** [hpcaitech/ColossalAI#3755]
### 🐛 Describe the bug

I have successfully installed Collosal AI on WSL (running Ubuntu 20.04.5) with command `pip install colossalai`
When I then run `colossalai check -i` I get an error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/fabric/connection.py", line 7, in <module>
    from invoke.vendor.decorator import decorator
ModuleNotFoundError: No module named 'invoke.vendor.decorator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/usr/local/lib/python3.8/dist-packages/colossalai/cli/__init__.py", line 1, in <module>
    from .cli import cli
  File "/usr/local/lib/python3.8/dist-packages/colossalai/cli/cli.py", line 5, in <module>
    from .launcher import run
  File "/usr/local/lib/python3.8/dist-packages/colossalai/cli/launcher/__init__.py", line 5, in <module>
    from .run import launch_multi_processes
  File "/usr/local/lib/python3.8/dist-packages/colossalai/cli/launcher/run.py", line 12, in <module>
    from .multinode_runner import MultiNodeRunner
  File "/usr/local/lib/python3.8/dist-packages/colossalai/cli/launcher/multinode_runner.py", line 5, in <module>
    import fabric
  File "/usr/local/lib/python3.8/dist-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/usr/local/lib/python3.8/dist-packages/fabric/connection.py", line 9, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

### Environment

WSL on Windows 10, running Ubuntu 20.04.5, Python 3.8.10

**Comment by AndrWeisR** [comment]
Note, I just fixed this by running `sudo pip3 install decorator` and then `colossalai check -i` worked. Might be worth documenting this, or including decerator as a dependency?
