### ISSUE TITLE
[BUG]:  ./train_sft.sh

### ISSUE THREAD

**Issue by steelllll** [hpcaitech/ColossalAI#3874]
### 🐛 Describe the bug

_**Hello everyone, i've got an error while trying to train colossal :**_

```bash
(coati) steel@DESKTOP-D1DE4HI:/mnt/c/Users/zinou/colossal/ColossalAI/applications/Chat/examples$ chmod +x ./train_sft.py
(coati) steel@DESKTOP-D1DE4HI:/mnt/c/Users/zinou/colossal/ColossalAI/applications/Chat/examples$ ./train_sft.sh
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/mnt/c/Users/zinou/colossal/ColossalAI/applications/Chat/examples/train_sft.py", line 7, in <module>
Traceback (most recent call last):
  File "/mnt/c/Users/zinou/colossal/ColossalAI/applications/Chat/examples/train_sft.py", line 7, in <module>
    from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset
  File "/home/steel/.local/lib/python3.10/site-packages/coati/dataset/__init__.py", line 1, in <module>
    from .prompt_dataset import PromptDataset
  File "/home/steel/.local/lib/python3.10/site-packages/coati/dataset/prompt_dataset.py", line 13, in <module>
    from colossalai.logging import get_dist_logger
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/initialize.py", line 18, in <module>
    from colossalai.amp import AMP_TYPE, convert_to_amp
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/amp/__init__.py", line 11, in <module>
    from .apex_amp import convert_to_apex_amp
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/amp/apex_amp/__init__.py", line 4, in <module>
    from .apex_amp import ApexAMPOptimizer    
from coati.dataset import DataCollatorForSupervisedDataset, SFTDataset, SupervisedDataset  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/amp/apex_amp/apex_amp.py", line 13, in <module>

  File "/home/steel/.local/lib/python3.10/site-packages/coati/dataset/__init__.py", line 1, in <module>
    from colossalai.nn.optimizer import ColossalaiOptimizer    from .prompt_dataset import PromptDataset

  File "/home/steel/.local/lib/python3.10/site-packages/coati/dataset/prompt_dataset.py", line 13, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/__init__.py", line 1, in <module>
        from ._ops import *from colossalai.logging import get_dist_logger

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/_ops/__init__.py", line 1, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/__init__.py", line 1, in <module>
        from .initialize import (from .addmm import colo_addmm

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/initialize.py", line 18, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/_ops/addmm.py", line 6, in <module>
        from colossalai.amp import AMP_TYPE, convert_to_ampfrom ._utils import GeneralTensor, Number, convert_to_colo_tensor, reduce_grad, reduce_input

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/amp/__init__.py", line 11, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/_ops/_utils.py", line 7, in <module>
    from .apex_amp import convert_to_apex_amp    from colossalai.nn.layer.utils import divide

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/__init__.py", line 1, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/amp/apex_amp/__init__.py", line 4, in <module>
        from .apex_amp import ApexAMPOptimizerfrom .colossalai_layer import *

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/amp/apex_amp/apex_amp.py", line 13, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/colossalai_layer/__init__.py", line 2, in <module>
    from colossalai.nn.optimizer import ColossalaiOptimizer
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/__init__.py", line 1, in <module>
    from .dropout import Dropout
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/colossalai_layer/dropout.py", line 5, in <module>
    from ._ops import *
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/_ops/__init__.py", line 1, in <module>
        from ..parallel_1d import *from .addmm import colo_addmm

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/parallel_1d/__init__.py", line 1, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/_ops/addmm.py", line 6, in <module>
        from .layers import (Classifier1D, Dropout1D, Embedding1D, LayerNorm1D, Linear1D, Linear1D_Col, Linear1D_Row,from ._utils import GeneralTensor, Number, convert_to_colo_tensor, reduce_grad, reduce_input

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/parallel_1d/layers.py", line 17, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/_ops/_utils.py", line 7, in <module>
        from colossalai.kernel import LayerNormfrom colossalai.nn.layer.utils import divide

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/kernel/__init__.py", line 1, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/__init__.py", line 1, in <module>
        from .cuda_native import FusedScaleMaskSoftmax, LayerNorm, MultiHeadAttentionfrom .colossalai_layer import *

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/kernel/cuda_native/__init__.py", line 1, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/colossalai_layer/__init__.py", line 2, in <module>
        from .dropout import Dropoutfrom .layer_norm import MixedFusedLayerNorm as LayerNorm

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/colossalai_layer/dropout.py", line 5, in <module>
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/kernel/cuda_native/layer_norm.py", line 12, in <module>
        from ..parallel_1d import *from colossalai.kernel.op_builder.layernorm import LayerNormBuilder

  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/parallel_1d/__init__.py", line 1, in <module>
ModuleNotFoundError:     No module named 'colossalai.kernel.op_builder'
from .layers import (Classifier1D, Dropout1D, Embedding1D, LayerNorm1D, Linear1D, Linear1D_Col, Linear1D_Row,
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/nn/layer/parallel_1d/layers.py", line 17, in <module>
    from colossalai.kernel import LayerNorm
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/kernel/__init__.py", line 1, in <module>
    from .cuda_native import FusedScaleMaskSoftmax, LayerNorm, MultiHeadAttention
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/kernel/cuda_native/__init__.py", line 1, in <module>
    from .layer_norm import MixedFusedLayerNorm as LayerNorm
  File "/home/steel/.local/lib/python3.10/site-packages/colossalai/kernel/cuda_native/layer_norm.py", line 12, in <module>
    from colossalai.kernel.op_builder.layernorm import LayerNormBuilder
ModuleNotFoundError: No module named 'colossalai.kernel.op_builder'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 4887) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/steel/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/steel/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/steel/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/steel/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/steel/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/steel/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

train_sft.py FAILED

Failures:
[1]:
  time      : 2023-05-31_19:34:09
  host      : DESKTOP-D1DE4HI.
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 4888)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

Root Cause (first observed failure):
[0]:
  time      : 2023-05-31_19:34:09
  host      : DESKTOP-D1DE4HI.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 4887)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

./train_sft.sh: line 2: --pretrain: command not found
./train_sft.sh: line 3: --model: command not found
./train_sft.sh: line 4: --strategy: command not found
./train_sft.sh: line 5: --log_interval: command not found
./train_sft.sh: line 6: --save_path: command not found
./train_sft.sh: line 7: --dataset: command not found
./train_sft.sh: line 8: --batch_size: command not found
./train_sft.sh: line 9: --accumulation_steps: command not found
./train_sft.sh: line 10: --lr: command not found
./train_sft.sh: line 11: --max_datasets_size: command not found
./train_sft.sh: line 12: --max_epochs: command not found
```

![error 1](https://github.com/hpcaitech/ColossalAI/assets/129765070/0a1ae030-c448-4edd-abdf-3b9c4bc93288)
![error 2](https://github.com/hpcaitech/ColossalAI/assets/129765070/3d9962f7-ca76-487c-a8d7-d1acb307d6f3)

### Environment

environment : python

**Comment by jiangmingyan** [comment]
can you post your script you run?
