### ISSUE TITLE
[BUG]: pytest and decorator required but missing in v0.3.0 requirements

### ISSUE THREAD

**Issue by MEllis-github** [hpcaitech/ColossalAI#3962]
### 🐛 Describe the bug

Running `colossalai check -i` in `docker.io/hpcaitech/colossalai:0.3.0` results in module-not-found errors for `pytest`. With that installed, running the command results in module-not-found errors for `decorator` (below). Installing `decorator` resolves the errors.

```
======== checking colossal ai ========
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/fabric/connection.py", line 7, in <module>
    from invoke.vendor.decorator import decorator
ModuleNotFoundError: No module named 'invoke.vendor.decorator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/opt/conda/lib/python3.9/site-packages/colossalai/cli/__init__.py", line 1, in <module>
    from .cli import cli
  File "/opt/conda/lib/python3.9/site-packages/colossalai/cli/cli.py", line 5, in <module>
    from .launcher import run
  File "/opt/conda/lib/python3.9/site-packages/colossalai/cli/launcher/__init__.py", line 5, in <module>
    from .run import launch_multi_processes
  File "/opt/conda/lib/python3.9/site-packages/colossalai/cli/launcher/run.py", line 12, in <module>
    from .multinode_runner import MultiNodeRunner
  File "/opt/conda/lib/python3.9/site-packages/colossalai/cli/launcher/multinode_runner.py", line 5, in <module>
    import fabric
  File "/opt/conda/lib/python3.9/site-packages/fabric/__init__.py", line 3, in <module>
    from .connection import Config, Connection
  File "/opt/conda/lib/python3.9/site-packages/fabric/connection.py", line 9, in <module>
    from decorator import decorator
ModuleNotFoundError: No module named 'decorator'
```

```
Collecting decorator
  Downloading decorator-5.1.1-py3-none-any.whl (9.1 kB)
Installing collected packages: decorator
Successfully installed decorator-5.1.1
======== checking colossal ai ========
#### Installation Report ####

------------ Environment ------------
Colossal-AI version: 0.3.0
PyTorch version: 1.12.1
System CUDA version: 11.3
CUDA version required by PyTorch: 11.3

```

### Environment

docker.io/hpcaitech/colossalai:0.3.0

**Comment by FrankLeeeee** [comment]
Fixed by #4087
