### ISSUE TITLE
txt2img error [BUG]: 

### ISSUE THREAD

**Issue by wangmiaowei** [hpcaitech/ColossalAI#4007]
### 🐛 Describe the bug

bash scripts/txt2img.sh

===================================BUG REPORT===================================
Welcome to bitsandbytes. For bug reports, please run

python -m bitsandbytes

 and submit this information together with your error trace to: https://github.com/TimDettmers/bitsandbytes/issues
================================================================================
bin /opt/conda/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda113.so
/opt/conda/lib/python3.7/site-packages/bitsandbytes/cuda_setup/main.py:149: UserWarning: Found duplicate ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] files: {PosixPath('/opt/conda/lib/libcudart.so'), PosixPath('/opt/conda/lib/libcudart.so.11.0')}.. We'll flip a coin and try one of these, in order to fail forward.
Either way, this might cause trouble in the future:
If you get `CUDA error: invalid device function` errors, the above might be the cause and the solution is to make sure only one ['libcudart.so', 'libcudart.so.11.0', 'libcudart.so.12.0'] in the paths that we search based on your env.
  warn(msg)
CUDA SETUP: CUDA runtime path found: /opt/conda/lib/libcudart.so
CUDA SETUP: Highest compute capability among GPUs detected: 8.6
CUDA SETUP: Detected CUDA version 113
CUDA SETUP: Loading binary /opt/conda/lib/python3.7/site-packages/bitsandbytes/libbitsandbytes_cuda113.so...
Global seed set to 42
Loading model from /root/programs_wmw/sd_train/ColossalAI-main/examples/images/diffusion/tmp/2023-06-15T17-53-44_train_colossalai_teyvat/checkpoints/trainstep_checkpoints/epoch=000095-step=000010000.ckpt
Global Step: 10000
Traceback (most recent call last):
  File "scripts/txt2img.py", line 306, in <module>
    main(opt)
  File "scripts/txt2img.py", line 200, in main
    model = load_model_from_config(config, f"{opt.ckpt}")
  File "scripts/txt2img.py", line 39, in load_model_from_config
    model = instantiate_from_config(config.model)
  File "/root/programs_wmw/sd_train/ColossalAI-main/examples/images/diffusion/ldm/util.py", line 78, in instantiate_from_config
    raise KeyError("Expected key `target` to instantiate.")
KeyError: 'Expected key `target` to instantiate.'

**Comment by jiangmingyan** [comment]
can you show the config.yaml, please check there has "target" in config.

**Comment by tiandiao123** [comment]
@wangmiaowei can you re-try text-image using this branch? https://github.com/hpcaitech/ColossalAI/tree/feature/stable-diffusion/applications/stable-diffusion/text_img2img we are updating to newer version. If you have some question, you can contact me @tiandiao123

**Comment by Youngon** [comment]
> @wangmiaowei can you re-try text-image using this branch? https://github.com/hpcaitech/ColossalAI/tree/feature/stable-diffusion/applications/stable-diffusion/text_img2img we are updating to newer version. If you have some question, you can contact me @tiandiao123

does this error be solved? I meet the same issue, when finish trainning, can not do inference.
