### ISSUE TITLE
[BUG]: Multi-GPU train error

### ISSUE THREAD

**Issue by barryhippo** [hpcaitech/ColossalAI#4009]
### My Script is blow
```
colossalai run --nproc_per_node=3 --host GPU03,GPU01 --master_addr GPU03 train_sft.py \
    --pretrain "/data/model/llama-7b-hf/" \
    --model 'llama' \
    --strategy naive \
    --log_interval 10 \
    --save_path  /data/model/Coati-7B \
    --dataset /data/train/ColossalAi/instinwild_ch.json \
    --batch_size 1 \
    --accumulation_steps 8 \
    --lr 2e-5 \
    --max_datasets_size 512 \
    --max_epochs 1 \
    --lora_rank 16 \
    --grad_checkpoint
```

**Password-free login for GPU01 and GPU03**

### I got the error:
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[E socket.cpp:860] [c10d] The client socket has timed out after 60s while trying to connect to (GPU03, 29500).
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 155, in _create_tcp_store
    store = TCPStore(
TimeoutError: The client socket has timed out after 60s while trying to connect to (GPU03, 29500).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 220, in launch_agent
    rdzv_handler=rdzv_registry.get_rendezvous_handler(rdzv_parameters),
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 65, in get_rendezvous_handler
    return handler_registry.create_handler(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/api.py", line 253, in create_handler
    handler = creator(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 36, in _create_c10d_handler
    backend, store = create_backend(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 250, in create_backend
    store = _create_tcp_store(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 175, in _create_tcp_store
    raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
[E socket.cpp:860] [c10d] The client socket has timed out after 60s while trying to connect to (GPU03, 29500).
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 155, in _create_tcp_store
    store = TCPStore(
TimeoutError: The client socket has timed out after 60s while trying to connect to (GPU03, 29500).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 220, in launch_agent
    rdzv_handler=rdzv_registry.get_rendezvous_handler(rdzv_parameters),
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 65, in get_rendezvous_handler
    return handler_registry.create_handler(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/api.py", line 253, in create_handler
    handler = creator(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 36, in _create_c10d_handler
    backend, store = create_backend(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 250, in create_backend
    store = _create_tcp_store(params)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 175, in _create_tcp_store
    raise RendezvousConnectionError(
torch.distributed.elastic.rendezvous.api.RendezvousConnectionError: The connection to the C10d store has failed. See inner exception for details.
Error: failed to run torchrun --nproc_per_node=3 --nnodes=2 --node_rank=1 --rdzv_backend=c10d --rdzv_endpoint=GPU03:29500 --rdzv_id=colossalai-default-job train_sft.py --pretrain /data/model/llama-7b-hf/ --model llama --strategy naive --log_interval 10 --save_path /data/model/Coati-7B --dataset /data/train/ColossalAi/instinwild_ch.json --batch_size 1 --accumulation_steps 8 --lr 2e-5 --max_datasets_size 512 --max_epochs 1 --lora_rank 16 --grad_checkpoint on GPU01, is localhost: False, exception: Encountered a bad command exit code!

Command: 'cd /data/train/ColossalAi && export XDG_SESSION_ID="70" HOSTNAME="localhost.localdomain" SHELL="/bin/bash" TERM="xterm-256color" HISTSIZE="1000" SSH_CLIENT="10.135.158.60 54795 22" CONDA_SHLVL="1" CONDA_PROMPT_MODIFIER="(base) " SSH_TTY="/dev/pts/0" USER="root" LS_COLORS="rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:" CONDA_EXE="/root/miniconda3/bin/conda" PATH="/root/miniconda3/bin:/root/miniconda3/condabin:/usr/local/cuda-11.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin" MAIL="/var/spool/mail/root" _="/root/miniconda3/bin/colossalai" CONDA_PREFIX="/root/miniconda3" PWD="/data/train/ColossalAi" LANG="zh_CN.UTF-8" HISTCONTROL="ignoredups" HOME="/root" SHLVL="2" LOGNAME="root" CONDA_PYTHON_EXE="/root/miniconda3/bin/python" SSH_CONNECTION="10.135.158.60 54795 10.10.1.220 22" LESSOPEN="||/usr/bin/lesspipe.sh %s" CONDA_DEFAULT_ENV="base" XDG_RUNTIME_DIR="/run/user/0" && torchrun --nproc_per_node=3 --nnodes=2 --node_rank=1 --rdzv_backend=c10d --rdzv_endpoint=GPU03:29500 --rdzv_id=colossalai-default-job train_sft.py --pretrain /data/model/llama-7b-hf/ --model llama --strategy naive --log_interval 10 --save_path /data/model/Coati-7B --dataset /data/train/ColossalAi/instinwild_ch.json --batch_size 1 --accumulation_steps 8 --lr 2e-5 --max_datasets_size 512 --max_epochs 1 --lora_rank 16 --grad_checkpoint'

Exit code: 1

Stdout: already printed

Stderr: already printed


Error: failed to run torchrun --nproc_per_node=3 --nnodes=2 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=GPU03:29500 --rdzv_id=colossalai-default-job train_sft.py --pretrain /data/model/llama-7b-hf/ --model llama --strategy naive --log_interval 10 --save_path /data/model/Coati-7B --dataset /data/train/ColossalAi/instinwild_ch.json --batch_size 1 --accumulation_steps 8 --lr 2e-5 --max_datasets_size 512 --max_epochs 1 --lora_rank 16 --grad_checkpoint on GPU03, is localhost: False, exception: Encountered a bad command exit code!

Command: 'cd /data/train/ColossalAi && export XDG_SESSION_ID="70" HOSTNAME="localhost.localdomain" SHELL="/bin/bash" TERM="xterm-256color" HISTSIZE="1000" SSH_CLIENT="10.135.158.60 54795 22" CONDA_SHLVL="1" CONDA_PROMPT_MODIFIER="(base) " SSH_TTY="/dev/pts/0" USER="root" LS_COLORS="rs=0:di=38;5;27:ln=38;5;51:mh=44;38;5;15:pi=40;38;5;11:so=38;5;13:do=38;5;5:bd=48;5;232;38;5;11:cd=48;5;232;38;5;3:or=48;5;232;38;5;9:mi=05;48;5;232;38;5;15:su=48;5;196;38;5;15:sg=48;5;11;38;5;16:ca=48;5;196;38;5;226:tw=48;5;10;38;5;16:ow=48;5;10;38;5;21:st=48;5;21;38;5;15:ex=38;5;34:*.tar=38;5;9:*.tgz=38;5;9:*.arc=38;5;9:*.arj=38;5;9:*.taz=38;5;9:*.lha=38;5;9:*.lz4=38;5;9:*.lzh=38;5;9:*.lzma=38;5;9:*.tlz=38;5;9:*.txz=38;5;9:*.tzo=38;5;9:*.t7z=38;5;9:*.zip=38;5;9:*.z=38;5;9:*.Z=38;5;9:*.dz=38;5;9:*.gz=38;5;9:*.lrz=38;5;9:*.lz=38;5;9:*.lzo=38;5;9:*.xz=38;5;9:*.bz2=38;5;9:*.bz=38;5;9:*.tbz=38;5;9:*.tbz2=38;5;9:*.tz=38;5;9:*.deb=38;5;9:*.rpm=38;5;9:*.jar=38;5;9:*.war=38;5;9:*.ear=38;5;9:*.sar=38;5;9:*.rar=38;5;9:*.alz=38;5;9:*.ace=38;5;9:*.zoo=38;5;9:*.cpio=38;5;9:*.7z=38;5;9:*.rz=38;5;9:*.cab=38;5;9:*.jpg=38;5;13:*.jpeg=38;5;13:*.gif=38;5;13:*.bmp=38;5;13:*.pbm=38;5;13:*.pgm=38;5;13:*.ppm=38;5;13:*.tga=38;5;13:*.xbm=38;5;13:*.xpm=38;5;13:*.tif=38;5;13:*.tiff=38;5;13:*.png=38;5;13:*.svg=38;5;13:*.svgz=38;5;13:*.mng=38;5;13:*.pcx=38;5;13:*.mov=38;5;13:*.mpg=38;5;13:*.mpeg=38;5;13:*.m2v=38;5;13:*.mkv=38;5;13:*.webm=38;5;13:*.ogm=38;5;13:*.mp4=38;5;13:*.m4v=38;5;13:*.mp4v=38;5;13:*.vob=38;5;13:*.qt=38;5;13:*.nuv=38;5;13:*.wmv=38;5;13:*.asf=38;5;13:*.rm=38;5;13:*.rmvb=38;5;13:*.flc=38;5;13:*.avi=38;5;13:*.fli=38;5;13:*.flv=38;5;13:*.gl=38;5;13:*.dl=38;5;13:*.xcf=38;5;13:*.xwd=38;5;13:*.yuv=38;5;13:*.cgm=38;5;13:*.emf=38;5;13:*.axv=38;5;13:*.anx=38;5;13:*.ogv=38;5;13:*.ogx=38;5;13:*.aac=38;5;45:*.au=38;5;45:*.flac=38;5;45:*.mid=38;5;45:*.midi=38;5;45:*.mka=38;5;45:*.mp3=38;5;45:*.mpc=38;5;45:*.ogg=38;5;45:*.ra=38;5;45:*.wav=38;5;45:*.axa=38;5;45:*.oga=38;5;45:*.spx=38;5;45:*.xspf=38;5;45:" CONDA_EXE="/root/miniconda3/bin/conda" PATH="/root/miniconda3/bin:/root/miniconda3/condabin:/usr/local/cuda-11.7/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin" MAIL="/var/spool/mail/root" _="/root/miniconda3/bin/colossalai" CONDA_PREFIX="/root/miniconda3" PWD="/data/train/ColossalAi" LANG="zh_CN.UTF-8" HISTCONTROL="ignoredups" HOME="/root" SHLVL="2" LOGNAME="root" CONDA_PYTHON_EXE="/root/miniconda3/bin/python" SSH_CONNECTION="10.135.158.60 54795 10.10.1.220 22" LESSOPEN="||/usr/bin/lesspipe.sh %s" CONDA_DEFAULT_ENV="base" XDG_RUNTIME_DIR="/run/user/0" && torchrun --nproc_per_node=3 --nnodes=2 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=GPU03:29500 --rdzv_id=colossalai-default-job train_sft.py --pretrain /data/model/llama-7b-hf/ --model llama --strategy naive --log_interval 10 --save_path /data/model/Coati-7B --dataset /data/train/ColossalAi/instinwild_ch.json --batch_size 1 --accumulation_steps 8 --lr 2e-5 --max_datasets_size 512 --max_epochs 1 --lora_rank 16 --grad_checkpoint'

Exit code: 1

Stdout: already printed

Stderr: already printed



====== Training on All Nodes =====
GPU03: failure
GPU01: failure

====== Stopping All Nodes =====
GPU03: finish
GPU01: finish
```

### Environment

------------ Environment ------------
Colossal-AI version: 0.3.0
PyTorch version: 1.13.1
System CUDA version: 11.7
CUDA version required by PyTorch: 11.7

------------ CUDA Extensions AOT Compilation ------------
Found AOT CUDA Extension: ✓
PyTorch version used for AOT compilation: N/A
CUDA version used for AOT compilation: N/A

------------ Compatibility ------------
PyTorch version match: N/A
System and PyTorch CUDA version match: ✓
System and Colossal-AI CUDA version match: N/A

**Comment by jiangmingyan** [comment]
'Strategy naive' can't use Multiple GPUs.

**Comment by barryhippo** [comment]
I have try 'strategy' with 'colossalai_zero2_cpu'、'ddp'、'colossalai_zero2'

also get the timeout error

TimeoutError: The client socket has timed out after 60s while trying to connect to (GPU03, 29500).

**Comment by FrankLeeeee** [comment]
I suspect that this might your DNS problem. Can you try to set master address as IP instead of hostname?

**Comment by barryhippo** [comment]
> 

**My /etc/hosts is:**
```
10.10.1.186 GPU01
10.10.1.188 GPU02
10.10.1.220 GPU03
```

master address set to 10.10.1.220   also got the timeout error

**Comment by FrankLeeeee** [comment]
That's strange. Is passwordless ssh enabled between the nodes?

**Comment by barryhippo** [comment]
> 

yes  passwordless ssh enabled!

**Comment by FrankLeeeee** [comment]
Ok, an alternative is to try to execute `torchrun` on two nodes separately. `colossalai run` is a wrapper for `torchrun` to execute multi-node training with one command, however, since it does not really work on your machine, one possible way to debug is to run `torchrun` on your node to see whether the root cause arises from colossalai.

```
# GPU 03
torchrun --nnodes 2 --node_rank 0 --nproc_per_node=3 --master_addr GPU03 --rdzv_backend=c10d train_sft.py

# on GPU 01
torchrun --nnodes 2 --node_rank 1 --nproc_per_node=3 --master_addr GPU03 --rdzv_backend=c10d train_sft.py
```

**Comment by barryhippo** [comment]
I tray this command:
```
#GPU 03
torchrun --nproc_per_node=3 --nnodes=2 --node_rank=0 --rdzv_backend=c10d --master_addr GPU03 train_sft.py  ...

#GPU 01
torchrun --nproc_per_node=3 --nnodes=2 --node_rank=1 --rdzv_backend=c10d --master_addr GPU03 train_sft.py  ...
```


GPU03 and GPU01 have the same error:
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/root/miniconda3/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 844, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 678, in _initialize_workers
    self._rendezvous(worker_group)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 538, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1025, in next_rendezvous
    self._op_executor.run(join_op, deadline)
  File "/root/miniconda3/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 638, in run
    raise RendezvousTimeoutError()
torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError
```
