### ISSUE TITLE
[BUG]: [BUG] _old_init is not found in the PytorchGELUTanh, please make sure that you have imported PytorchGELUTanh before entering the context.

### ISSUE THREAD

**Issue by zedong-mt** [hpcaitech/ColossalAI#4051]
### 🐛 Describe the bug

Traceback (most recent call last):
  File "./train.py", line 252, in <module>
    main()
  File "./train.py", line 199, in main
    model, plugin = create_cai_model(args)
  File "./train.py", line 106, in create_cai_model
    model = build_model(args)
  File "/usr/local/lib/python3.8/dist-packages/colossalai/utils/model/utils.py", line 98, in __exit__
    substitute_init_recursively(torch.nn.modules.module.Module, _disable_class, set())
  File "/usr/local/lib/python3.8/dist-packages/colossalai/utils/model/utils.py", line 15, in substitute_init_recursively
    func(subcls)
  File "/usr/local/lib/python3.8/dist-packages/colossalai/utils/model/utils.py", line 92, in _disable_class
    raise AttributeError(
AttributeError: _old_init is not found in the PytorchGELUTanh, please make sure that you have imported PytorchGELUTanh before entering the context.

**Comment by zedong-mt** [comment]
version: 0.3.0,  latest master code

**Comment by jiangmingyan** [comment]
As indicated by the error message, please make sure that you have imported PytorchGELUTanh before entering the context.

**Comment by zedong-mt** [comment]
thanks, I have solved it already
