### ISSUE TITLE
[BUG]: TypeError: Booster.boost() missing 1 required positional argument: 'optimizer'

### ISSUE THREAD

**Issue by SeekPoint** [hpcaitech/ColossalAI#4232]
### 🐛 Describe the bug

```bash
(gh_ColossalAI-chat) amd01@mz32-01:~/llm_dev/ColossalAI/applications/Chat/examples$ bash train_prompts.sh
GPU Memory Usage:
     0  1 MiB
     1  1 MiB
Now CUDA_VISIBLE_DEVICES is set to:
CUDA_VISIBLE_DEVICES=0,1
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
[07/13/23 10:36:40] INFO     colossalai - colossalai - INFO: /home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/context/parallel_context.py:522 set_device
                    INFO     colossalai - colossalai - INFO: process rank 1 is bound to device 1
[07/13/23 10:36:40] INFO     colossalai - colossalai - INFO: /home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/context/parallel_context.py:522 set_device
                    INFO     colossalai - colossalai - INFO: process rank 0 is bound to device 0
[07/13/23 10:36:41] INFO     colossalai - colossalai - INFO: /home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/context/parallel_context.py:558 set_seed
[07/13/23 10:36:41] INFO     colossalai - colossalai - INFO: /home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/context/parallel_context.py:558 set_seed
                    INFO     colossalai - colossalai - INFO: initialized seed on rank 0, numpy: 42, python random: 42, ParallelMode.DATA: 42, ParallelMode.TENSOR: 42,the default parallel seed is ParallelMode.DATA.
                    INFO     colossalai - colossalai - INFO: initialized seed on rank 1, numpy: 42, python random: 42, ParallelMode.DATA: 42, ParallelMode.TENSOR: 42,the default parallel seed is ParallelMode.DATA.
/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/booster/booster.py:69: UserWarning: The plugin will control the accelerator, so the device argument will be ignored.
  warnings.warn('The plugin will control the accelerator, so the device argument will be ignored.')
/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/booster/booster.py:75: UserWarning: The plugin will control the precision, so the mixed_precision argument will be ignored.
  warnings.warn('The plugin will control the precision, so the mixed_precision argument will be ignored.')
                    INFO     colossalai - colossalai - INFO: /home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/initialize.py:115 launch
                    INFO     colossalai - colossalai - INFO: Distributed environment is initialized, data parallel size: 2, pipeline parallel size: 1, tensor parallel size: 1
/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/booster/booster.py:69: UserWarning: The plugin will control the accelerator, so the device argument will be ignored.
  warnings.warn('The plugin will control the accelerator, so the device argument will be ignored.')
/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/colossalai/booster/booster.py:75: UserWarning: The plugin will control the precision, so the mixed_precision argument will be ignored.
  warnings.warn('The plugin will control the precision, so the mixed_precision argument will be ignored.')
[07/13/23 10:36:59] INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/prompt_dataset.py:30 __init__
                    INFO     colossalai - colossalai - INFO: Loading data...
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/prompt_dataset.py:32 __init__
                    INFO     colossalai - colossalai - INFO: Loaded 51504 examples.
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/prompt_dataset.py:35 __init__
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 16384 examples.
[07/13/23 10:37:06] INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:121 __init__
                    INFO     colossalai - colossalai - INFO: Loading data...
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:123 __init__
                    INFO     colossalai - colossalai - INFO: Loaded 52191 examples.
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:126 __init__
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 16384 examples.
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:129 __init__
                    INFO     colossalai - colossalai - INFO: Formatting inputs...
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:137 __init__
                    INFO     colossalai - colossalai - INFO: Tokenizing inputs... This may take some time...
[07/13/23 10:37:09] INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/prompt_dataset.py:30 __init__
                    INFO     colossalai - colossalai - INFO: Loading data...
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/prompt_dataset.py:32 __init__
                    INFO     colossalai - colossalai - INFO: Loaded 51504 examples.
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/prompt_dataset.py:35 __init__
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 16384 examples.
[07/13/23 10:37:16] INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:121 __init__
                    INFO     colossalai - colossalai - INFO: Loading data...
[07/13/23 10:37:17] INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:123 __init__
                    INFO     colossalai - colossalai - INFO: Loaded 52191 examples.
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:126 __init__
                    INFO     colossalai - colossalai - INFO: Limiting dataset to 16384 examples.
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:129 __init__
                    INFO     colossalai - colossalai - INFO: Formatting inputs...
                    INFO     colossalai - colossalai - INFO: /home/amd01/llm_dev/ColossalAI/applications/Chat/coati/dataset/sft_dataset.py:137 __init__
                    INFO     colossalai - colossalai - INFO: Tokenizing inputs... This may take some time...
Traceback (most recent call last):
  File "/home/amd01/llm_dev/ColossalAI/applications/Chat/examples/train_prompts.py", line 233, in <module>
    main(args)
  File "/home/amd01/llm_dev/ColossalAI/applications/Chat/examples/train_prompts.py", line 167, in main
    strategy.prepare((actor, actor_optim), (critic, critic_optim), reward_model, initial_model)
  File "/home/amd01/llm_dev/ColossalAI/applications/Chat/coati/trainer/strategies/base.py", line 75, in prepare
    model, *_ = self.booster.boost(arg)
TypeError: Booster.boost() missing 1 required positional argument: 'optimizer'
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3935 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 3934) of binary: /home/amd01/anaconda3/envs/gh_ColossalAI-chat/bin/python
Traceback (most recent call last):
  File "/home/amd01/anaconda3/envs/gh_ColossalAI-chat/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/amd01/anaconda3/envs/gh_ColossalAI-chat/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_prompts.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-13_10:37:31
  host      : mz32-01
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 3934)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
(gh_ColossalAI-chat) amd01@mz32-01:~/llm_dev/ColossalAI/applications/Chat/examples$
```

**Comment by CWHer** [comment]
Do you use the latest version of `colossal-ai` (i.e., git clone repo)? 
We have updated `Booster` class since the last release.

**Comment by SeekPoint** [comment]
yes, I had my re
