### ISSUE TITLE
[BUG]: 使用RedPajama-Data-1T-Sample数据集训练llama-7b模型报错

### ISSUE THREAD

**Issue by Maxhyl** [hpcaitech/ColossalAI#4289]
### 🐛 Describe the bug

运行命令：colossalai run --nproc_per_node 8 --master_port 8822 --hostfile /home/edcuser/models/ColossalAI/examples/language/llama/hostfile.txt  --master_addr 192.168.30.3 pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin "gemini" -l 512 -g -b 4 -a 后得到如下结果：

`WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "/home/edcuser/.conda/envs/torch113/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 220, in launch_agent
    rdzv_handler=rdzv_registry.get_rendezvous_handler(rdzv_parameters),
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 65, in get_rendezvous_handler
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Fatal Python error:     return handler_registry.create_handler(params)
Aborted

  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/api.py", line 253, in create_handler
Thread 0x00007fcdcbd3f740 (most recent call first):
  <no Python frame>
    handler = creator(params)
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 36, in _create_c10d_handler
    backend, store = create_backend(params)
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 254, in create_backend
    backend = C10dRendezvousBackend(store, params.run_id)
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 64, in __init__
    self._call_store("compare_set", self._key, "", self._NULL_SENTINEL)
  File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 113, in _call_store

Extension modules: torch._C, torch._C._fft, torch._C._linalg    return getattr(self._store, store_op)(*args, **kwargs)
MemoryError: std::bad_alloc
, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 20)
/bin/bash: line 1: 43031 Aborted                 (core dumped) torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=192.168.30.3:8822 --rdzv_id=colossalai-default-job pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin gemini -l 512 -g -b 4 -a
Error: failed to run torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=192.168.30.3:8822 --rdzv_id=colossalai-default-job pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin gemini -l 512 -g -b 4 -a on localhost, is localhost: True, exception: Encountered a bad command exit code!

Command: 'cd /home/edcuser/models/ColossalAI/examples/language/llama && export XDG_SESSION_ID="12933" HOSTNAME="localhost.localdomain" TERM="xterm" SHELL="/bin/bash" HISTSIZE="1000" SSH_CLIENT="192.168.30.1 33808 8822" CONDA_SHLVL="2" CONDA_PROMPT_MODIFIER="(torch113) " OLDPWD="/home/edcuser/models/ColossalAI/examples/language/llama/benchmark_7B" SSH_TTY="/dev/pts/2" CUDA_HOME="/usr/local/cuda-11.7" USER="edcuser" LD_LIBRARY_PATH="/usr/local/cuda-11.7/lib64:/usr/local/cuda/lib64:" LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.axa=01;36:*.oga=01;36:*.spx=01;36:*.xspf=01;36:" CONDA_EXE="/opt/anaconda3/bin/conda" CONDA_PREFIX_1="/opt/anaconda3" MAIL="/var/spool/mail/edcuser" PATH="/usr/local/cuda-11.7/bin:/home/edcuser/.conda/envs/torch113/bin:/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/home/edcuser/.local/bin:/home/edcuser/bin" CONDA_PREFIX="/home/edcuser/.conda/envs/torch113" PWD="/home/edcuser/models/ColossalAI/examples/language/llama" LANG="en_US.UTF-8" MODULEPATH="/usr/share/Modules/modulefiles:/etc/modulefiles" HISTCONTROL="ignoredups" SHLVL="1" HOME="/home/edcuser" CONDA_PYTHON_EXE="/opt/anaconda3/bin/python" LOGNAME="edcuser" XDG_DATA_DIRS="/home/edcuser/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share" SSH_CONNECTION="192.168.30.1 33808 192.168.30.3 8822" MODULESHOME="/usr/share/Modules" CONDA_DEFAULT_ENV="torch113" LESSOPEN="||/usr/bin/lesspipe.sh %s" XDG_RUNTIME_DIR="/run/user/1001" DISPLAY="localhost:11.0" _="/home/edcuser/.conda/envs/torch113/bin/colossalai" && torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=192.168.30.3:8822 --rdzv_id=colossalai-default-job pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin gemini -l 512 -g -b 4 -a'

Exit code: 134

Stdout: already printed

Stderr: already printed

====== Training on All Nodes =====
localhost: failure

====== Stopping All Nodes =====
localhost: finish
`

### Environment

python 3.10
cuda 117
pytorch 1.13.0
colossalai 0.3.0
8*A100

**Comment by Maxhyl** [comment]
服务器内存是够的
![image](https://github.com/hpcaitech/ColossalAI/assets/49184062/c073b38e-1cbe-462f-8914-7a929d0b590e)

**Comment by flybird11111** [comment]
> ### 🐛 Describe the bug
> 运行命令：colossalai run --nproc_per_node 8 --master_port 8822 --hostfile /home/edcuser/models/ColossalAI/examples/language/llama/hostfile.txt --master_addr 192.168.30.3 pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin "gemini" -l 512 -g -b 4 -a 后得到如下结果：
> 
> `WARNING:torch.distributed.run:
> 
> Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
> 
> Traceback (most recent call last): File "/home/edcuser/.conda/envs/torch113/bin/torchrun", line 8, in sys.exit(main()) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/**init**.py", line 346, in wrapper return f(*args, **kwargs) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main run(args) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run elastic_launch( File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 220, in launch_agent rdzv_handler=rdzv_registry.get_rendezvous_handler(rdzv_parameters), File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 65, in get_rendezvous_handler terminate called after throwing an instance of 'std::bad_alloc' what(): std::bad_alloc Fatal Python error: return handler_registry.create_handler(params) Aborted
> 
> File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/api.py", line 253, in create_handler Thread 0x00007fcdcbd3f740 (most recent call first): handler = creator(params) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/registry.py", line 36, in _create_c10d_handler backend, store = create_backend(params) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 254, in create_backend backend = C10dRendezvousBackend(store, params.run_id) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 64, in **init** self._call_store("compare_set", self._key, "", self._NULL_SENTINEL) File "/home/edcuser/.conda/envs/torch113/lib/python3.10/site-packages/torch/distributed/elastic/rendezvous/c10d_rendezvous_backend.py", line 113, in _call_store
> 
> Extension modules: torch._C, torch._C._fft, torch._C._linalg return getattr(self._store, store_op)(*args, **kwargs) MemoryError: std::bad_alloc , torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator (total: 20) /bin/bash: line 1: 43031 Aborted (core dumped) torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=192.168.30.3:8822 --rdzv_id=colossalai-default-job pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin gemini -l 512 -g -b 4 -a Error: failed to run torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=192.168.30.3:8822 --rdzv_id=colossalai-default-job pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin gemini -l 512 -g -b 4 -a on localhost, is localhost: True, exception: Encountered a bad command exit code!
> 
> Command: 'cd /home/edcuser/models/ColossalAI/examples/language/llama && export XDG_SESSION_ID="12933" HOSTNAME="localhost.localdomain" TERM="xterm" SHELL="/bin/bash" HISTSIZE="1000" SSH_CLIENT="192.168.30.1 33808 8822" CONDA_SHLVL="2" CONDA_PROMPT_MODIFIER="(torch113) " OLDPWD="/home/edcuser/models/ColossalAI/examples/language/llama/benchmark_7B" SSH_TTY="/dev/pts/2" CUDA_HOME="/usr/local/cuda-11.7" USER="edcuser" LD_LIBRARY_PATH="/usr/local/cuda-11.7/lib64:/usr/local/cuda/lib64:" LS_COLORS="rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;05;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:_.tar=01;31:_.tgz=01;31:_.arc=01;31:_.arj=01;31:_.taz=01;31:_.lha=01;31:_.lz4=01;31:_.lzh=01;31:_.lzma=01;31:_.tlz=01;31:_.txz=01;31:_.tzo=01;31:_.t7z=01;31:_.zip=01;31:_.z=01;31:_.Z=01;31:_.dz=01;31:_.gz=01;31:_.lrz=01;31:_.lz=01;31:_.lzo=01;31:_.xz=01;31:_.bz2=01;31:_.bz=01;31:_.tbz=01;31:_.tbz2=01;31:_.tz=01;31:_.deb=01;31:_.rpm=01;31:_.jar=01;31:_.war=01;31:_.ear=01;31:_.sar=01;31:_.rar=01;31:_.alz=01;31:_.ace=01;31:_.zoo=01;31:_.cpio=01;31:_.7z=01;31:_.rz=01;31:_.cab=01;31:_.jpg=01;35:_.jpeg=01;35:_.gif=01;35:_.bmp=01;35:_.pbm=01;35:_.pgm=01;35:_.ppm=01;35:_.tga=01;35:_.xbm=01;35:_.xpm=01;35:_.tif=01;35:_.tiff=01;35:_.png=01;35:_.svg=01;35:_.svgz=01;35:_.mng=01;35:_.pcx=01;35:_.mov=01;35:_.mpg=01;35:_.mpeg=01;35:_.m2v=01;35:_.mkv=01;35:_.webm=01;35:_.ogm=01;35:_.mp4=01;35:_.m4v=01;35:_.mp4v=01;35:_.vob=01;35:_.qt=01;35:_.nuv=01;35:_.wmv=01;35:_.asf=01;35:_.rm=01;35:_.rmvb=01;35:_.flc=01;35:_.avi=01;35:_.fli=01;35:_.flv=01;35:_.gl=01;35:_.dl=01;35:_.xcf=01;35:_.xwd=01;35:_.yuv=01;35:_.cgm=01;35:_.emf=01;35:_.axv=01;35:_.anx=01;35:_.ogv=01;35:_.ogx=01;35:_.aac=01;36:_.au=01;36:_.flac=01;36:_.mid=01;36:_.midi=01;36:_.mka=01;36:_.mp3=01;36:_.mpc=01;36:_.ogg=01;36:_.ra=01;36:_.wav=01;36:_.axa=01;36:_.oga=01;36:_.spx=01;36:*.xspf=01;36:" CONDA_EXE="/opt/anaconda3/bin/conda" CONDA_PREFIX_1="/opt/anaconda3" MAIL="/var/spool/mail/edcuser" PATH="/usr/local/cuda-11.7/bin:/home/edcuser/.conda/envs/torch113/bin:/opt/anaconda3/condabin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/cuda/bin:/home/edcuser/.local/bin:/home/edcuser/bin" CONDA_PREFIX="/home/edcuser/.conda/envs/torch113" PWD="/home/edcuser/models/ColossalAI/examples/language/llama" LANG="en_US.UTF-8" MODULEPATH="/usr/share/Modules/modulefiles:/etc/modulefiles" HISTCONTROL="ignoredups" SHLVL="1" HOME="/home/edcuser" CONDA_PYTHON_EXE="/opt/anaconda3/bin/python" LOGNAME="edcuser" XDG_DATA_DIRS="/home/edcuser/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share" SSH_CONNECTION="192.168.30.1 33808 192.168.30.3 8822" MODULESHOME="/usr/share/Modules" CONDA_DEFAULT_ENV="torch113" LESSOPEN="||/usr/bin/lesspipe.sh %s" XDG_RUNTIME_DIR="/run/user/1001" DISPLAY="localhost:11.0" _="/home/edcuser/.conda/envs/torch113/bin/colossalai" && torchrun --nproc_per_node=8 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=192.168.30.3:8822 --rdzv_id=colossalai-default-job pretrain.py -f /data01/hyl_data/llama_models/7B -d /home/edcuser/models/new_lit_llama/data/RedPajama-Data-1T-Sample -c 7b --plugin gemini -l 512 -g -b 4 -a'
> 
> Exit code: 134
> 
> Stdout: already printed
> 
> Stderr: already printed
> 
> ====== Training on All Nodes ===== localhost: failure
> 
> ====== Stopping All Nodes ===== localhost: finish `
> 
> ### Environment
> python 3.10 cuda 117 pytorch 1.13.0 colossalai 0.3.0 8*A100
Have you tried reducing the batch size ?
