### ISSUE TITLE
[BUG]: GeminiStrategy save_pretrained CAN NOT be loaded with map_location

### ISSUE THREAD

**Issue by CWHer** [hpcaitech/ColossalAI#4292]
### 🐛 Describe the bug

These [scripts](https://github.com/CWHer/ColossalAI/tree/gemini_save_error/applications/Chat/reproduce) can be used to reproduce this error. Just run `run.sh`.

```bash
  File "load.py", line 6, in <module>
    state_dict = torch.load("bloom/pytorch_model.bin", map_location=torch.device('cpu'))
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/_tensor.py", line 60, in _rebuild_from_type_v2
    ret = func(*args)
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/_utils.py", line 153, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/_utils.py", line 147, in _rebuild_tensor
    return t.set_(storage.untyped(), storage_offset, size, stride)
RuntimeError: Trying to resize storage that is not resizable
```

**Comment by CWHer** [comment]
@ver217 @Fridge003

**Comment by ver217** [comment]
Can you make the scipt simpler and only remain save/load logic?

**Comment by CWHer** [comment]
The following are much simpler.

`save.py`
```python
import argparse

from coati.models import convert_to_lora_module
from coati.trainer.strategies import GeminiStrategy
from transformers import BloomForCausalLM, BloomTokenizerFast


def train(args):
    # configure strategy
    strategy = GeminiStrategy(placement_policy='cuda')

    # configure model
    with strategy.model_init_context():
        model = convert_to_lora_module(
            BloomForCausalLM.from_pretrained(args.pretrain),
            0
        ).half().cuda()
    tokenizer = BloomTokenizerFast.from_pretrained('bigscience/bloom-560m')

    model = strategy.prepare(model)

    # save model checkpoint after fitting on only rank0
    strategy.save_pretrained(model, path=args.save_path, only_rank0=True, tokenizer=tokenizer)


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--pretrain', type=str, default=None)
    parser.add_argument('--save_path', type=str, default='output')
    args = parser.parse_args()
    train(args)
```

`load.py`
```python
import torch

if __name__ == "__main__":
    state_dict = torch.load("bloom/pytorch_model.bin")
    print("[INFO]: torch.load w/o map_location")
    state_dict = torch.load("bloom/pytorch_model.bin", map_location=torch.device('cpu'))
    print("[INFO]: torch.load w map_location")
    # RuntimeError: Trying to resize storage that is not resizable
```

`run.sh`
```bash
set -xue

torchrun --standalone --nproc_per_node=1 save.py \
    --pretrain bigscience/bloom-560m --save_path bloom
python load.py
```

`run.sh` yields on my environment,
```bash
Traceback (most recent call last):
  File "load.py", line 6, in <module>
    state_dict = torch.load("bloom/pytorch_model.bin", map_location=torch.device('cpu'))
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/serialization.py", line 789, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/serialization.py", line 1131, in _load
    result = unpickler.load()
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/_tensor.py", line 60, in _rebuild_from_type_v2
    ret = func(*args)
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/_utils.py", line 153, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "/home/lccwh/.conda/envs/cls-ai/lib/python3.8/site-packages/torch/_utils.py", line 147, in _rebuild_tensor
    return t.set_(storage.untyped(), storage_offset, size, stride)
RuntimeError: Trying to resize storage that is not resizable
```

**Comment by Fridge003** [comment]
Please use the checkpointing methods we customized for GeminiPlugin. Original huggingface from_pretrained method isn't compatible with GeminiStrategy.
