### ISSUE TITLE
[Bug] torchrun多机多卡启动训练卡住不动

### ISSUE THREAD

**Issue by Aaricis** [hpcaitech/ColossalAI#4343]
### 🐛 Describe the bug

多机多卡训练resnet，卡住不动
启动命令：
# node1
torchrun --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="90.91.33.64" --master_port=29500  train.py -c ./ckpt-fp32

# node2
torchrun --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="90.91.33.64" --master_port=29500 train.py -c ./ckpt-fp32

node1训练卡住不动：
![image](https://github.com/hpcaitech/ColossalAI/assets/35218694/3152d7c3-5ae8-4ec7-941e-c59572cbee58)

node2超时：
```
(colossal-AI) [root@node65 resnet]# torchrun --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="90.91.33.64" --master_port=29500 train.py -c ./ckpt-fp32
[07/27/23 21:22:33] INFO     colossalai - colossalai - INFO: /root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/colossalai/context/parallel_context.py:522 set_device                                                                            
                    INFO     colossalai - colossalai - INFO: process rank 1 is bound to device 0                                                                                                                                                            
Traceback (most recent call last):
  File "/home/z00621429/ColossalAI/examples/images/resnet/train.py", line 204, in <module>
    main()
  File "/home/z00621429/ColossalAI/examples/images/resnet/train.py", line 127, in main
    colossalai.launch_from_torch(config={})
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/colossalai/initialize.py", line 218, in launch_from_torch
    launch(config=config,
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/colossalai/initialize.py", line 109, in launch
    gpc.detect_num_processes_on_current_node()
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/colossalai/context/parallel_context.py", line 92, in detect_num_processes_on_current_node
    dist.all_gather_object(hostname_list, hostname, group=self.get_group(ParallelMode.GLOBAL))
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 1649, in all_gather_object
    all_gather(object_size_list, local_size, group=group)
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 2062, in all_gather
    work = group.allgather([tensor_list], [tensor])
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1646756402876/work/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:1169, unhandled system error, NCCL version 21.0.3
ncclSystemError: System call (socket, malloc, munmap, etc) failed.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 43400) of binary: /root/miniconda3/envs/colossal-AI/bin/python
ERROR:torch.distributed.elastic.agent.server.api:Error waiting on exit barrier. Elapsed: 300.01041197776794 seconds
Traceback (most recent call last):
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/elastic/agent/server/api.py", line 906, in _exit_barrier
    store_util.barrier(
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/elastic/utils/store.py", line 67, in barrier
    synchronize(store, data, rank, world_size, key_prefix, barrier_timeout)
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/elastic/utils/store.py", line 53, in synchronize
    agent_data = get_all(store, key_prefix, world_size)
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/elastic/utils/store.py", line 31, in get_all
    data = store.get(f"{prefix}{idx}")
RuntimeError: Socket Timeout
Traceback (most recent call last):
  File "/root/miniconda3/envs/colossal-AI/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.11.0', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/run.py", line 724, in main
    run(args)
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/run.py", line 715, in run
    elastic_launch(
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/colossal-AI/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-27_21:29:01
  host      : node65
  rank      : 1 (local_rank: 0)
  exitcode  : 1 (pid: 43400)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

### Environment

CUDA=11.3
Python = 3.9.17
Pytorch = 1.11.0

**Comment by Aaricis** [comment]
I have fix this by adding NCCL environment variable:
`export NCCL_SOCKET_IFNAME=enp99s0`
