### ISSUE TITLE
[BUG]: the training procedure exit without any error logs or stuck in some steps using multi-nodes with booster api

### ISSUE THREAD

**Issue by zhangvia** [hpcaitech/ColossalAI#4353]
### 🐛 Describe the bug

i 'm using the booster api to train the stable diffusion,but the training procedure is not stable.sometimes it will stuck in some step,sometimes it will exit without any log due to recieving SIGTEM and sometimes it will training without any problem.by the way i just restart the train.sh,i didn't change the code or dataset.

have you guys encountered this problem? the exit log like below:
```shell
[07/31/23 02:53:39] INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :388 main                                          
                    INFO     colossalai - colossalai - INFO: ***** Running      
                             training *****                                     
                    INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :389 main                                          
                    INFO     colossalai - colossalai - INFO:   Num examples =   
                             77376                                              
                    INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :390 main                                          
                    INFO     colossalai - colossalai - INFO:   Num batches each 
                             epoch = 403                                        
                    INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :391 main                                          
                    INFO     colossalai - colossalai - INFO:   Num Epochs = 30  
                    INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :392 main                                          
                    INFO     colossalai - colossalai - INFO:   Instantaneous    
                             batch size per device = 16                         
                    INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :393 main                                          
                    INFO     colossalai - colossalai - INFO:   Total train batch
                             size (w. parallel, distributed & accumulation) =   
                             192                                                
                    INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :394 main                                          
                    INFO     colossalai - colossalai - INFO:   Gradient         
                             Accumulation steps = 1                             
                    INFO     colossalai - colossalai - INFO:                    
                             /media/74nvme/research/stable-diffusion/text_img2im
                             g/stable_diffusion_colossalai_trainer_sd_scripts.py
                             :395 main                                          
                    INFO     colossalai - colossalai - INFO:   Total            
                             optimization steps = 12090                         

  0%|          | 0/12090 [00:00<?, ?it/s]
Steps:   0%|          | 0/12090 [00:00
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 19 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 23 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 18) of binary: /root/miniconda3/envs/colossalai/bin/python
Traceback (most recent call last):
  File "/root/miniconda3/envs/colossalai/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.1', 'console_scripts', 'torchrun')())
  File "/root/miniconda3/envs/colossalai/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/root/miniconda3/envs/colossalai/lib/python3.9/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/root/miniconda3/envs/colossalai/lib/python3.9/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/root/miniconda3/envs/colossalai/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/miniconda3/envs/colossalai/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/media/74nvme/research/stable-diffusion/text_img2img/stable_diffusion_colossalai_trainer_sd_scripts.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-31_02:53:43
  host      : zjy3501-nuhl-master-0
  rank      : 0 (local_rank: 0)
  exitcode  : -6 (pid: 18)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 18
============================================================
```

the exitcode won't be same every time, sometimes it will be -6,-1,-9.

i hope sombody can give me some advice, and can you guys add more logs in next version?

**Comment by zhangvia** [comment]
i found the reason why the colossalai is not stable. because i'm using the cluster to run the multi-node training,and one of my cluster machine using amd cpu. however the cpu_adam.so was built on intel cpu. so when my traing mission was not using this machine,the mission running successfully, but if it used this machine,the mission crashed.

hope it can help anyone who encounters this problem.
