### ISSUE TITLE
[BUG]: pretrain llama2报错

### ISSUE THREAD

**Issue by Maxhyl** [hpcaitech/ColossalAI#4639]
### 🐛 Describe the bug

运行script/benchmark_7B/gemini.sh报错如下：

bash gemini.sh 

/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/site-packages/torch/distributed/launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See 
https://pytorch.org/docs/stable/distributed.html#launch-utility for 
further instructions

  warnings.warn(
usage: benchmark.py [-h] [-c CONFIG]
                    [-p {gemini,gemini_auto,fsdp,fsdp_cpu,3d,3d_cpu}]
                    [-b BATCH_SIZE] [-s NUM_STEPS] [-i IGNORE_STEPS] [-g]
                    [-l MAX_LENGTH] [-w WARMUP_RATIO] [-m MEMORY_LIMIT] [-x]
                    [--shard_param_frac SHARD_PARAM_FRAC]
                    [--offload_optim_frac OFFLOAD_OPTIM_FRAC]
                    [--offload_param_frac OFFLOAD_PARAM_FRAC] [--tp TP]
                    [--pp PP] [--mbs MBS] [--zero ZERO]
benchmark.py: error: unrecognized arguments: --local-rank=0
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 2) local_rank: 0 (pid: 43362) of binary: /home/edcuser/.conda/envs/pytorch_cuda117/bin/python
Traceback (most recent call last):
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/site-packages/torch/distributed/launch.py", line 196, in <module>
    main()
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/site-packages/torch/distributed/launch.py", line 192, in main
    launch(args)
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/site-packages/torch/distributed/launch.py", line 177, in launch
    run(args)
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/edcuser/.conda/envs/pytorch_cuda117/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### Environment

环境
colossalai 0.3.1
torch 2.0
cuda117
8*A100

**Comment by wangbluo** [comment]
你用的是pytorch2.0？现在colossalai还不支持2.0，本身pytorch2.0就还没有稳定下来

**Comment by ver217** [comment]
您好，llama2例子建议使用torch 1.13.1

**Comment by Maxhyl** [comment]
谢谢，使用torch 1.13.1可以正常运行。
