### ISSUE TITLE
[BUG]: llama2 num_workers=1 error

### ISSUE THREAD

**Issue by YixinSong-e** [hpcaitech/ColossalAI#4760]
### 🐛 Describe the bug

I found that during training, a lot of time is consumed by data preprocessing. I found that the pretrain.py in llama2 sets num_workers=0 for dataloader.
But when I set num_workers=1, the program connot run correctly.

How do I fix this problem?

**Comment by flybird11111** [comment]
I will take a look at this issue.

**Comment by YixinSong-e** [comment]
I change the following code:
```
dataloader = prepare_dataloader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=1,
        drop_last=True,
        collate_fn=partial(tokenize_batch_for_pretrain, tokenizer=tokenizer, max_length=args.max_length),
    )
```

**Comment by flybird11111** [comment]
What error does it raise?

**Comment by YixinSong-e** [comment]
```
Traceback (most recent call last):
  File "/mnt/hwfile/songyixin/ColossalAI/examples/language/llama2/pretrain.py", line 321, in <module>
    main()
  File "/mnt/hwfile/songyixin/ColossalAI/examples/language/llama2/pretrain.py", line 276, in main
    dataloader_iter = iter(dataloader)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 435, in __iter__
    return self._get_iterator()
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 381, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1034, in __init__
    w.start()
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/mnt/petrelfs/songyixin/miniconda3/envs/cai/lib/python3.9/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'prepare_dataloader.<locals>.seed_worker'
```

**Comment by flybird11111** [comment]
This error occurs when attempting to serialize (pickle) a local function object prepare_dataloader.<locals>.seed_worker while using a multi-process data loader (torch.utils.data.DataLoader). This function object cannot be properly serialized in a multi-process environment, leading to an AttributeError. 'seed_worker' is defined as follows:
`    def seed_worker(worker_id):
        worker_seed = seed
        np.random.seed(worker_seed)
        torch.manual_seed(worker_seed)
        random.seed(worker_seed)

    return DataLoader(dataset,
                      batch_size=batch_size,
                      sampler=sampler,
                      worker_init_fn=seed_worker,
                      drop_last=drop_last,
                      pin_memory=pin_memory,
                      num_workers=num_workers,
                      **_kwargs)`
Perhaps you can set worker_init_fn to None and see if it works.

**Comment by YixinSong-e** [comment]
OK. I will try it.

**Comment by YixinSong-e** [comment]
It's strange that  there is no error reported for num_worker here, but it  triggered an OOM (Out of Memory) error(never before).

**Comment by YixinSong-e** [comment]
You are right. This error is solved! Let me read more about this code. Thank you!!!!!
