### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by KelleyYin** [hpcaitech/ColossalAI#4875]
### 🐛 Describe the bug

[10/10/23 13:47:10] INFO     colossalai - colossalai - INFO:                    
                             /usr/local/lib/python3.8/dist-packages/colossalai/i
                             nitialize.py:63 launch                             
                    INFO     colossalai - colossalai - INFO: Distributed        
                             environment is initialized, world size: 8          
Model params: 6.28 B
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 161, in load
    op_module = self.import_op()
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 109, in import_op
    return importlib.import_module(self.prebuilt_import_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmark.py", line 223, in <module>
    main()
  File "benchmark.py", line 189, in main
    optimizer = HybridAdam(model.parameters())
  File "/usr/local/lib/python3.8/dist-packages/colossalai/nn/optimizer/hybrid_adam.py", line 76, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/colossalai/nn/optimizer/cpu_adam.py", line 79, in __init__
    cpu_adam = CPUAdamBuilder().load()
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 168, in load
    self.check_runtime_build_environment()
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 139, in check_runtime_build_environment
    check_system_pytorch_cuda_match(CUDA_HOME)
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/utils.py", line 89, in check_system_pytorch_cuda_match
    raise Exception(
Exception: [extension] Failed to build PyTorch extension because the detected CUDA version (12.0) mismatches the version that was used to compile PyTorch (11.7).Please make sure you have set the CUDA_HOME correctly and installed the correct PyTorch in https://pytorch.org/get-started/locally/ .
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 161, in load
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 161, in load
    op_module = self.import_op()
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 109, in import_op
    op_module = self.import_op()
  File "/usr/local/lib/python3.8/dist-packages/colossalai/kernel/op_builder/builder.py", line 109, in import_op
    return importlib.import_module(self.prebuilt_import_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return importlib.import_module(self.prebuilt_import_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "benchmark.py", line 223, in <module>
ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'

During handling of the above exception, another exception occurred:

### Environment

![image](https://github.com/hpcaitech/ColossalAI/assets/30852232/28d4a764-d12a-4743-8ebf-1fa19723a3d4)

**Comment by flybird11111** [comment]
Hi, could you please take a look at this issue?#4327
