### ISSUE TITLE
[BUG]: ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'

### ISSUE THREAD

**Issue by xielinzhen** [hpcaitech/ColossalAI#4986]
### 🐛 Describe the bug

I have installed colossalai with CUDA_EXT=1 pip  install colossalai

when i run bash gemini.sh in /ColossalAI/examples/language/llama2/scripts/benchmark_7B
the error is
`Model params: 6.28 B
Traceback (most recent call last):
  File "/home/pdl/anaconda3/envs/xlz/lib/python3.10/site-packages/colossalai/kernel/op_builder/builder.py", line 161, in load
    op_module = self.import_op()
  File "/home/pdl/anaconda3/envs/xlz/lib/python3.10/site-packages/colossalai/kernel/op_builder/builder.py", line 109, in import_op
    return importlib.import_module(self.prebuilt_import_path)
  File "/home/pdl/anaconda3/envs/xlz/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'colossalai._C.cpu_adam'`

### Environment

cuda_11.7  
cuDNN 8904
nccl (2, 14, 3)
python 3.10
torch 1.13.1

**Comment by JThh** [comment]
It can be due to an incorrect Python import path. Can you redo the above with prepended `PYTHONPATH=".:$PYTHONPATH"`?
