### ISSUE TITLE
[BUG]: RuntimeError: Parameter `model.norm.weight` failed at the gradient reduction

### ISSUE THREAD

**Issue by ericxsun** [hpcaitech/ColossalAI#5029]
### 🐛 Describe the bug

When using  `rms_norm` implemented in (Flash-Attn)[https://github.com/Dao-AILab/flash-attention], the forward is okay, but in backward, I got the ```RuntimeError: Parameter `model.norm.weight` failed at the gradient reduction. Some unsupported torch function is operated upon this parameter.```

The RMSNorm: 
```
from flash_attn.ops.rms_norm import rms_norm as flash_attn_rms_norm

class RMSNorm(nn.Module):
    def __init__(self, hidden_size, eps=1e-6):
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps

    def _norm(self, hidden_states):
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def forward(self, hidden_states):
        if flash_attn_rms_norm is not None and hidden_states.is_cuda:
            return flash_attn_rms_norm(hidden_states, self.weight, self.variance_epsilon)
        else:
            return self._norm(hidden_states)
```

The traceback:

```
/opt/conda/bin/python3 debug.py 
[I][unknown_node][debug.py:72:main] - args:
  warnings.warn("`config` is deprecated and will be removed soon.")
INFO     colossalai - colossalai - INFO:                    
                             /opt/conda/lib/python3.10/site-packages/colossalai/
                             initialize.py:63 launch                            
                    INFO     colossalai - colossalai - INFO: Distributed        
                             environment is initialized, world size: 1          
[I][unknown_node][debug.py:136:main] - rank 0 -> start dataloader prefetching
[I][unknown_node][debug.py:144:main] - rank 0 -> start training at epoch 0
[I][unknown_node][debug.py:148:main] - rank 0 -> first forward/backward step at epoch 0
[E][unknown_node][debug.py:173:main] - 
------------------step failed------------------
rank: 0
batch shape: torch.Size([1, 64])
------------------step failed------------------
Traceback (most recent call last):
  File "debug.py", line 193, in <module>
    main()
  File "debug.py", line 179, in main
    raise e
  File "debug.py", line 164, in main
    booster.backward(loss, optimizer)
  File "/opt/conda/lib/python3.10/site-packages/colossalai/booster/booster.py", line 167, in backward
    optimizer.backward(loss)
  File "/opt/conda/lib/python3.10/site-packages/colossalai/zero/gemini/gemini_optimizer.py", line 274, in backward
    self.module.backward(loss)
  File "/opt/conda/lib/python3.10/site-packages/colossalai/zero/gemini/gemini_ddp.py", line 317, in backward
    loss.backward()
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 478, in backward
    return handle_torch_function(
  File "/opt/conda/lib/python3.10/site-packages/torch/overrides.py", line 1551, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "/opt/conda/lib/python3.10/site-packages/colossalai/tensor/colo_tensor.py", line 81, in __torch_function__
    return backward_tensor.backward(**tensor_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/opt/conda/lib/python3.10/site-packages/colossalai/zero/gemini/gemini_ddp.py", line 332, in grad_handle
    raise RuntimeError(
RuntimeError: Parameter `model.norm.weight` failed at the gradient reduction. Some unsupported torch function is operated upon this parameter.

Process finished with exit code 1

```

### Environment

Pytorch: 2.0.1
ColossalAI: 0.3.4
Flash-attn: 2.3.3

**Comment by Fridge003** [comment]
you can refer to #4984, just not using rms_norm of flash attention would be a fast solution

**Comment by ericxsun** [comment]
> you can refer to #4984, just not using rms_norm of flash attention would be a fast solution

Thanks a lot.
