### ISSUE TITLE
[BUG]: At starting everything is good, but suddenly crash, not OOM, error log is : /aten/src/ATen/native/cuda/Indexing.cu:1141: indexSelectLargeIndex: block: [545,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

### ISSUE THREAD

**Issue by hellangleZ** [hpcaitech/ColossalAI#5039]
### 🐛 Describe the bug

At starting everything is good, but suddenly crash, not OOM, error log is : /aten/src/ATen/native/cuda/Indexing.cu:1141: indexSelectLargeIndex: block: [545,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

And also show:

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so 
the stacktrace below might be incorrect.

Below is all of the bug :

Model params: 6.28 B
A100:5588:5588 [0] NCCL INFO Bootstrap : Using eth0:192.168.0.9<0>
A100:5588:5588 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation

A100:5588:5588 [0] misc/cudawrap.cc:90 NCCL WARN Failed to find CUDA library in (null) (NCCL_CUDA_PATH=(null))
NCCL version 2.14.3+cuda11.7

A100:5589:5589 [1] misc/cudawrap.cc:90 NCCL WARN Failed to find CUDA library in (null) (NCCL_CUDA_PATH=(null))
A100:5589:5589 [1] NCCL INFO Bootstrap : Using eth0:192.168.0.9<0>
A100:5589:5589 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
A100:5588:5697 [0] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
A100:5588:5697 [0] NCCL INFO NET/Socket : Using [0]eth0:192.168.0.9<0>
A100:5588:5697 [0] NCCL INFO Using network Socket
A100:5589:5698 [1] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
A100:5589:5698 [1] NCCL INFO NET/Socket : Using [0]eth0:192.168.0.9<0>
A100:5589:5698 [1] NCCL INFO Using network Socket

A100:5590:5590 [2] misc/cudawrap.cc:90 NCCL WARN Failed to find CUDA library in (null) (NCCL_CUDA_PATH=(null))
A100:5590:5590 [2] NCCL INFO Bootstrap : Using eth0:192.168.0.9<0>
A100:5590:5590 [2] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
A100:5590:5700 [2] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
A100:5590:5700 [2] NCCL INFO NET/Socket : Using [0]eth0:192.168.0.9<0>
A100:5590:5700 [2] NCCL INFO Using network Socket

A100:5591:5591 [3] misc/cudawrap.cc:90 NCCL WARN Failed to find CUDA library in (null) (NCCL_CUDA_PATH=(null))
A100:5591:5591 [3] NCCL INFO Bootstrap : Using eth0:192.168.0.9<0>
A100:5591:5591 [3] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
A100:5591:5708 [3] NCCL INFO NCCL_IB_DISABLE set by environment to 1.
A100:5591:5708 [3] NCCL INFO NET/Socket : Using [0]eth0:192.168.0.9<0>
A100:5591:5708 [3] NCCL INFO Using network Socket
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5590:5700 [2] NCCL INFO Setting affinity for GPU 2 to ff,ffff0000,00000000
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5589:5698 [1] NCCL INFO Setting affinity for GPU 1 to ffff,ff000000
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5591:5708 [3] NCCL INFO Setting affinity for GPU 3 to ffffff00,00000000,00000000
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 0(=100000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 1(=200000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 2(=300000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 3(=400000)
A100:5588:5697 [0] NCCL INFO Setting affinity for GPU 0 to ffffff
A100:5588:5697 [0] NCCL INFO Channel 00/04 :    0   1   2   3
A100:5588:5697 [0] NCCL INFO Channel 01/04 :    0   3   2   1
A100:5588:5697 [0] NCCL INFO Channel 02/04 :    0   1   2   3
A100:5588:5697 [0] NCCL INFO Channel 03/04 :    0   3   2   1
A100:5588:5697 [0] NCCL INFO Trees [0] 1/-1/-1->0->-1 [1] 3/-1/-1->0->-1 [2] 1/-1/-1->0->-1 [3] 3/-1/-1->0->-1
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5591:5708 [3] NCCL INFO Trees [0] -1/-1/-1->3->2 [1] 2/-1/-1->3->0 [2] -1/-1/-1->3->2 [3] 2/-1/-1->3->0
A100:5590:5700 [2] NCCL INFO Trees [0] 3/-1/-1->2->1 [1] 1/-1/-1->2->3 [2] 3/-1/-1->2->1 [3] 1/-1/-1->2->3
A100:5589:5698 [1] NCCL INFO Trees [0] 2/-1/-1->1->0 [1] -1/-1/-1->1->2 [2] 2/-1/-1->1->0 [3] -1/-1/-1->1->2
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5591:5708 [3] NCCL INFO Channel 00 : 3[400000] -> 0[100000] via SHM/direct/direct
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5591:5708 [3] NCCL INFO Channel 02 : 3[400000] -> 0[100000] via SHM/direct/direct
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5589:5698 [1] NCCL INFO Channel 00 : 1[200000] -> 2[300000] via SHM/direct/direct
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5588:5697 [0] NCCL INFO Channel 00/0 : 0[100000] -> 1[200000] via P2P/IPC/read
A100:5589:5698 [1] NCCL INFO Channel 02 : 1[200000] -> 2[300000] via SHM/direct/direct
A100:5588:5697 [0] NCCL INFO Channel 02/0 : 0[100000] -> 1[200000] via P2P/IPC/read
A100:5590:5700 [2] NCCL INFO Channel 00/0 : 2[300000] -> 3[400000] via P2P/IPC/read
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5588:5697 [0] NCCL INFO Channel 01 : 0[100000] -> 3[400000] via SHM/direct/direct
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5588:5697 [0] NCCL INFO Channel 03 : 0[100000] -> 3[400000] via SHM/direct/direct
A100:5590:5700 [2] NCCL INFO Channel 02/0 : 2[300000] -> 3[400000] via P2P/IPC/read
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Channel 01 : 2[300000] -> 1[200000] via SHM/direct/direct
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Channel 03 : 2[300000] -> 1[200000] via SHM/direct/direct
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5589:5698 [1] NCCL INFO Channel 01/0 : 1[200000] -> 0[100000] via P2P/IPC/read
A100:5589:5698 [1] NCCL INFO Channel 03/0 : 1[200000] -> 0[100000] via P2P/IPC/read
A100:5591:5708 [3] NCCL INFO Channel 01/0 : 3[400000] -> 2[300000] via P2P/IPC/read
A100:5591:5708 [3] NCCL INFO Channel 03/0 : 3[400000] -> 2[300000] via P2P/IPC/read
A100:5589:5698 [1] NCCL INFO Connected all rings
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5589:5698 [1] NCCL INFO Channel 01 : 1[200000] -> 2[300000] via SHM/direct/direct
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5589:5698 [1] NCCL INFO Channel 03 : 1[200000] -> 2[300000] via SHM/direct/direct
A100:5591:5708 [3] NCCL INFO Connected all rings
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5588:5697 [0] NCCL INFO Connected all rings
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5591:5708 [3] NCCL INFO Channel 01 : 3[400000] -> 0[100000] via SHM/direct/direct
A100:5591:5708 [3] NCCL INFO Could not enable P2P between dev 3(=400000) and dev 0(=100000)
A100:5591:5708 [3] NCCL INFO Channel 03 : 3[400000] -> 0[100000] via SHM/direct/direct
A100:5590:5700 [2] NCCL INFO Connected all rings
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5588:5697 [0] NCCL INFO Could not enable P2P between dev 0(=100000) and dev 3(=400000)
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Channel 01/0 : 2[300000] -> 3[400000] via P2P/IPC/read
A100:5590:5700 [2] NCCL INFO Channel 03/0 : 2[300000] -> 3[400000] via P2P/IPC/read
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Channel 00 : 2[300000] -> 1[200000] via SHM/direct/direct
A100:5590:5700 [2] NCCL INFO Could not enable P2P between dev 2(=300000) and dev 1(=200000)
A100:5590:5700 [2] NCCL INFO Channel 02 : 2[300000] -> 1[200000] via SHM/direct/direct
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5591:5708 [3] NCCL INFO Channel 00/0 : 3[400000] -> 2[300000] via P2P/IPC/read
A100:5591:5708 [3] NCCL INFO Channel 02/0 : 3[400000] -> 2[300000] via P2P/IPC/read
A100:5591:5708 [3] NCCL INFO Connected all trees
A100:5591:5708 [3] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
A100:5591:5708 [3] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
A100:5589:5698 [1] NCCL INFO Could not enable P2P between dev 1(=200000) and dev 2(=300000)
A100:5589:5698 [1] NCCL INFO Channel 00/0 : 1[200000] -> 0[100000] via P2P/IPC/read
A100:5589:5698 [1] NCCL INFO Channel 02/0 : 1[200000] -> 0[100000] via P2P/IPC/read
A100:5588:5697 [0] NCCL INFO Connected all trees
A100:5588:5697 [0] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
A100:5588:5697 [0] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
A100:5589:5698 [1] NCCL INFO Connected all trees
A100:5589:5698 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
A100:5589:5698 [1] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
A100:5590:5700 [2] NCCL INFO Connected all trees
A100:5590:5700 [2] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 512 | 512
A100:5590:5700 [2] NCCL INFO 4 coll channels, 4 p2p channels, 2 p2p channels per peer
A100:5588:5697 [0] NCCL INFO comm 0x7d2a66f0 rank 0 nranks 4 cudaDev 0 busId 100000 - Init COMPLETE
A100:5589:5698 [1] NCCL INFO comm 0x7974ec50 rank 1 nranks 4 cudaDev 1 busId 200000 - Init COMPLETE
A100:5590:5700 [2] NCCL INFO comm 0x7c91fa20 rank 2 nranks 4 cudaDev 2 busId 300000 - Init COMPLETE
A100:5591:5708 [3] NCCL INFO comm 0x777188d0 rank 3 nranks 4 cudaDev 3 busId 400000 - Init COMPLETE
Booster init max CUDA memory: 1378.09 MB
Booster init max CPU memory: 13356.70 MB
Epoch 0:   0%|          | 0/58157 [00:00<?, ?it/s]finish_collection 582finish_collection 582

finish_collection 582
finish_collection 582
Epoch 0:   0%|          | 24/58157 [01:37<59:22:18,  3.68s/it, loss=32.6]../aten/src/ATen/native/cuda/Indexing.cu:1141: indexSelectLargeIndex: block: [545,0,0], thread: [96,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/326342b6-58b8-4122-8460-cf1f9fe1c289)

![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/72079145-12e4-47e9-88a3-b52990a14f39)
![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/46060219-87fe-4303-ab83-26aac60cee1a)
![image](https://github.com/hpcaitech/ColossalAI/assets/15274284/88ecf16b-90c6-422f-ac3f-1342175d6958)

RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so 
the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
terminate called after throwing an instance of 'c10::Error'
  what():  CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Exception raised from c10_cuda_check_implementation at ../c10/cuda/CUDAException.cpp:31 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x57 (0x7f13dbd4a457 in /aml/conda/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::string const&) + 0x64 (0x7f13dbd143ec in /aml/conda/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #2: c10::cuda::c10_cuda_check_implementation(std::string const&, std::string const&, int, bool) + 0xb4 (0x7f1406db6c64 in /aml/conda/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #3: <unknown function> + 0x1e0dc (0x7f1406d8e0dc in /aml/conda/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #4: c10::cuda::CUDACachingAllocator::raw_delete(void*) + 0x244 (0x7f1406d91054 in /aml/conda/lib/python3.10/site-packages/torch/lib/libc10_cuda.so)
frame #5: <unknown function> + 0x4d7d63 (0x7f1431c77d63 in /aml/conda/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #6: c10::TensorImpl::~TensorImpl() + 0x1a0 (0x7f13dbd2a9e0 in /aml/conda/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #7: c10::TensorImpl::~TensorImpl() + 0x9 (0x7f13dbd2aaf9 in /aml/conda/lib/python3.10/site-packages/torch/lib/libc10.so)
frame #8: <unknown function> + 0x735788 (0x7f1431ed5788 in /aml/conda/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #9: THPVariable_subclass_dealloc(_object*) + 0x2a5 (0x7f1431ed5a75 in /aml/conda/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
frame #10: /aml/conda/bin/python() [0x4ec258]
frame #11: /aml/conda/bin/python() [0x4f8523]
frame #12: /aml/conda/bin/python() [0x508059]
frame #13: /aml/conda/bin/python() [0x5080bb]
frame #14: /aml/conda/bin/python() [0x4e14e2]
frame #15: PyDict_SetItemString + 0x52 (0x4e46b2 in /aml/conda/bin/python)
frame #16: /aml/conda/bin/python() [0x5c8464]
frame #17: Py_FinalizeEx + 0x164 (0x5c7554 in /aml/conda/bin/python)
frame #18: Py_RunMain + 0x109 (0x5b9379 in /aml/conda/bin/python)
frame #19: Py_BytesMain + 0x39 (0x588099 in /aml/conda/bin/python)
frame #20: __libc_start_main + 0xe7 (0x7f1454218c87 in /lib/x86_64-linux-gnu/libc.so.6)
frame #21: /aml/conda/bin/python() [0x587f4e]

WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5588 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5589 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 5591 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 2 (pid: 5590) of binary: /aml/conda/bin/python
Traceback (most recent call last):
  File "/aml/conda/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/aml/conda/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/aml/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/aml/conda/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/aml/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/aml/conda/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
=====================================================
pretrain.py FAILED
-----------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
-----------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-11-11_01:16:41
  host      : a100.internal.chinacloudapp.cn
  rank      : 2 (local_rank: 2)
  exitcode  : -6 (pid: 5590)
  error_file: <N/A>
  traceback : Signal 6 (SIGABRT) received by PID 5590
=====================================================
Error: failed to run torchrun --nproc_per_node=4 --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=29500 pretrain.py --d /aml/data/boyang/RedPajama-Data-1T-Sample -p gemini_auto -c 7b -b 4 -x fp16 -l 512 on A100, is localhost: True, exception: Encountered a bad command exit code!

### Environment

Ubuntu:18.04
torch 1.13.1
cuda 11.7
Colossal-AI the lastest version

hardware: 4*A100 80G

**Comment by hellangleZ** [comment]
Environment
Ubuntu:18.04
torch 1.13.1
cuda 11.7
Colossal-AI the lastest version

hardware: 4*A100 80G  PCIE,  not SXM

**Comment by hellangleZ** [comment]
Resolved , it due to a rare risk, I use Alpaca embedding vocb to to the demo, after change to a new vocb, the issue not raised again.
