### ISSUE TITLE
[BUG]: RuntimeError: value cannot be converted to type float without overflow

### ISSUE THREAD

**Issue by ericxsun** [hpcaitech/ColossalAI#5182]
### 🐛 Describe the bug

When using GeminiPlugin, I got a RuntimeError: `RuntimeError: value cannot be converted to type float without overflow`

the full traceback:

```
Traceback (most recent call last):

File "pretrain.py", line 395, in <module>

main(args, cfg)

File "pretrain.py", line 241, in main

raise e

File "pretrain.py", line 219, in main

optimizer.step()

File ".local/lib/python3.10/site-packages/colossalai/zero/gemini/gemini_optimizer.py", line 276, in step

combined_scale = self._get_combined_scale()

File ".local/lib/python3.10/site-packages/colossalai/zero/gemini/gemini_optimizer.py", line 249, in _get_combined_scale

total_norm = self._calc_global_norm()

File ".local/lib/python3.10/site-packages/colossalai/zero/gemini/gemini_optimizer.py", line 238, in _calc_global_norm

comm_buffer.fill_(part_norm)

RuntimeError: value cannot be converted to type float without overflow

```

### Environment

Pytorch: 2.0.1
ColossalAI: main branch

**Comment by flybird11111** [comment]
Thanks, I'll look into it.

**Comment by ericxsun** [comment]
> Hi, I haven't been able to reproduce this issue. From the code, it seems that part_norm itself is of type float.

Thanks.

I suspect it might be related to the issue documented here: https://github.com/hpcaitech/ColossalAI/issues/5110. `RuntimeError: value cannot be converted to type float without overflow`  occurred during training after 1273 steps with GeminiPlugin, using tensor_parallel(tp_size=8), and employing the flash-attn-2.
