### ISSUE TITLE
[BUG]: Assert Error while Freeze some layers （GeminiPlugin)

### ISSUE THREAD

**Issue by ericxsun** [hpcaitech/ColossalAI#5290]
### 🐛 Describe the bug

*Note: Things progress smoothly when no layers are frozen.*

Got an assert problem when freeze some layers:

```
booster = GeminiPlugin(...)

model = ...from_pretrained(...)
model.requires_grad_(False)
for name, parameter in model.named_parameters():
    for idx in ext_layers:
        if f"layers.{idx}." in name:
            parameter.requires_grad_(True)

optimizer = HybridAdam(model.parameters(), ...)
lr_scheduler = ...
model, optimizer, _, _, lr_scheduler = booster.boost(model, optimizer, lr_scheduler=lr_scheduler)
```

the full traceback
```
Traceback (most recent call last):
  File "debug_train.py", line 132, in <module>
    debug_main()
  File "debug_train.py", line 128, in debug_main
    main(args, cfg)
  File "pretrain.py", line 264, in main
    raise e
  File "pretrain.py", line 228, in main
    outputs = model(
  File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File ".local/lib/python3.10/site-packages/colossalai/zero/gemini/gemini_ddp.py", line 271, in forward
    outputs = self.module(*args, **kwargs)
  File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "zoo/phi2/modeling_phi.py", line 938, in forward
    outputs = self.model(
  File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "zoo/phi2/modeling_phi.py", line 833, in forward
    layer_outputs = self._gradient_checkpointing_func(
  File ".local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File ".local/lib/python3.10/site-packages/torch/autograd/function.py", line 506, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File ".local/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "zoo/phi2/modeling_phi.py", line 677, in forward
    attn_outputs, self_attn_weights, present_key_value = self.self_attn(
  File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "zoo/phi2/modeling_phi.py", line 427, in forward
    query_states = self.q_proj(hidden_states)
  File ".local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File ".local/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
  File ".local/lib/python3.10/site-packages/colossalai/tensor/colo_parameter.py", line 61, in __torch_function__
    new_args = ColoParamOpHookManager.pre_op(params, *args, *kwargs.values())
  File ".local/lib/python3.10/site-packages/colossalai/tensor/param_op_hook.py", line 88, in pre_op
    grad_args, other_args, grad_flags, spec = _flatten_grad_args(args)
  File ".local/lib/python3.10/site-packages/colossalai/tensor/param_op_hook.py", line 145, in _flatten_grad_args
    assert len(grad_args) > 0
AssertionError
```

### Environment

Colossalai: main branch
Pytorch: 2.0.1

**Comment by ericxsun** [comment]
It appears strange that when utilizing LazyInitContext, the `requires_grad` attribute of a parameter is set to False following the `_preprocess_param` step in `GeminiDPP._init_chunks`.

Upon closer examination, it seems that `p.__init__(p, requires_grad=requires_grad)` does not correctly assign the requires_grad property. https://github.com/hpcaitech/ColossalAI/blob/f7e3f82a7e49057593932bbd8d9f1797c7584bf6/colossalai/zero/gemini/gemini_ddp.py#L835

**Comment by flybird11111** [comment]
It is true that freezing specific layers is incompatible with the Gemini strategy. If all layers are frozen, you can use the Gemini strategy for inference.

**Comment by ericxsun** [comment]
> It is true that freezing specific layers is incompatible with the Gemini strategy. If all layers are frozen, you can use the Gemini strategy for inference.

@flybird11111  thanks

However, it appears that none of the plugins, including Gemini, LowLevelZeroPlugin, and HybridParallelPlugin, are functioning.

with  `LowLevelZeroPlugin(stage=1, ...)` or `LowLevelZeroPlugin(stage=2, ...)` 

```
Traceback (most recent call last):
  File "debug_train.py", line 133, in <module>
    debug_main()
  File "debug_train.py", line 129, in debug_main
    main(args, cfg)
  File "pretrain.py", line 285, in main
    raise e
  File "pretrain.py", line 259, in main
    booster.backward(loss, optimizer)
  File ".local/lib/python3.10/site-packages/colossalai/booster/booster.py", line 167, in backward
    optimizer.backward(loss)
  File ".local/lib/python3.10/site-packages/colossalai/zero/low_level/low_level_optim.py", line 480, in backward
    loss.backward(retain_graph=retain_graph)
  File ".local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File ".local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

and with `HybridParallelPlugin`:
```
Traceback (most recent call last):
  File "debug_train.py", line 133, in <module>
    debug_main()
  File "debug_train.py", line 129, in debug_main
    main(args, cfg)
  File "pretrain.py", line 285, in main
    raise e
  File "pretrain.py", line 259, in main
    booster.backward(loss, optimizer)
  File ".local/lib/python3.10/site-packages/colossalai/booster/booster.py", line 167, in backward
    optimizer.backward(loss)
  File ".local/lib/python3.10/site-packages/colossalai/booster/plugin/hybrid_parallel_plugin.py", line 492, in backward
    super().backward(loss, *args, **kwargs)
  File ".local/lib/python3.10/site-packages/colossalai/amp/naive_amp/mixed_precision_optimizer.py", line 90, in backward
    loss.backward(*args, **kwargs)
  File ".local/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File ".local/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

**Comment by ericxsun** [comment]
Hi, @flybird11111 could you take a look? Thanks very much.

**Comment by ericxsun** [comment]
Use TorchFSDP plugin(it can freeze layers), and : 

```
model.gradient_checkpointing_enable(gradient_checkpointing_kwargs={"use_reentrant": False})
```

things go well.
