### ISSUE TITLE
Grok-1: ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address

### ISSUE THREAD

**Issue by nijisakai** [hpcaitech/ColossalAI#5527]
Follow the guide from <https://github.com/hpcaitech/ColossalAI/tree/main/examples/language/grok-1>
and got this error.

(/SSD_DATA/chenhy/anaconda_envs/xai) [chenhy@centos7gpu grok-1]$ ./run_inference_fast.sh /HDD_DATA/chenhy/xai/grok-1/
[2024-03-28 09:35:31,685] torch.distributed.run: [WARNING] master_addr is only used for static rdzv_backend and when rdzv_endpoint is not specified.
[2024-03-28 09:35:31,685] torch.distributed.run: [WARNING]
[2024-03-28 09:35:31,685] torch.distributed.run: [WARNING] *****************************************
[2024-03-28 09:35:31,685] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2024-03-28 09:35:31,685] torch.distributed.run: [WARNING] *****************************************
Traceback (most recent call last):
  File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
    colossalai.launch_from_torch({})
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
    launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
    rendezvous_iterator = rendezvous(
                          ^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
    return _rendezvous_helper(url, rank, world_size, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
    result = urlparse(url)
             ^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
    _check_bracketed_host(bracketed_host)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
Traceback (most recent call last):
  File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
    colossalai.launch_from_torch({})
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
    launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
    rendezvous_iterator = rendezvous(
                          ^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
    return _rendezvous_helper(url, rank, world_size, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
    result = urlparse(url)
             ^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
    _check_bracketed_host(bracketed_host)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
Traceback (most recent call last):
  File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
    colossalai.launch_from_torch({})
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
    launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
    rendezvous_iterator = rendezvous(
                          ^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
    return _rendezvous_helper(url, rank, world_size, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
    result = urlparse(url)
             ^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
    _check_bracketed_host(bracketed_host)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
Traceback (most recent call last):
  File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
    colossalai.launch_from_torch({})
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
    launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
    rendezvous_iterator = rendezvous(
                          ^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
    return _rendezvous_helper(url, rank, world_size, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
    result = urlparse(url)
             ^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
    _check_bracketed_host(bracketed_host)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py:48: UserWarning: `config` is deprecated and will be removed soon.
  warnings.warn("`config` is deprecated and will be removed soon.")
Traceback (most recent call last):
  File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
    colossalai.launch_from_torch({})
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
    launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
    rendezvous_iterator = rendezvous(
                          ^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
    return _rendezvous_helper(url, rank, world_size, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
    result = urlparse(url)
             ^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
    _check_bracketed_host(bracketed_host)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
Traceback (most recent call last):
  File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
    colossalai.launch_from_torch({})
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
    launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
    rendezvous_iterator = rendezvous(
                          ^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
    return _rendezvous_helper(url, rank, world_size, **kwargs)
         Traceback (most recent call last):
    File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
^^^^^^^^^^^^^^^^^^^^^^^^^^^    ^colossalai.launch_from_torch({})
^^^^^^^^^^^  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
    launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    result = urlparse(url)
            dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
   ^^^^^^^^^  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    func_return = func(*args, **kwargs)
                  Traceback (most recent call last):
    splitresult = urlsplit(url, scheme, allow_fragments)
^^^  File "/SSD_DATA/chenhy/ColossalAI/examples/language/grok-1/inference_tp.py", line 19, in <module>
^^  ^^ ^^ ^  ^  ^  ^^ ^^  ^^  ^  ^ ^^
^^^      File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
^colossalai.launch_from_torch({})^
^^^^^^^^^  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 173, in launch_from_torch
^^^^^^^^^^^^^^^^^^^^^^^
      File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/colossalai/initialize.py", line 56, in launch
    dist.init_process_group(rank=rank, world_size=world_size, backend=backend, init_method=init_method)
    rendezvous_iterator = rendezvous(
   File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
            _check_bracketed_host(bracketed_host)
          func_return = func(*args, **kwargs)   File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host

      ^^ ^   ^^  ^^  ^  ^^  ^
    File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
   ^^ ^  ^^  ^^ ^^   ^^^    ^^^^return _rendezvous_helper(url, rank, world_size, **kwargs)^^^
^^^^^^^^^^^^^
^^  ^   File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1138, in init_process_group
 ^  ^^^^^^^^^^^ ^^ ^^
   File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
  ^^^^^^^^^    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
^^^^^^^^^ValueError: ^^'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
^^^^^^^^^^^^^^^^^^^^^^    ^^rendezvous_iterator = rendezvous(^^
^^^ ^^
   File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
                  result = urlparse(url)
         ^ ^  ^^  ^  ^^  ^  ^^ ^^^^
^  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 98, in rendezvous
^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    return _rendezvous_helper(url, rank, world_size, **kwargs)
           ^^^^^^^^^^^    ^^^splitresult = urlsplit(url, scheme, allow_fragments)^^^
^ ^^   ^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/rendezvous.py", line 60, in _rendezvous_helper
^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
    result = urlparse(url)
             ^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 395, in urlparse
    _check_bracketed_host(bracketed_host)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host
    splitresult = urlsplit(url, scheme, allow_fragments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^    ^ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4^
^^^^^^^^^^
     File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 500, in urlsplit
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
    _check_bracketed_host(bracketed_host)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/urllib/parse.py", line 446, in _check_bracketed_host
    ip = ipaddress.ip_address(hostname) # Throws Value Error if not IPv6 or IPv4
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/ipaddress.py", line 54, in ip_address
    raise ValueError(f'{address!r} does not appear to be an IPv4 or IPv6 address')
ValueError: 'localhost.localdomain' does not appear to be an IPv4 or IPv6 address
[2024-03-28 09:35:37,010] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 24288) of binary: /SSD_DATA/chenhy/anaconda_envs/xai/bin/python
Traceback (most recent call last):
  File "/SSD_DATA/chenhy/anaconda_envs/xai/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/run.py", line 806, in main
    run(args)
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/run.py", line 797, in run
    elastic_launch(
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/SSD_DATA/chenhy/anaconda_envs/xai/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 264, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
inference_tp.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 24289)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 24290)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 24291)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 24292)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 24293)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[6]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 24294)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[7]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 24295)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-28_09:35:37
  host      : localhost.localdomain
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 24288)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

**Comment by nijisakai** [comment]
Fixed after change python from 3.11 to 3.10

**Comment by yuanheng-zhao** [comment]
> Fixed after change python from 3.11 to 3.10

Closed as the issue has been fixed. Please let us know if any other issue exists.
