### ISSUE TITLE
When I execute `colossalai run --nproc_per_node 2 --master_addr localhost --master_port 29500 train.py`, I encounter an error.

### ISSUE THREAD

**Issue by awer-A** [hpcaitech/ColossalAI#5540]
### 🐛 Describe the bug

```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from data.bert_helper import SequenceParallelDataIterator, get_batch_for_sequence_parallel
  File "/GPUFS/nsccgz_ywang_zfd/bfy/ColossalAI/examples/tutorial/sequence_parallel/data/__init__.py", line 3, in <module>
    from colossalai.legacy.context import ParallelMode
ModuleNotFoundError: No module named 'colossalai.legacy'
Traceback (most recent call last):
  File "train.py", line 4, in <module>
    from data.bert_helper import SequenceParallelDataIterator, get_batch_for_sequence_parallel
  File "/GPUFS/nsccgz_ywang_zfd/bfy/ColossalAI/examples/tutorial/sequence_parallel/data/__init__.py", line 3, in <module>
    from colossalai.legacy.context import ParallelMode
ModuleNotFoundError: No module named 'colossalai.legacy'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 37766) of binary: /GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/bin/python
Traceback (most recent call last):
  File "/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.12.1', 'console_scripts', 'torchrun')())
  File "/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/run.py", line 761, in main
    run(args)
  File "/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/run.py", line 752, in run
    elastic_launch(
  File "/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-03-31_19:53:21
  host      : deeplearning-v191204-bfy-a800n
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 37767)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-03-31_19:53:21
  host      : deeplearning-v191204-bfy-a800n
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 37766)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Error: failed to run torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=localhost:29500 --rdzv_id=colossalai-default-job train.py on 127.0.0.1, is localhost: True, exception: Encountered a bad command exit code!

Command: 'cd /GPUFS/nsccgz_ywang_zfd/bfy/ColossalAI/examples/tutorial/sequence_parallel && export CONDA_SHLVL="1" CONDA_EXE="/app/common/anaconda3/5.4.0/bin/conda" SSH_CONNECTION="192.168.11.192 49734 192.168.214.76 22" LANG="zh_CN.UTF-8" OLDPWD="/GPUFS/nsccgz_ywang_zfd/bfy/ColossalAI/examples/tutorial" LOADEDMODULES_modshare="proxy/1.0.0:1" COLORTERM="truecolor" CONDA_PREFIX="/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold" MODULES_CMD="/usr/local/Modules/libexec/modulecmd.tcl" USER="nsccgz_ywang_zfd" ENV="/usr/local/Modules/init/profile.sh" PWD="/GPUFS/nsccgz_ywang_zfd/bfy/ColossalAI/examples/tutorial/sequence_parallel" HOME="/GPUFS/nsccgz_ywang_zfd" CONDA_PYTHON_EXE="/app/common/anaconda3/5.4.0/bin/python" BROWSER="/GPUFS/nsccgz_ywang_zfd/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/bin/helpers/browser.sh" VSCODE_GIT_ASKPASS_NODE="/GPUFS/nsccgz_ywang_zfd/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/node" TERM_PROGRAM="vscode" SSH_CLIENT="192.168.11.192 49734 22" TERM_PROGRAM_VERSION="1.86.2" https_proxy="http://10.20.18.21:3128" BASH_ENV="/usr/local/Modules/init/bash" _LMFILES__modshare="/app/ubuntu/modulefiles/proxy/1.0.0:1" http_proxy="http://10.20.18.21:3128" MKL_INTERFACE_LAYER="LP64,GNU" GSETTINGS_SCHEMA_DIR="/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/share/glib-2.0/schemas" VSCODE_IPC_HOOK_CLI="/tmp/vscode-ipc-035b4211-842f-45f9-b68a-e247011ca5a4.sock" LOADEDMODULES="proxy/1.0.0" CONDA_PROMPT_MODIFIER="(fastfold) " MAIL="/var/mail/nsccgz_ywang_zfd" VSCODE_GIT_ASKPASS_MAIN="/GPUFS/nsccgz_ywang_zfd/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/extensions/git/dist/askpass-main.js" TERM="xterm-256color" SHELL="/bin/bash" all_proxy="socks5://10.20.18.21:3128" CONDA_ROOT="/GPUFS/nsccgz_ywang_zfd/miniconda3" SHLVL="4" LANGUAGE="zh_CN:zh:en_US:en" PYTHONPATH="/GPUFS/nsccgz_ywang_zfd/bfy/ColossalAI/examples/tutorial/sequence_parallel" VSCODE_GIT_IPC_HANDLE="/tmp/vscode-git-c9de2caaef.sock" MANPATH="/usr/local/Modules/share/man" MODULEPATH="/app/ubuntu/modulefiles" LOGNAME="nsccgz_ywang_zfd" GIT_ASKPASS="/GPUFS/nsccgz_ywang_zfd/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/extensions/git/dist/askpass.sh" MODULEPATH_modshare="/app/ubuntu/modulefiles:1" PATH="/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/bin:/app/common/anaconda3/5.4.0/condabin:/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/bin:/app/common/anaconda3/5.4.0/condabin:/GPUFS/nsccgz_ywang_zfd/.vscode-server/bin/903b1e9d8990623e3d7da1df3d33db3e42d80eda/bin/remote-cli:/app/ubuntu/bin:/app/ubuntu/bin:/tools/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" _LMFILES_="/app/ubuntu/modulefiles/proxy/1.0.0" PS1="\\[\x1b]633;A\x07\\](fastfold) ${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$ \\[\x1b]633;B\x07\\]" MODULESHOME="/usr/local/Modules" CONDA_DEFAULT_ENV="fastfold" ftp_proxy="10.20.18.21:3128" XML_CATALOG_FILES="file:///GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/etc/xml/catalog file:///etc/xml/catalog" _="/GPUFS/nsccgz_ywang_zfd/miniconda3/envs/fastfold/bin/colossalai" && torchrun --nproc_per_node=2 --nnodes=1 --node_rank=0 --rdzv_backend=c10d --rdzv_endpoint=localhost:29500 --rdzv_id=colossalai-default-job train.py'

Exit code: 1

Stdout: already printed

Stderr: already printed



====== Training on All Nodes =====
127.0.0.1: failure

====== Stopping All Nodes =====
127.0.0.1: finish
```

### Environment

Python 3.8.18
CUDA 11.3.1
Pytorch  1.12.1

**Comment by Edenzzzz** [comment]
Please reformat to make your error more visible. 
Since "colossalai.legacy" is missing, your environment doesn't have colossalai properly installed. Please follow the installation instructions to reinstall your environment.

**Comment by Edenzzzz** [comment]
This happens only when sequence parallel is on and ZeRO is off. We are rebuilding the seq parallel API with ring attention etc., so I've set it to False in enable_all_optimization as a quick fix.

**Comment by awer-A** [comment]
@Edenzzzz 
Can you tell me which branch of colossalai I should install, When I reinstalled colossalai I got an error`ModuleNotFoundError: No module named 'colossalai.kernel.cuda_native'`
