### ISSUE TITLE
[BUG]: RuntimeErrorRuntimeError: : The param bucket max size 12582912 is exceededby tensor (size 131334144)The param bucket max size 12582912 is exceededby tensor (size 131334144)

### ISSUE THREAD

**Issue by zhurunhua** [hpcaitech/ColossalAI#5935]
### Is there an existing issue for this bug?

- [X] I have searched the existing issues

### 🐛 Describe the bug

I got an error when I do sft training , using ColossalAI-0.4.0/applications/Colossal-LLaMA/train.py, the base model is llama3-8B-instruct, And there is the detail error occurred:
```
RuntimeErrorRuntimeError: : The param bucket max size 12582912 is exceededby tensor (size 131334144)The param bucket max size 12582912 is exceededby tensor (size 131334144)



During handling of the above exception, another exception occurred:
During handling of the above exception, another exception occurred:


Traceback (most recent call last):
Traceback (most recent call last):
  File "/mnt/data/tool/ColossalAI-0.4.0/applications/Colossal-LLaMA/train.py", line 425, in <module>
  File "/mnt/data/tool/ColossalAI-0.4.0/applications/Colossal-LLaMA/train.py", line 425, in <module>
    main()
    main()
  File "/mnt/data/tool/ColossalAI-0.4.0/applications/Colossal-LLaMA/train.py", line 357, in main
  File "/mnt/data/tool/ColossalAI-0.4.0/applications/Colossal-LLaMA/train.py", line 357, in main
    optimizer.step()
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/low_level_optim.py", line 717, in step
    optimizer.step()
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/low_level_optim.py", line 717, in step
    tensor_bucket.all_gather(self._bucket_store.moe_extra_dp_pg)
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/bookkeeping/tensor_bucket.py", line 65, in all_gather
    tensor_bucket.all_gather(self._bucket_store.moe_extra_dp_pg)
    flat = self.flatten()
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/bookkeeping/tensor_bucket.py", line 65, in all_gather
           ^^^^^^^^^^^^^^
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/bookkeeping/tensor_bucket.py", line 54, in flatten
    flat = self.flatten()
           ^^^^^^^^^^    ^return _flatten_dense_tensors(self._bucket)^
^^
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/bookkeeping/tensor_bucket.py", line 54, in flatten
           ^^^^^^^^^^^^^^^^    ^return _flatten_dense_tensors(self._bucket)^
^^^^^^^^^^^^^^^^ ^ ^ 
      File "/home/pai/lib/python3.11/site-packages/torch/_utils.py", line 498, in _flatten_dense_tensors
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pai/lib/python3.11/site-packages/torch/_utils.py", line 498, in _flatten_dense_tensors
    return torch._C._nn.flatten_dense_tensors(tensors)
               return torch._C._nn.flatten_dense_tensors(tensors)^
^^^^^^^^^^^^^^^^^^^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^ ^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^RuntimeError^^: ^torch.cat(): expected a non-empty list of Tensors^
^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: torch.cat(): expected a non-empty list of Tensors
Traceback (most recent call last):
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/low_level_optim.py", line 715, in step
    tensor_bucket.add_to_bucket(param_to_gather, write_back_tensor=working_param)
  File "/home/pai/lib/python3.11/site-packages/colossalai/zero/low_level/bookkeeping/tensor_bucket.py", line 34, in add_to_bucket
    raise RuntimeError(msg)
RuntimeError: The param bucket max size 12582912 is exceededby tensor (size 131334144)
```
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/bca841e0-b1c8-4a41-803c-9f3b9448f8b1">

How can I solve it ?

### Environment

OS:
● ubuntu22.04
● CPU：96c；
● RAM：736 GiB；
● GPU：4 * NVIDIA V100 (32GB)

Software:
● Python 3.11.5；
● ColossalAI 0.4.0；
● cuda_11.8；
● pytorch 2.1.0+cu118

**Comment by zhurunhua** [comment]
the train script is :
```
colossalai run --nproc_per_node 4 --master_port 30013 /mnt/data/tool/ColossalAI-0.4.0/applications/Colossal-LLaMA/train.py \
    --pretrained $PRETRAINED_MODEL_PATH \
    --dataset ${dataset[@]} \
    --plugin zero2_cpu \
    --save_dir $SAVE_DIR \
    --tensorboard_dir $TENSORBOARD_DIR \
    --config_file $CONFIG_FILE \
    --num_epochs 1 \
    --accumulation_steps 1 \
    --micro_batch_size 1 \
    --lr 5e-5 \
    --max_length 512 \
    --save_interval 8000 \
    --use_grad_checkpoint
```

**Comment by Edenzzzz** [comment]
We recently pushed a fix for this (https://github.com/hpcaitech/ColossalAI/commit/ea94c07b959e8895b713d6dd68b168ea37db6b7b). Could you pull the latest main?

**Comment by zhurunhua** [comment]
Thanks，I'll try, Is this related to the specifications of my GPU?

**Comment by zhurunhua** [comment]
> We recently pushed a fix for this ([ea94c07](https://github.com/hpcaitech/ColossalAI/commit/ea94c07b959e8895b713d6dd68b168ea37db6b7b)). Could you pull the latest main?

I tried using the latest code, but still got the same error, But this time the error was reported a bit late

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/80994af2-40a3-41a6-9893-b05f7dfadba8">

**Comment by Edenzzzz** [comment]
Have you reinstalled after pulling or used `pip install -e .` ?

**Comment by zhurunhua** [comment]
I didn't do this, I'll try it tomorrow, Thanks a lot.

**Comment by zhurunhua** [comment]
> Have you reinstalled after pulling or used `pip install -e .` ?

It's work, Thanks.
