### ISSUE TITLE
[BUG]: Dependence of math.dist which is new in py3.8

### ISSUE THREAD

**Issue by zouzh14** [hpcaitech/ColossalAI#996]
### 🐛 Describe the bug

I installed Colossal-AI in python 3.7.12 and it reported an error "ImportError: cannot import name 'dist' from 'math'" which seems for the lack of math.dist in python 3.7.

### How do I install?

I installed Colossal-AI package in an existing pytorch conda env with pip:

```
pip install colossalai==0.1.5+torch1.10cu11.3 -f https://release.colossalai.org
```

And test with

```
colossalai check -i
```

Then it reported the error:

```
Traceback (most recent call last):
  File "/data/XXX/anaconda3/envs/torch/bin/colossalai", line 5, in <module>
    from colossalai.cli import cli
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/__init__.py", line 1, in <module>
    from .initialize import (initialize, launch, launch_from_openmpi,
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/initialize.py", line 23, in <module>
    from colossalai.engine.schedule import NonPipelineSchedule, PipelineSchedule, InterleavedPipelineSchedule, get_tensor_shape
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/engine/__init__.py", line 1, in <module>
    from ._base_engine import Engine
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/engine/_base_engine.py", line 11, in <module>
    from colossalai.engine.schedule import BaseSchedule, NonPipelineSchedule, PipelineSchedule, InterleavedPipelineSchedule
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/engine/schedule/__init__.py", line 1, in <module>
    from ._base_schedule import BaseSchedule
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/engine/schedule/_base_schedule.py", line 10, in <module>
    from colossalai.utils import get_current_device
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/utils/__init__.py", line 15, in <module>
    from .model.colo_init_context import ColoInitContext
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/utils/model/colo_init_context.py", line 3, in <module>
    from colossalai.tensor import ColoTensor, ColoParameter
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/tensor/__init__.py", line 4, in <module>
    from .colo_tensor import ColoTensor
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/tensor/colo_tensor.py", line 12, in <module>
    from colossalai.tensor.dist_spec_mgr import DistSpecManager
  File "/data/XXX/anaconda3/envs/torch/lib/python3.7/site-packages/colossalai/tensor/dist_spec_mgr.py", line 1, in <module>
    from math import dist
ImportError: cannot import name 'dist' from 'math' (/data/zouziheng/anaconda3/envs/torch/lib/python3.7/lib-dynload/math.cpython-37m-x86_64-linux-gnu.so)
```

### Environment

CUDA: 11.3
cUDNN: 8200
NCCL: (2, 10, 3)
Python: 3.7.12
PyTorch: 1.10.0

**Comment by FrankLeeeee** [comment]
Hi, thanks for spotting this bug. We will fix it asap.
